/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package producto;

import ModelClass.TextFieldEven;
import alertas.principal.AWTUtilities;
import alertas.principal.ErrorAlert;
import alertas.principal.SuccessAlert;
import conexion.ConexionBD;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import static producto.Opciones.cn;

/**
 *
 * @author Rojeru San
 */
public class ModalProductoMInventario extends javax.swing.JDialog {

    Timer timer = null;
    TimerTask task;
    int i = 32;
    private String cod = "";
    private String nom = "";
    private String des = "";
    private double pc = 0;
    private double pv = 0;
    private double pm = 0;
    private int idprovedor;
    private int cantidad = 0;
    private String tipo = "";
    TextFieldEven evento = new TextFieldEven();
    static ConexionBD cc = new ConexionBD();
    static Connection cn = cc.conexion();

    /**
     * Creates new form ModalProducto
     */
    public ModalProductoMInventario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        AWTUtilities.setOpaque(this, false);

        ConexionBD.conectar();
        comboProveedor.removeAllItems();
        ArrayList<String> lista = new ArrayList<String>();
        lista = conexion.ConexionBD.llenar_combo("proveedores", "empresa_proveedor");
        for (int i = 0; i < lista.size(); i++) {
            comboProveedor.addItem(lista.get(i));
        }

        Ubicar(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        jPanel7 = new javax.swing.JPanel();
        Button_Limpiar = new javax.swing.JButton();
        Button_Guardar = new javax.swing.JButton();
        Label_codPRODUCTO = new javax.swing.JLabel();
        TextField_CODPRODUCTO = new javax.swing.JTextField();
        Label_nomPRODUCTO = new javax.swing.JLabel();
        TextField_nomPRODUCTO = new javax.swing.JTextField();
        Label_desPRODUCTO = new javax.swing.JLabel();
        TextField_desPRODUCTO = new javax.swing.JTextField();
        Label_canPRODUCTO = new javax.swing.JLabel();
        TextField_canPRODUCTO = new javax.swing.JTextField();
        Label_pcPRODUCTO = new javax.swing.JLabel();
        TextField_pcPRODUCTO = new javax.swing.JTextField();
        Label_pvPRODUCTO = new javax.swing.JLabel();
        TextField_pvPRODUCTO = new javax.swing.JTextField();
        Label_pmPRODUCTO = new javax.swing.JLabel();
        TextField_pmPRODUCTO = new javax.swing.JTextField();
        Label_empresaProveedor = new javax.swing.JLabel();
        comboProveedor = new javax.swing.JComboBox<>();
        Label_productoTipo = new javax.swing.JLabel();
        combotipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        idmodal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cerrar = new principal.MaterialButton();
        titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alertas/img/fondo.png"))); // NOI18N
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Limpiar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png"))); // NOI18N
        Button_Limpiar.setText("Limpiar");
        Button_Limpiar.setBorder(null);
        Button_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LimpiarActionPerformed(evt);
            }
        });
        jPanel7.add(Button_Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 100, 39));

        Button_Guardar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Agregar.png"))); // NOI18N
        Button_Guardar.setText("Guardar");
        Button_Guardar.setBorder(null);
        Button_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GuardarActionPerformed(evt);
            }
        });
        jPanel7.add(Button_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 100, 39));

        Label_codPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_codPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        Label_codPRODUCTO.setText("Código");
        Label_codPRODUCTO.setToolTipText("");
        jPanel7.add(Label_codPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 125, 92, -1));

        TextField_CODPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_CODPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_CODPRODUCTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_CODPRODUCTOKeyTyped(evt);
            }
        });
        jPanel7.add(TextField_CODPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 147, 228, -1));

        Label_nomPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_nomPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        Label_nomPRODUCTO.setText("Nombre");
        Label_nomPRODUCTO.setToolTipText("");
        jPanel7.add(Label_nomPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 171, 92, -1));

        TextField_nomPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_nomPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_nomPRODUCTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_nomPRODUCTOKeyTyped(evt);
            }
        });
        jPanel7.add(TextField_nomPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 193, 228, -1));

        Label_desPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_desPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        Label_desPRODUCTO.setText("Descripción");
        Label_desPRODUCTO.setToolTipText("");
        jPanel7.add(Label_desPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 221, 92, -1));

        TextField_desPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_desPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_desPRODUCTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_desPRODUCTOKeyTyped(evt);
            }
        });
        jPanel7.add(TextField_desPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 243, 228, -1));

        Label_canPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_canPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        Label_canPRODUCTO.setText("Cantidad");
        jPanel7.add(Label_canPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 271, 92, -1));

        TextField_canPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_canPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_canPRODUCTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_canPRODUCTOKeyTyped(evt);
            }
        });
        jPanel7.add(TextField_canPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 293, 228, -1));

        Label_pcPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_pcPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        Label_pcPRODUCTO.setText("Precio compra");
        Label_pcPRODUCTO.setToolTipText("");
        jPanel7.add(Label_pcPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 321, 92, -1));

        TextField_pcPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_pcPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_pcPRODUCTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_pcPRODUCTOKeyTyped(evt);
            }
        });
        jPanel7.add(TextField_pcPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 343, 228, -1));

        Label_pvPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_pvPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        Label_pvPRODUCTO.setText("Precio venta");
        jPanel7.add(Label_pvPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 371, 92, -1));

        TextField_pvPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_pvPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_pvPRODUCTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_pvPRODUCTOKeyTyped(evt);
            }
        });
        jPanel7.add(TextField_pvPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 393, 228, -1));

        Label_pmPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_pmPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        Label_pmPRODUCTO.setText("Precio mayorista");
        jPanel7.add(Label_pmPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 421, -1, -1));

        TextField_pmPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_pmPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_pmPRODUCTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_pmPRODUCTOKeyTyped(evt);
            }
        });
        jPanel7.add(TextField_pmPRODUCTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 443, 228, -1));

        Label_empresaProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_empresaProveedor.setForeground(new java.awt.Color(102, 102, 102));
        Label_empresaProveedor.setText("Proveedor");
        jPanel7.add(Label_empresaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 11, 188, -1));

        jPanel7.add(comboProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 33, 228, 30));

        Label_productoTipo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_productoTipo.setForeground(new java.awt.Color(102, 102, 102));
        Label_productoTipo.setText("Tipo");
        jPanel7.add(Label_productoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 69, 188, -1));

        combotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASEO", "HOJAS", "LIBROS", "JUGUETES", "BISUTERIA" }));
        jPanel7.add(combotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 91, 228, 28));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Id");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 20, 30));

        idmodal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(idmodal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 50, 30));

        panel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 440, 530));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 460, 545));

        jPanel2.setBackground(new java.awt.Color(80, 80, 97));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setForeground(new java.awt.Color(80, 80, 97));
        cerrar.setText("X");
        cerrar.setToolTipText("<html> <head> <style> #contenedor{background:white;color:black; padding-left:10px;padding-right:10px;margin:0; padding-top:5px;padding-bottom:5px;} </style> </head> <body> <h4 id=\"contenedor\">Cerrar</h4> </body> </html>");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Datos del producto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        task = new TimerTask() {
            @Override
            public void run() {
                if (i == 0) {
                    Cerrar();
                } else {
                    Ubicar(i);
                    i -= 32;
                    Trasparencia((float) i / 352);
                }
            }
        };
        timer = new Timer();
        timer.schedule(task, 0, 2);
    }//GEN-LAST:event_cerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        task = new TimerTask() {
            @Override
            public void run() {
                if (i == 352) {
                    timer.cancel();
                } else {
                    Ubicar(i);
                    i += 32;
                    Trasparencia((float) i / 352);
                }
            }
        };
        timer = new Timer();
        timer.schedule(task, 0, 2);
    }//GEN-LAST:event_formWindowOpened

    private void Button_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_Button_LimpiarActionPerformed

    private void Button_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GuardarActionPerformed

        if (titulo.getText().equalsIgnoreCase("REGISTRAR")) {
            guardar();
            limpiar();
            this.cod = "";
            this.nom = "";
            this.des = "";
            this.pc = 0;
            this.pv = 0;
            this.pm = 0;
            this.cantidad = 0;
            this.idprovedor = 0;
            
        }

        if (titulo.getText().equalsIgnoreCase("MODIFICAR")) {

            actualizar();
            limpiar();
            this.cod = "";
            this.nom = "";
            this.des = "";
            this.pc = 0;
            this.pv = 0;
            this.pm = 0;
            this.cantidad = 0;
            this.idprovedor = 0;
            this.dispose();
        }


    }//GEN-LAST:event_Button_GuardarActionPerformed

    public void actualizar() {
        if (validar() < 7) {

            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("FALTAN CAMPOS DE LLENAR");
            er.msj1.setText("");
            er.setVisible(true);

        } else {
            producto.Sentencias s = new Sentencias(cod, nom, des, pc, pv, pm, idprovedor, cantidad, tipo);
            s.setId(Integer.parseInt(idmodal.getText()));

            int opcion = producto.Opciones.actualizar(s);
            if (opcion != 0) {

                producto.Opciones.listartodo();

                SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                sa.titulo.setText("¡HECHO!");
                sa.msj.setText("SE HAN GUARDADO LOS CAMBIOS");
                sa.msj1.setText("");
                sa.setVisible(true);
            } else {
                System.out.println(s.toString());
            }
        }

    }

    public void guardar() {

        if (validar() < 7) {

            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("FALTAN CAMPOS DE LLENAR");
            er.msj1.setText("");
            er.setVisible(true);

        } else {
            producto.Sentencias s = new Sentencias(cod, nom, des, pc, pv, pm, idprovedor, cantidad, tipo);

            int opcion = producto.Opciones.registrar(s);
            if (opcion != 0) {

                limpiar();
                SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                sa.titulo.setText("¡HECHO!");
                sa.msj.setText("SE HA REGISTRADO UN");
                sa.msj1.setText("NUEVO PRODUCTO");
                sa.setVisible(true);
                producto.Opciones.listartodo();
            }

            //}
        }
    }

    private int validar() {
        int val = 0;
        System.out.println("entro " + val);
        if (TextField_nomPRODUCTO.getText().equals("")) {
            System.out.println("sin nombre " + val);
            Label_nomPRODUCTO.setText("Ingrese nombre");
            Label_nomPRODUCTO.setForeground(Color.red);
            TextField_nomPRODUCTO.requestFocus();
        } else {

            val++;
            System.out.println("bombre " + val);
            if (TextField_desPRODUCTO.getText().equals("")) {
                Label_desPRODUCTO.setText("Ingrese descripción");
                Label_desPRODUCTO.setForeground(Color.red);
                TextField_desPRODUCTO.requestFocus();
            } else {
                val++;
                System.out.println("descrip 2  " + val);
                if (TextField_canPRODUCTO.getText().equals("") || Integer.parseInt(TextField_canPRODUCTO.getText()) < 0) {
                    Label_canPRODUCTO.setText("Ingrese cantidad");
                    Label_canPRODUCTO.setForeground(Color.red);
                    TextField_canPRODUCTO.requestFocus();
                } else {
                    val++;
                    System.out.println("cantidad 3" + val);
                    if (TextField_pcPRODUCTO.getText().equals("")) {
                        Label_pcPRODUCTO.setText("Ingrese precio compra");
                        Label_pcPRODUCTO.setForeground(Color.red);
                        TextField_pcPRODUCTO.requestFocus();
                    } else {
                        val++;
                        System.out.println("precio 4" + val);
                        if (TextField_pvPRODUCTO.getText().equals("")) {
                            Label_pvPRODUCTO.setText("Ingrese precio venta");
                            Label_pvPRODUCTO.setForeground(Color.red);
                            TextField_pvPRODUCTO.requestFocus();
                        } else {
                            val++;
                            System.out.println("pventa  5" + val);
                            if (TextField_CODPRODUCTO.getText().equals("")) {
                                Label_codPRODUCTO.setText("Ingrese código");
                                Label_empresaProveedor.setForeground(Color.red);
                                TextField_CODPRODUCTO.requestFocus();
                            } else {
                                val++;
                                System.out.println("codigo 6" + val);
                                if (TextField_pmPRODUCTO.getText().equals("")) {
                                    Label_pmPRODUCTO.setText("Ingrese precio mayorista");
                                    Label_pmPRODUCTO.setForeground(Color.red);
                                    TextField_pmPRODUCTO.requestFocus();
                                } else {
                                    val++;
                                    System.out.println("pm yo r 7" + val);

                                    nom = TextField_nomPRODUCTO.getText();
                                    cod = TextField_CODPRODUCTO.getText();
                                    des = TextField_desPRODUCTO.getText().toUpperCase();
                                    cantidad = Integer.parseInt(TextField_canPRODUCTO.getText());
                                    pc = Double.parseDouble(TextField_pcPRODUCTO.getText());
                                    pv = Double.parseDouble(TextField_pvPRODUCTO.getText());
                                    pm = Double.parseDouble(TextField_pmPRODUCTO.getText());
                                    idprovedor = extraerID(comboProveedor.getSelectedItem().toString());
                                    tipo = combotipo.getSelectedItem().toString();
//                                    empresa = TextField_empresaProveedor.getText().toUpperCase();
                                    System.out.println("vlor :" + val);

                                }

                            }

                        }

                    }

                }

            }
        }

        return val;
    }

    static PreparedStatement ps;

    public static int extraerID(String empresa) {

        int c = 0;
        String SQL = "SELECT id_proveedor FROM proveedores WHERE empresa_proveedor = '" + empresa + "'";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                c = rs.getInt(1);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Opciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        return c;
    }

    private void limpiar() {
        TextField_nomPRODUCTO.setText("");
        TextField_CODPRODUCTO.setText("");
        TextField_desPRODUCTO.setText("");
        TextField_canPRODUCTO.setText("");
        TextField_pcPRODUCTO.setText("");
        TextField_pvPRODUCTO.setText("");
        TextField_pmPRODUCTO.setText("");
//        TextField_empresaProveedor.setText("");

        Label_nomPRODUCTO.setForeground(new Color(102, 102, 102));
        Label_codPRODUCTO.setForeground(new Color(102, 102, 102));
        Label_desPRODUCTO.setForeground(new Color(102, 102, 102));
        Label_canPRODUCTO.setForeground(new Color(102, 102, 102));
        Label_pcPRODUCTO.setForeground(new Color(102, 102, 102));
        Label_pvPRODUCTO.setForeground(new Color(102, 102, 102));
        Label_pmPRODUCTO.setForeground(new Color(102, 102, 102));
        Label_empresaProveedor.setForeground(new Color(102, 102, 102));

        //Opciones.listar("");
    }
    private void TextField_CODPRODUCTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CODPRODUCTOKeyReleased
        if (TextField_CODPRODUCTO.getText().equals("")) {
            Label_codPRODUCTO.setForeground(new Color(102, 102, 102));
        } else {
            Label_codPRODUCTO.setText("Código");
            Label_codPRODUCTO.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_CODPRODUCTOKeyReleased

    private void TextField_CODPRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CODPRODUCTOKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_CODPRODUCTOKeyTyped

    private void TextField_nomPRODUCTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_nomPRODUCTOKeyReleased
        if (TextField_nomPRODUCTO.getText().equals("")) {
            Label_nomPRODUCTO.setForeground(new Color(102, 102, 102));
        } else {
            Label_nomPRODUCTO.setText("Nombre");
            Label_nomPRODUCTO.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_nomPRODUCTOKeyReleased

    private void TextField_nomPRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_nomPRODUCTOKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_nomPRODUCTOKeyTyped

    private void TextField_desPRODUCTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_desPRODUCTOKeyReleased
        if (TextField_desPRODUCTO.getText().equals("")) {
            Label_desPRODUCTO.setForeground(new Color(102, 102, 102));
        } else {
            Label_desPRODUCTO.setText("Descripción");
            Label_desPRODUCTO.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_desPRODUCTOKeyReleased

    private void TextField_desPRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_desPRODUCTOKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_desPRODUCTOKeyTyped

    private void TextField_pcPRODUCTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_pcPRODUCTOKeyReleased
        if (TextField_pcPRODUCTO.getText().equals("")) {
            Label_pcPRODUCTO.setForeground(new Color(102, 102, 102));
        } else {
            Label_pcPRODUCTO.setText("Precio compra");
            Label_pcPRODUCTO.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_pcPRODUCTOKeyReleased

    private void TextField_pcPRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_pcPRODUCTOKeyTyped
        evento.numberDecimalkeyPress(evt, TextField_pcPRODUCTO);
    }//GEN-LAST:event_TextField_pcPRODUCTOKeyTyped

    private void TextField_pvPRODUCTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_pvPRODUCTOKeyReleased
        if (TextField_pvPRODUCTO.getText().equals("")) {
            Label_pvPRODUCTO.setForeground(new Color(102, 102, 102));
        } else {
            Label_pvPRODUCTO.setText("Precio venta");
            Label_pvPRODUCTO.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_pvPRODUCTOKeyReleased

    private void TextField_pvPRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_pvPRODUCTOKeyTyped
        evento.numberDecimalkeyPress(evt, TextField_pvPRODUCTO);
    }//GEN-LAST:event_TextField_pvPRODUCTOKeyTyped

    private void TextField_pmPRODUCTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_pmPRODUCTOKeyReleased
        if (TextField_pmPRODUCTO.getText().equals("")) {
            Label_pmPRODUCTO.setForeground(new Color(102, 102, 102));
        } else {
            Label_pmPRODUCTO.setText("Precio mayorista");
            Label_pmPRODUCTO.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_pmPRODUCTOKeyReleased

    private void TextField_pmPRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_pmPRODUCTOKeyTyped
        evento.numberDecimalkeyPress(evt, TextField_pmPRODUCTO);
    }//GEN-LAST:event_TextField_pmPRODUCTOKeyTyped

    private void TextField_canPRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_canPRODUCTOKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_canPRODUCTOKeyTyped

    private void TextField_canPRODUCTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_canPRODUCTOKeyReleased
        if (TextField_canPRODUCTO.getText().equals("")) {
            Label_canPRODUCTO.setForeground(new Color(102, 102, 102));
        } else {
            Label_canPRODUCTO.setText("Cantidad");
            Label_canPRODUCTO.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_canPRODUCTOKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalProductoMInventario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalProductoMInventario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalProductoMInventario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalProductoMInventario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModalProductoMInventario dialog = new ModalProductoMInventario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Guardar;
    private javax.swing.JButton Button_Limpiar;
    private javax.swing.JLabel Label_canPRODUCTO;
    private javax.swing.JLabel Label_codPRODUCTO;
    private javax.swing.JLabel Label_desPRODUCTO;
    private javax.swing.JLabel Label_empresaProveedor;
    private javax.swing.JLabel Label_nomPRODUCTO;
    private javax.swing.JLabel Label_pcPRODUCTO;
    private javax.swing.JLabel Label_pmPRODUCTO;
    private javax.swing.JLabel Label_productoTipo;
    private javax.swing.JLabel Label_pvPRODUCTO;
    public static javax.swing.JTextField TextField_CODPRODUCTO;
    public static javax.swing.JTextField TextField_canPRODUCTO;
    public static javax.swing.JTextField TextField_desPRODUCTO;
    public static javax.swing.JTextField TextField_nomPRODUCTO;
    public static javax.swing.JTextField TextField_pcPRODUCTO;
    public static javax.swing.JTextField TextField_pmPRODUCTO;
    public static javax.swing.JTextField TextField_pvPRODUCTO;
    private principal.MaterialButton cerrar;
    private javax.swing.JComboBox<String> comboProveedor;
    private javax.swing.JComboBox<String> combotipo;
    public static javax.swing.JLabel idmodal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private org.edisoncor.gui.panel.Panel panel1;
    public static javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

    private void Cerrar() {
        this.dispose();
        timer = null;
        task = null;
    }

    private void Trasparencia(float trasp) {
        AWTUtilities.setOpacity(this, trasp);
    }

    private void Ubicar(int y) {
        this.setLocation(603, y - 200);
    }
}
