/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import paneles.CambiaPanel;
import ventas.ListaVentas;
import ventas.Ventas;



/**
 *
 * @author RojeruSan
 */
public class Principal extends javax.swing.JFrame {

    int x, y;
    /**
     * Creates new form Principal
     */
    int poss = 1;
    int anterior;
    public static ListaVentas lista = null;
    public static Ventas ventas = null;
    boolean b = true;
    private boolean minimiza = false;
    public static boolean cerra = false;

    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.btn_inicio.setBackground(new Color(65, 132, 219));
        poss = 1;
        anterior = poss;

        //new CambiaPanel(pnlPrincipal, new paneles.PnlCliente());
    }

//    public static boolean estacerrado(Object obj) {
//        //JInternalFrame[] activos = escritorio.getAllFrames();
//        boolean cerrado = true;
//        int i = 0;
//        while (i < activos.length && cerrado) {
//            if (activos[i] == obj) {
//                cerrado = false;
//                cerra = false;
//            }
//            i++;
//        }
//        return cerrado;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_productos = new rojerusan.RSButtonIconD();
        btn_ventas = new rojerusan.RSButtonIconD();
        btn_facturas = new rojerusan.RSButtonIconD();
        btn_inventarios = new rojerusan.RSButtonIconD();
        btn_empleados = new rojerusan.RSButtonIconD();
        btn_proveedores = new rojerusan.RSButtonIconD();
        btn_inicio = new rojerusan.RSButtonIconD();
        btn_caja = new rojerusan.RSButtonIconD();
        btn_admin = new rojerusan.RSButtonIconD();
        btn_clientes = new rojerusan.RSButtonIconD();
        btn_usuarios = new rojerusan.RSButtonIconD();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(106, 111, 124));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        pnlMenu.setBackground(new java.awt.Color(80, 80, 97));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(80, 80, 97));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menú");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        pnlMenu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 50));

        btn_productos.setBackground(new java.awt.Color(80, 80, 97));
        btn_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/business_inventory_maintenance_product_box_boxes_2326.png"))); // NOI18N
        btn_productos.setText("Productos");
        btn_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productosActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_productos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 180, 50));

        btn_ventas.setBackground(new java.awt.Color(80, 80, 97));
        btn_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-buying-96.png"))); // NOI18N
        btn_ventas.setText("Ventas");
        btn_ventas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ventasActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 180, 50));

        btn_facturas.setBackground(new java.awt.Color(80, 80, 97));
        btn_facturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/business_salesreport_salesreport_negocio_2353.png"))); // NOI18N
        btn_facturas.setText("Facturas");
        btn_facturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facturasActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_facturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 180, 50));

        btn_inventarios.setBackground(new java.awt.Color(80, 80, 97));
        btn_inventarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shoppaymentorderbuy-08_icon-icons.com_73885.png"))); // NOI18N
        btn_inventarios.setText("Inventarios");
        btn_inventarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inventariosActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_inventarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 180, 50));

        btn_empleados.setBackground(new java.awt.Color(80, 80, 97));
        btn_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/contactlist_theuser_802.png"))); // NOI18N
        btn_empleados.setText("Empleados");
        btn_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empleadosActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_empleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 180, 50));

        btn_proveedores.setBackground(new java.awt.Color(80, 80, 97));
        btn_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-management-96.png"))); // NOI18N
        btn_proveedores.setText("Proveedores");
        btn_proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proveedoresActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_proveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 180, 50));

        btn_inicio.setBackground(new java.awt.Color(80, 80, 97));
        btn_inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Home.png"))); // NOI18N
        btn_inicio.setText("Inicio");
        btn_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 180, 50));

        btn_caja.setBackground(new java.awt.Color(80, 80, 97));
        btn_caja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cashier_icon-icons.com_53629.png"))); // NOI18N
        btn_caja.setText("Caja");
        btn_caja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cajaActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 180, 50));

        btn_admin.setBackground(new java.awt.Color(80, 80, 97));
        btn_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        btn_admin.setText("Usuarios");
        btn_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adminActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 180, 50));

        btn_clientes.setBackground(new java.awt.Color(80, 80, 97));
        btn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bootloader_users_person_people_6080.png"))); // NOI18N
        btn_clientes.setText("Clientes");
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 180, 50));

        btn_usuarios.setBackground(new java.awt.Color(80, 80, 97));
        btn_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Apps_43866.png"))); // NOI18N
        btn_usuarios.setText("Compras");
        btn_usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_usuariosActionPerformed(evt);
            }
        });
        pnlMenu.add(btn_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 180, 50));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 8.3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        jPanel1.add(pnlMenu, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(45, 45, 45));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tunga", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Librería y papelería");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(762, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.weightx = 0.2;
        jPanel1.add(jPanel2, gridBagConstraints);

        pnlCentro.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(106, 111, 124));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(null);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new javax.swing.BoxLayout(pnlPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(pnlPrincipal);

        javax.swing.GroupLayout pnlCentroLayout = new javax.swing.GroupLayout(pnlCentro);
        pnlCentro.setLayout(pnlCentroLayout);
        pnlCentroLayout.setHorizontalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        pnlCentroLayout.setVerticalGroup(
            pnlCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCentroLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        jPanel1.add(pnlCentro, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pintar(int poss) {
        switch (poss) {
            case 1:
                this.btn_inicio.setBackground(new Color(65, 132, 219));
                break;
            case 2:
                this.btn_admin.setBackground(new Color(65, 132, 219));
                break;
            case 3:
                this.btn_caja.setBackground(new Color(65, 132, 219));
                break;
            case 4:
                this.btn_clientes.setBackground(new Color(65, 132, 219));
                break;
            case 5:
                this.btn_empleados.setBackground(new Color(65, 132, 219));
                break;
            case 6:
                this.btn_proveedores.setBackground(new Color(65, 132, 219));
                break;
            case 7:
                this.btn_facturas.setBackground(new Color(65, 132, 219));
                break;
            case 8:
                this.btn_inventarios.setBackground(new Color(65, 132, 219));
                break;
            case 9:
                this.btn_productos.setBackground(new Color(65, 132, 219));
                break;
            case 10:
                this.btn_usuarios.setBackground(new Color(65, 132, 219));
                break;
            case 11:
                this.btn_ventas.setBackground(new Color(65, 132, 219));
                break;
        }
    }

    private void despintar(int anterior) {
        switch (anterior) {
            case 1:
                this.btn_inicio.setBackground(new Color(80, 80, 97));
                break;
            case 2:
                this.btn_admin.setBackground(new Color(80, 80, 97));
                break;
            case 3:
                this.btn_caja.setBackground(new Color(80, 80, 97));
                break;
            case 4:
                this.btn_clientes.setBackground(new Color(80, 80, 97));
                break;
            case 5:
                this.btn_empleados.setBackground(new Color(80, 80, 97));
                break;
            case 6:
                this.btn_proveedores.setBackground(new Color(80, 80, 97));
                break;
            case 7:
                this.btn_facturas.setBackground(new Color(80, 80, 97));
                break;
            case 8:
                this.btn_inventarios.setBackground(new Color(80, 80, 97));
                break;
            case 9:
                this.btn_productos.setBackground(new Color(80, 80, 97));
                break;
            case 10:
                this.btn_usuarios.setBackground(new Color(80, 80, 97));
                break;
            case 11:
                this.btn_ventas.setBackground(new Color(80, 80, 97));
                break;
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int posicion = pnlMenu.getX();
        if (posicion > -1) {
            Animacion.Animacion.mover_izquierda(0, -264, 2, 2, pnlMenu);
        } else {
            Animacion.Animacion.mover_derecha(-264, 0, 2, 2, pnlMenu);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btn_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productosActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.PnlProductos());
        this.poss = 9;
        pintar(this.poss);
        if (this.poss != this.anterior) {
            despintar(this.anterior);
            this.anterior = this.poss;
        }
    }//GEN-LAST:event_btn_productosActionPerformed

    private void btn_ventasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ventasActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.PnlVentas());
        this.poss = 11;
        pintar(this.poss);
        if (this.poss != this.anterior) {
            despintar(this.anterior);
            this.anterior = this.poss;
        }
    }//GEN-LAST:event_btn_ventasActionPerformed

    private void btn_facturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facturasActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.PnlGestionFacturas());
        this.poss = 7;
        pintar(this.poss);
        if (this.poss != this.anterior) {
            despintar(this.anterior);
            this.anterior = this.poss;
        }
    }//GEN-LAST:event_btn_facturasActionPerformed

    private void btn_inventariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventariosActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.PnlInventario());
        this.poss = 8;
        pintar(this.poss);
        if (this.poss != this.anterior) {
            despintar(this.anterior);
            this.anterior = this.poss;
        }
    }//GEN-LAST:event_btn_inventariosActionPerformed

    private void btn_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empleadosActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.PnlEmpleados());
        this.poss = 5;
        pintar(this.poss);
        if (this.poss != this.anterior) {
            despintar(this.anterior);
            this.anterior = this.poss;
        }
    }//GEN-LAST:event_btn_empleadosActionPerformed

    private void btn_proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proveedoresActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.PnlProveedor());
        this.poss = 6;
        pintar(this.poss);
        if (this.poss != this.anterior) {
            despintar(this.anterior);
            this.anterior = this.poss;
        }
    }//GEN-LAST:event_btn_proveedoresActionPerformed

    private void btn_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.PnlLocal());
        this.poss = 1;
        pintar(this.poss);
        if (this.poss != this.anterior) {
            despintar(this.anterior);
            this.anterior = this.poss;
        }
    }//GEN-LAST:event_btn_inicioActionPerformed

    private void btn_cajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cajaActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.PnlGestionVentas());
        this.poss = 3;
        pintar(this.poss);
        if (this.poss != this.anterior) {
            despintar(this.anterior);
            this.anterior = this.poss;
        }

    }//GEN-LAST:event_btn_cajaActionPerformed

    private void btn_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adminActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.pnlAdministradores());
        this.poss = 2;
        pintar(this.poss);
        if (this.poss != this.anterior) {
            despintar(this.anterior);
            this.anterior = this.poss;
        }

    }//GEN-LAST:event_btn_adminActionPerformed

    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.PnlCliente());
        this.poss = 4;
        pintar(this.poss);
        if (this.poss != this.anterior) {
            despintar(this.anterior);
            this.anterior = this.poss;
        }
    }//GEN-LAST:event_btn_clientesActionPerformed

    private void btn_usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_usuariosActionPerformed
        new CambiaPanel(pnlPrincipal, new paneles.PnlCompras());
        this.poss = 10;
        pintar(this.poss);
        if (this.poss != this.anterior) {
            despintar(this.anterior);
            this.anterior = this.poss;
        }
    }//GEN-LAST:event_btn_usuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new Principal().setVisible(true);
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonIconD btn_admin;
    private rojerusan.RSButtonIconD btn_caja;
    private rojerusan.RSButtonIconD btn_clientes;
    private rojerusan.RSButtonIconD btn_empleados;
    private rojerusan.RSButtonIconD btn_facturas;
    private rojerusan.RSButtonIconD btn_inicio;
    private rojerusan.RSButtonIconD btn_inventarios;
    private rojerusan.RSButtonIconD btn_productos;
    private rojerusan.RSButtonIconD btn_proveedores;
    private rojerusan.RSButtonIconD btn_usuarios;
    private rojerusan.RSButtonIconD btn_ventas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
