package models;
// Generated 02-nov-2018 18:26:55 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ReportesCliente generated by hbm2java
 */
public class ReportesCliente  implements java.io.Serializable {


//     private Integer idRegistro;
//     privateClientes clientes;
//     private double saldoActual;
//     private Date fechaActual;
//     private double ultimoPago;
//     private Date fechaPago;
//     private String idCliente;
//
//    public ReportesCliente() {
//    }
//
//    public ReportesClienteClientes clientes, double saldoActual, Date fechaActual, double ultimoPago, Date fechaPago, String idCliente) {
//       this.clientes = clientes;
//       this.saldoActual = saldoActual;
//       this.fechaActual = fechaActual;
//       this.ultimoPago = ultimoPago;
//       this.fechaPago = fechaPago;
//       this.idCliente = idCliente;
//    }
//   
//    public Integer getIdRegistro() {
//        return this.idRegistro;
//    }
//    
//    public void setIdRegistro(Integer idRegistro) {
//        this.idRegistro = idRegistro;
//    }
//    publicClientes getClientes() {
//        return this.clientes;
//    }
//    
//    public void setClientesClientes clientes) {
//        this.clientes = clientes;
//    }
//    public double getSaldoActual() {
//        return this.saldoActual;
//    }
//    
//    public void setSaldoActual(double saldoActual) {
//        this.saldoActual = saldoActual;
//    }
//    public Date getFechaActual() {
//        return this.fechaActual;
//    }
//    
//    public void setFechaActual(Date fechaActual) {
//        this.fechaActual = fechaActual;
//    }
//    public double getUltimoPago() {
//        return this.ultimoPago;
//    }
//    
//    public void setUltimoPago(double ultimoPago) {
//        this.ultimoPago = ultimoPago;
//    }
//    public Date getFechaPago() {
//        return this.fechaPago;
//    }
//    
//    public void setFechaPago(Date fechaPago) {
//        this.fechaPago = fechaPago;
//    }
//    public String getIdCliente() {
//        return this.idCliente;
//    }
//    
//    public void setIdCliente(String idCliente) {
//        this.idCliente = idCliente;
//    }




}


