/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import ModelClass.TextFieldEven;
import controllers.AdministradorJpaController;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import models.Administrador;


/**
 *
 * @author RojeruSan
 */
public class pnlAdministradores extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    private String acction = "insert", Id = "", dia, mes, anio, funcionCatDpt, idCat, dpt;
    private int pageSize, tab, maxReg, pageCount, currentPage, numReg;
    private int startRec, endRec;

    private String id = "";
    private String nombre = "";
    private String apellido = "";
    private String direccion = "";
    private String telefono = "";

    TextFieldEven evento = new TextFieldEven();

    DefaultTableModel modelo2;
    AdministradorJpaController adminController = new AdministradorJpaController();
    int ids;
    private TableRowSorter trsfiltro;
    
    

    public pnlAdministradores() {
        initComponents();
        
        LoadAdmin();
        this.Button_GuardarCliente.setEnabled(true);
        this.Button_Editar.setEnabled(false);
    }

    public void filtro() {
        trsfiltro.setRowFilter(RowFilter.regexFilter(TextField_BuscarCliente.getText(), 2));
    }

    private void LoadAdmin() {
        try {
            Table_admin.removeAll();
            String[] titulos = {"id", "Ci", "Nombres", "Apellidos", "Dirección", "Teléfono"};
            String[] registro = new String[6];
            Object o[] = null;
            List<Administrador> listAdmin = adminController.findAdministradorEntities();
            modelo2 = new DefaultTableModel(null, titulos);

            for (int i = 0; i < listAdmin.size(); i++) {
//                modelo2.addRow(o);
                registro[0] = String.valueOf(listAdmin.get(i).getId());
                registro[1] = listAdmin.get(i).getCi();
                registro[2] = listAdmin.get(i).getNombres();
                registro[3] = listAdmin.get(i).getApellidos();
                registro[4] = listAdmin.get(i).getDireccion();
                registro[5] = listAdmin.get(i).getTelefono();
                modelo2.addRow(registro);
            }
            Table_admin.setModel(modelo2);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error2");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Button_GuardarCliente = new javax.swing.JButton();
        Label_IdCliente = new javax.swing.JLabel();
        TextField_idAdmin = new javax.swing.JTextField();
        Label_NombreCliente = new javax.swing.JLabel();
        TextField_NombreAdmin = new javax.swing.JTextField();
        Label_ApellidoCliente = new javax.swing.JLabel();
        TextField_ApellidioAdmin = new javax.swing.JTextField();
        Label_DireccionCliente = new javax.swing.JLabel();
        TextField_DireccioAdmin = new javax.swing.JTextField();
        Label_TelefonoCliente = new javax.swing.JLabel();
        TextField_TelefonoAdmin = new javax.swing.JTextField();
        Button_Editar = new javax.swing.JButton();
        Button_Limpiar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextField_BuscarCliente = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_admin =   Table_admin = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        Button_Cancelar = new javax.swing.JButton();
        Button_Factura = new javax.swing.JButton();
        Button_EliminarCLT = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(80, 80, 97));
        jLabel2.setText("Datos del Usuario");
        jLabel2.setToolTipText("");

        Button_GuardarCliente.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        Button_GuardarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Agregar.png"))); // NOI18N
        Button_GuardarCliente.setText("Guardar");
        Button_GuardarCliente.setBorder(null);
        Button_GuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GuardarClienteActionPerformed(evt);
            }
        });

        Label_IdCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_IdCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_IdCliente.setText("CI");
        Label_IdCliente.setToolTipText("");

        TextField_idAdmin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_idAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_idAdminKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_idAdminKeyTyped(evt);
            }
        });

        Label_NombreCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_NombreCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_NombreCliente.setText("Nombre completo");
        Label_NombreCliente.setToolTipText("");

        TextField_NombreAdmin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_NombreAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_NombreAdminKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_NombreAdminKeyTyped(evt);
            }
        });

        Label_ApellidoCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_ApellidoCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_ApellidoCliente.setText("Apellido");

        TextField_ApellidioAdmin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_ApellidioAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_ApellidioAdminKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_ApellidioAdminKeyTyped(evt);
            }
        });

        Label_DireccionCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_DireccionCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_DireccionCliente.setText("Dirección");
        Label_DireccionCliente.setToolTipText("");

        TextField_DireccioAdmin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_DireccioAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_DireccioAdminKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_DireccioAdminKeyTyped(evt);
            }
        });

        Label_TelefonoCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_TelefonoCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_TelefonoCliente.setText("Teléfono");

        TextField_TelefonoAdmin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_TelefonoAdmin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_TelefonoAdminKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_TelefonoAdminKeyTyped(evt);
            }
        });

        Button_Editar.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        Button_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar.png"))); // NOI18N
        Button_Editar.setText("Editar");
        Button_Editar.setBorder(null);
        Button_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EditarActionPerformed(evt);
            }
        });

        Button_Limpiar.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        Button_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar.png"))); // NOI18N
        Button_Limpiar.setText("Limpiar");
        Button_Limpiar.setBorder(null);
        Button_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextField_NombreAdmin)
                            .addComponent(TextField_ApellidioAdmin)
                            .addComponent(TextField_DireccioAdmin)
                            .addComponent(TextField_TelefonoAdmin)
                            .addComponent(TextField_idAdmin)
                            .addComponent(jLabel2)
                            .addComponent(Label_IdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_NombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(Label_ApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_DireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_TelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Button_GuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_IdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_idAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(Label_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_NombreAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_ApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_ApellidioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_DireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_DireccioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_TelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_TelefonoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_GuardarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 97));
        jLabel1.setText("Usuarios");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(80, 80, 97));
        jLabel5.setText("Buscar");

        TextField_BuscarCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_BuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_BuscarClienteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(184, 184, 184)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(TextField_BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TextField_BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Table_admin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Table_admin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table_admin.setRowHeight(20);
        Table_admin.setSelectionBackground(new java.awt.Color(102, 204, 255));
        jScrollPane2.setViewportView(Table_admin);

        Button_Cancelar.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        Button_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar.png"))); // NOI18N
        Button_Cancelar.setText("Cancelar");
        Button_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelarActionPerformed(evt);
            }
        });

        Button_Factura.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        Button_Factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Left.png"))); // NOI18N
        Button_Factura.setText("Seleccionar");
        Button_Factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_FacturaActionPerformed(evt);
            }
        });

        Button_EliminarCLT.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        Button_EliminarCLT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png"))); // NOI18N
        Button_EliminarCLT.setText("Eliminar");
        Button_EliminarCLT.setBorder(null);
        Button_EliminarCLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EliminarCLTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2)
                .addGap(10, 10, 10))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Factura)
                .addGap(10, 10, 10)
                .addComponent(Button_EliminarCLT, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Factura, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_EliminarCLT, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_GuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GuardarClienteActionPerformed
        if (validar() == 5) {
            saveAdministrador();
            limpiar();
            this.id = "";
            this.nombre = "";
            this.apellido = "";
            this.direccion = "";
            this.telefono = "";
            JOptionPane.showMessageDialog(null, "Guardado exitosamente");
        } else {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        }

    }//GEN-LAST:event_Button_GuardarClienteActionPerformed

    private void Button_EliminarCLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EliminarCLTActionPerformed
        try {
            int id_ad = Integer.parseInt((String) Table_admin.getValueAt(Table_admin.getSelectedRow(), 0));
            
            adminController.destroy(id_ad);
         
            LoadAdmin();
            JOptionPane.showMessageDialog(null, "Eliminado exitosamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Button_EliminarCLTActionPerformed

    private void TextField_idAdminKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_idAdminKeyReleased
        if (TextField_idAdmin.getText().equals("")) {
            Label_IdCliente.setForeground(new Color(102, 102, 102));
        } else {
            Label_IdCliente.setText("ID");
            Label_IdCliente.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_idAdminKeyReleased

    private void TextField_idAdminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_idAdminKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_idAdminKeyTyped

    private void TextField_NombreAdminKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_NombreAdminKeyReleased
        if (TextField_NombreAdmin.getText().equals("")) {
            Label_NombreCliente.setForeground(new Color(102, 102, 102));
        } else {
            Label_NombreCliente.setText("Nombre completo");
            Label_NombreCliente.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_NombreAdminKeyReleased

    private void TextField_NombreAdminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_NombreAdminKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_NombreAdminKeyTyped

    private void TextField_ApellidioAdminKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ApellidioAdminKeyReleased
        if (TextField_ApellidioAdmin.getText().equals("")) {
            Label_ApellidoCliente.setForeground(new Color(102, 102, 102));
        } else {
            Label_ApellidoCliente.setText("Apellido");
            Label_ApellidoCliente.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_ApellidioAdminKeyReleased

    private void TextField_ApellidioAdminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ApellidioAdminKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_ApellidioAdminKeyTyped

    private void TextField_DireccioAdminKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_DireccioAdminKeyReleased
        if (TextField_DireccioAdmin.getText().equals("")) {
            Label_DireccionCliente.setForeground(new Color(102, 102, 102));
        } else {
            Label_DireccionCliente.setText("Dirección");
            Label_DireccionCliente.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_DireccioAdminKeyReleased

    private void TextField_DireccioAdminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_DireccioAdminKeyTyped

    }//GEN-LAST:event_TextField_DireccioAdminKeyTyped

    private void TextField_TelefonoAdminKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_TelefonoAdminKeyReleased
        if (TextField_TelefonoAdmin.getText().equals("")) {
            Label_TelefonoCliente.setForeground(new Color(102, 102, 102));
        } else {
            Label_TelefonoCliente.setText("Teléfono");
            Label_TelefonoCliente.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_TelefonoAdminKeyReleased

    private void TextField_TelefonoAdminKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_TelefonoAdminKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_TelefonoAdminKeyTyped

    private void Button_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EditarActionPerformed
        try {
            if (validar() == 5) {
                
                Administrador admin = adminController.findAdministrador(ids);
                admin.setCi(id);

                admin.setNombres(nombre);

                admin.setApellidos(apellido);

                admin.setDireccion(direccion);

                admin.setTelefono(telefono);
                adminController.edit(admin);

                JOptionPane.showMessageDialog(null, "Actualizado exitosamente");
                limpiar();
                this.id = "";
                this.nombre = "";
                this.apellido = "";
                this.direccion = "";
                this.telefono = "";
                LoadAdmin();
                this.Button_GuardarCliente.setEnabled(true);
                this.Button_Editar.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Complete todos los campos");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_Button_EditarActionPerformed

    private void Button_FacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_FacturaActionPerformed
        this.Button_GuardarCliente.setEnabled(false);
        this.Button_Editar.setEnabled(true);
        this.ids = Integer.parseInt((String) Table_admin.getValueAt(Table_admin.getSelectedRow(), 0));
        TextField_idAdmin.setText(Table_admin.getValueAt(Table_admin.getSelectedRow(), 1).toString());
        TextField_NombreAdmin.setText(Table_admin.getValueAt(Table_admin.getSelectedRow(), 2).toString());
        TextField_ApellidioAdmin.setText(Table_admin.getValueAt(Table_admin.getSelectedRow(), 3).toString());
        TextField_DireccioAdmin.setText(Table_admin.getValueAt(Table_admin.getSelectedRow(), 4).toString());
        TextField_TelefonoAdmin.setText(Table_admin.getValueAt(Table_admin.getSelectedRow(), 5).toString());
    }//GEN-LAST:event_Button_FacturaActionPerformed

    private void Button_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_Button_LimpiarActionPerformed

    private void Button_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelarActionPerformed
        limpiar();
        this.Button_GuardarCliente.setEnabled(true);
        this.Button_Editar.setEnabled(false);
    }//GEN-LAST:event_Button_CancelarActionPerformed

    private void TextField_BuscarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_BuscarClienteKeyTyped
        TextField_BuscarCliente.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (TextField_BuscarCliente.getText().toUpperCase());
                TextField_BuscarCliente.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsfiltro = new TableRowSorter(Table_admin.getModel());
        Table_admin.setRowSorter(trsfiltro);
    }//GEN-LAST:event_TextField_BuscarClienteKeyTyped

    private void limpiar() {
        TextField_idAdmin.setText("");
        TextField_NombreAdmin.setText("");
        TextField_ApellidioAdmin.setText("");
        TextField_DireccioAdmin.setText("");
        TextField_TelefonoAdmin.setText("");

        Label_IdCliente.setForeground(new Color(102, 102, 102));
        Label_NombreCliente.setForeground(new Color(102, 102, 102));
        Label_ApellidoCliente.setForeground(new Color(102, 102, 102));
        Label_DireccionCliente.setForeground(new Color(102, 102, 102));
        Label_TelefonoCliente.setForeground(new Color(102, 102, 102));

    }

    private void saveAdministrador() {
        Administrador admin = new Administrador();

        admin.setCi(id);

        admin.setNombres(nombre);

        admin.setApellidos(apellido);

        admin.setDireccion(direccion);

        admin.setTelefono(telefono);

        adminController.create(admin);
        LoadAdmin();
    }

    private int validar() {
        int val = 0;
        if (TextField_idAdmin.getText().equals("")) {
            Label_IdCliente.setText("Ingrese la ID");
            Label_IdCliente.setForeground(Color.red);
            TextField_idAdmin.requestFocus();
        } else {
            val++;
            if (TextField_NombreAdmin.getText().equals("")) {
                Label_NombreCliente.setText("Ingrese el nombre");
                Label_NombreCliente.setForeground(Color.red);
                TextField_NombreAdmin.requestFocus();
            } else {
                val++;
                if (TextField_ApellidioAdmin.getText().equals("")) {
                    Label_ApellidoCliente.setText("Ingrese el apellido");
                    Label_ApellidoCliente.setForeground(Color.red);
                    TextField_ApellidioAdmin.requestFocus();
                } else {
                    val++;
                    if (TextField_DireccioAdmin.getText().equals("")) {
                        Label_DireccionCliente.setText("Ingrese la dirección");
                        Label_DireccionCliente.setForeground(Color.red);
                        TextField_DireccioAdmin.requestFocus();
                    } else {
                        val++;
                        if (TextField_TelefonoAdmin.getText().equals("")) {
                            Label_TelefonoCliente.setText("Ingrese el teléfono");
                            Label_TelefonoCliente.setForeground(Color.red);
                            TextField_TelefonoAdmin.requestFocus();
                        } else {
                            val++;
                            if (acction.equals("insert")) {
                                id = TextField_idAdmin.getText();
                                nombre = TextField_NombreAdmin.getText().toUpperCase();
                                apellido = TextField_ApellidioAdmin.getText().toUpperCase();
                                direccion = TextField_DireccioAdmin.getText().toUpperCase();
                                telefono = TextField_TelefonoAdmin.getText();
                            }

                        }

                    }

                }

            }
        }
        return val;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cancelar;
    private javax.swing.JButton Button_Editar;
    private javax.swing.JButton Button_EliminarCLT;
    private javax.swing.JButton Button_Factura;
    private javax.swing.JButton Button_GuardarCliente;
    private javax.swing.JButton Button_Limpiar;
    private javax.swing.JLabel Label_ApellidoCliente;
    private javax.swing.JLabel Label_DireccionCliente;
    private javax.swing.JLabel Label_IdCliente;
    private javax.swing.JLabel Label_NombreCliente;
    private javax.swing.JLabel Label_TelefonoCliente;
    private javax.swing.JTable Table_admin;
    private javax.swing.JTextField TextField_ApellidioAdmin;
    private javax.swing.JTextField TextField_BuscarCliente;
    private javax.swing.JTextField TextField_DireccioAdmin;
    private javax.swing.JTextField TextField_NombreAdmin;
    private javax.swing.JTextField TextField_TelefonoAdmin;
    private javax.swing.JTextField TextField_idAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
