/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import ModelClass.TextFieldEven;
import alertas.principal.ErrorAlert;
import alertas.principal.SuccessAlert;
import clientes.Sentencias;
import conexion.ConexionBD;
import controllers.ClienteJpaController;
import controllers.Controlador;
import controllers.ControllerCliente;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import models.Cliente;
import models.Local;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author RojeruSan
 */
public class PnlCliente extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    private String acction = "insert";

    TextFieldEven evento = new TextFieldEven();

    private String ci = "";
    private String ruc = "";
    private String nombre = "";
    private String apellido = "";
    private String direccion = "";
    private String telefono = "";
    private String email = "";
    private float descuento = 0;

    DefaultTableModel modelo2;
    int ids;
    private TableRowSorter trsfiltro;

    public PnlCliente() {
        initComponents();
        clientes.Opciones.listar("");
        this.Button_Guardar.setEnabled(true);
        this.Button_Editar.setEnabled(false);
    }

    public void filtro() {
        trsfiltro.setRowFilter(RowFilter.regexFilter(TextField_BuscarCliente.getText(), 4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Button_Limpiar = new javax.swing.JButton();
        Button_Guardar = new javax.swing.JButton();
        Label_rucCliente = new javax.swing.JLabel();
        TextField_rucCliente = new javax.swing.JTextField();
        Label_ciCliente = new javax.swing.JLabel();
        TextField_CiCliente = new javax.swing.JTextField();
        Label_NombreCliente = new javax.swing.JLabel();
        TextField_NombreCliente = new javax.swing.JTextField();
        Label_ApellidoCliente = new javax.swing.JLabel();
        TextField_ApellidioCliente = new javax.swing.JTextField();
        Label_DireccionCliente = new javax.swing.JLabel();
        TextField_DireccioCliente = new javax.swing.JTextField();
        Label_TelefonoCliente = new javax.swing.JLabel();
        TextField_TelefonoCliente = new javax.swing.JTextField();
        Button_Editar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextField_BuscarCliente = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Clientes =   Table_Clientes = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        Button_Seleccionar = new javax.swing.JButton();
        Button_Eliminar = new javax.swing.JButton();
        Button_Cancelar = new javax.swing.JButton();
        Button_imprimir = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(80, 80, 97));
        jLabel2.setText("Datos del cliente");
        jLabel2.setToolTipText("");

        Button_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png"))); // NOI18N
        Button_Limpiar.setText("Limpiar");
        Button_Limpiar.setBorder(null);
        Button_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LimpiarActionPerformed(evt);
            }
        });

        Button_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Agregar.png"))); // NOI18N
        Button_Guardar.setText("Guardar");
        Button_Guardar.setBorder(null);
        Button_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GuardarActionPerformed(evt);
            }
        });

        Label_rucCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_rucCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_rucCliente.setText("Ruc");
        Label_rucCliente.setToolTipText("");

        TextField_rucCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_rucClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_rucClienteKeyTyped(evt);
            }
        });

        Label_ciCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_ciCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_ciCliente.setText("CI");
        Label_ciCliente.setToolTipText("");

        TextField_CiCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_CiClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_CiClienteKeyTyped(evt);
            }
        });

        Label_NombreCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_NombreCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_NombreCliente.setText("Nombre completo");
        Label_NombreCliente.setToolTipText("");

        TextField_NombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_NombreClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_NombreClienteKeyTyped(evt);
            }
        });

        Label_ApellidoCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_ApellidoCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_ApellidoCliente.setText("Apellido");

        TextField_ApellidioCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_ApellidioClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_ApellidioClienteKeyTyped(evt);
            }
        });

        Label_DireccionCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_DireccionCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_DireccionCliente.setText("Dirección");
        Label_DireccionCliente.setToolTipText("");

        TextField_DireccioCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_DireccioClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_DireccioClienteKeyTyped(evt);
            }
        });

        Label_TelefonoCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_TelefonoCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_TelefonoCliente.setText("Teléfono");

        TextField_TelefonoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_TelefonoClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_TelefonoClienteKeyTyped(evt);
            }
        });

        Button_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar.png"))); // NOI18N
        Button_Editar.setText("Editar");
        Button_Editar.setBorder(null);
        Button_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Button_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextField_NombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(TextField_ApellidioCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(TextField_DireccioCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(TextField_TelefonoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(TextField_CiCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(TextField_rucCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(Label_rucCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_ciCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_NombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_ApellidoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_DireccionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_TelefonoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_rucCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_rucCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Label_ciCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_CiCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_NombreCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_NombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_ApellidoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_ApellidioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Label_DireccionCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_DireccioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_TelefonoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_TelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 97));
        jLabel1.setText("Clientes");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(80, 80, 97));
        jLabel5.setText("Buscar");

        TextField_BuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_BuscarClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_BuscarClienteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(156, 156, 156)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(TextField_BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(TextField_BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Table_Clientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Table_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CI", "NOMBRE", "APELLIDO", "DIRECCIÓN", "TELÉFONO", "RUC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Clientes.setRowHeight(20);
        Table_Clientes.setSelectionBackground(new java.awt.Color(102, 204, 255));
        jScrollPane2.setViewportView(Table_Clientes);
        if (Table_Clientes.getColumnModel().getColumnCount() > 0) {
            Table_Clientes.getColumnModel().getColumn(0).setPreferredWidth(10);
            Table_Clientes.getColumnModel().getColumn(1).setResizable(false);
            Table_Clientes.getColumnModel().getColumn(2).setResizable(false);
            Table_Clientes.getColumnModel().getColumn(3).setResizable(false);
            Table_Clientes.getColumnModel().getColumn(4).setResizable(false);
        }

        Button_Seleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Left.png"))); // NOI18N
        Button_Seleccionar.setText("Seleccionar");
        Button_Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SeleccionarActionPerformed(evt);
            }
        });

        Button_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png"))); // NOI18N
        Button_Eliminar.setText("Eliminar");
        Button_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EliminarActionPerformed(evt);
            }
        });

        Button_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar.png"))); // NOI18N
        Button_Cancelar.setText("Cancelar");
        Button_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelarActionPerformed(evt);
            }
        });

        Button_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Imprimir.png"))); // NOI18N
        Button_imprimir.setText("Imprimir");
        Button_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_imprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Seleccionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_imprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button_imprimir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Button_Seleccionar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Button_Cancelar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Button_Eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GuardarActionPerformed

        if (validar() == 5) {
            saveCliente();

            JOptionPane.showMessageDialog(null, "Guardado exitosamente");
            limpiar();
            this.ci = "";
            this.ruc = "";
            this.nombre = "";
            this.apellido = "";
            this.direccion = "";
            this.telefono = "";
            this.email = "";
            this.descuento = 0;

        } else {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        }
    }//GEN-LAST:event_Button_GuardarActionPerformed

    private void Button_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_Button_LimpiarActionPerformed

    private void TextField_rucClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_rucClienteKeyReleased
        if (TextField_rucCliente.getText().equals("")) {
            Label_rucCliente.setForeground(new Color(102, 102, 102));
        } else {
            Label_rucCliente.setText("Ruc");
            Label_rucCliente.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_rucClienteKeyReleased

    private void TextField_rucClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_rucClienteKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_rucClienteKeyTyped

    private void TextField_CiClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CiClienteKeyReleased
        if (TextField_CiCliente.getText().equals("")) {
            Label_ciCliente.setForeground(new Color(102, 102, 102));
        } else {
            Label_ciCliente.setText("CI");
            Label_ciCliente.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_CiClienteKeyReleased

    private void TextField_CiClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CiClienteKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_CiClienteKeyTyped

    private void TextField_NombreClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_NombreClienteKeyReleased
        if (TextField_NombreCliente.getText().equals("")) {
            Label_NombreCliente.setForeground(new Color(102, 102, 102));
        } else {
            Label_NombreCliente.setText("Nombres completos");
            Label_NombreCliente.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_NombreClienteKeyReleased

    private void TextField_NombreClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_NombreClienteKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_NombreClienteKeyTyped

    private void TextField_ApellidioClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ApellidioClienteKeyReleased
        if (TextField_ApellidioCliente.getText().equals("")) {
            Label_ApellidoCliente.setForeground(new Color(102, 102, 102));
        } else {
            Label_ApellidoCliente.setText("Apellidos");
            Label_ApellidoCliente.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_ApellidioClienteKeyReleased

    private void TextField_ApellidioClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ApellidioClienteKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_ApellidioClienteKeyTyped

    private void TextField_DireccioClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_DireccioClienteKeyReleased
        if (TextField_DireccioCliente.getText().equals("")) {
            Label_DireccionCliente.setForeground(new Color(102, 102, 102));
        } else {
            Label_DireccionCliente.setText("Dirección");
            Label_DireccionCliente.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_DireccioClienteKeyReleased

    private void TextField_DireccioClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_DireccioClienteKeyTyped

    }//GEN-LAST:event_TextField_DireccioClienteKeyTyped

    private void TextField_TelefonoClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_TelefonoClienteKeyReleased
        if (TextField_TelefonoCliente.getText().equals("")) {
            Label_TelefonoCliente.setForeground(new Color(102, 102, 102));
        } else {
            Label_TelefonoCliente.setText("Teléfono");
            Label_TelefonoCliente.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_TelefonoClienteKeyReleased

    private void TextField_TelefonoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_TelefonoClienteKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_TelefonoClienteKeyTyped

    public void actualizar() {
        System.out.println("valor de validar ; "+validar());
        if (validar() < 5) {

            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("FALTAN CAMPOS DE LLENAR");
            er.msj1.setText("");
            er.setVisible(true);

        } else {
            //String ci, String nom, String ruc, String dir, String ape, String telf
            Sentencias s = new Sentencias(ci, nombre, ruc, direccion, apellido, telefono);
            s.setId(this.ids);

            int opcion = clientes.Opciones.actualizar(s);
            if (opcion != 0) {

                clientes.Opciones.listar("");

                SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                sa.titulo.setText("¡HECHO!");
                sa.msj.setText("SE HAN GUARDADO LOS CAMBIOS");
                sa.msj1.setText("");
                sa.setVisible(true);
            } else {
                System.out.println(s.toString());
            }
        }

    }
    private void Button_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EditarActionPerformed
        actualizar();
        limpiar();
        ci = "";
        ruc = "";
        nombre = "";
        apellido = "";
        direccion = "";
        telefono = "";
        this.ids=0;

    }//GEN-LAST:event_Button_EditarActionPerformed

    private void Button_SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SeleccionarActionPerformed
        this.Button_Guardar.setEnabled(false);
        this.Button_Editar.setEnabled(true);
        this.ids = Integer.parseInt((String) Table_Clientes.getValueAt(Table_Clientes.getSelectedRow(), 0));

        TextField_rucCliente.setText(Table_Clientes.getValueAt(Table_Clientes.getSelectedRow(), 1).toString());
        TextField_CiCliente.setText(Table_Clientes.getValueAt(Table_Clientes.getSelectedRow(), 2).toString());
        TextField_NombreCliente.setText(Table_Clientes.getValueAt(Table_Clientes.getSelectedRow(), 3).toString());
        TextField_ApellidioCliente.setText(Table_Clientes.getValueAt(Table_Clientes.getSelectedRow(), 4).toString());
        TextField_DireccioCliente.setText(Table_Clientes.getValueAt(Table_Clientes.getSelectedRow(), 5).toString());
        TextField_TelefonoCliente.setText(Table_Clientes.getValueAt(Table_Clientes.getSelectedRow(), 6).toString());

    }//GEN-LAST:event_Button_SeleccionarActionPerformed

    private void TextField_BuscarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_BuscarClienteKeyTyped
        char letras = evt.getKeyChar();

        if (Character.isLowerCase(letras)) {
            String cad = ("" + letras).toUpperCase();
            letras = cad.charAt(0);
            evt.setKeyChar(letras);
        }
    }//GEN-LAST:event_TextField_BuscarClienteKeyTyped

    private void Button_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EliminarActionPerformed
        try {
            int id_ad = Integer.parseInt((String) Table_Clientes.getValueAt(Table_Clientes.getSelectedRow(), 0));
            int elimina = clientes.Opciones.eliminar(id_ad);
            if (elimina != 0) {

                clientes.Opciones.listar("");
                SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                sa.titulo.setText("¡HECHO!");
                sa.msj.setText("SE HA ELIMINADO UN");
                sa.msj1.setText("REGISTRO");
                sa.setVisible(true);
            }
            //productoController.destroy(id_ad);

            //LoadDates();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Button_EliminarActionPerformed

    private void Button_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelarActionPerformed
        limpiar();
        this.Button_Guardar.setEnabled(true);
        this.Button_Editar.setEnabled(false);
    }//GEN-LAST:event_Button_CancelarActionPerformed

    private void TextField_BuscarClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_BuscarClienteKeyReleased
        clientes.Opciones.listar(this.TextField_BuscarCliente.getText());
    }//GEN-LAST:event_TextField_BuscarClienteKeyReleased

    private void Button_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_imprimirActionPerformed
        try {
            ConexionBD cc = new ConexionBD();
            JasperReport reporte = (JasperReport) JRLoader.loadObject("ReporteClientes.jasper");

            JasperPrint j = JasperFillManager.fillReport(reporte, null, cc.conexion());
            JasperViewer jv = new JasperViewer(j, false);
            jv.setTitle("Reporte Clientes Registrados");
            jv.setVisible(true);

        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
    }//GEN-LAST:event_Button_imprimirActionPerformed

    private void saveCliente() {
        clientes.Sentencias sentecia = new clientes.Sentencias(ci, nombre, ruc, direccion, apellido, telefono);
        clientes.Opciones.registrar(sentecia);
        clientes.Opciones.listar("");

    }

    private int validar() {
        int val = 0;
        if (TextField_CiCliente.getText().equals("")) {
            Label_ciCliente.setText("Ingrese CI");
            Label_ciCliente.setForeground(Color.red);
            TextField_CiCliente.requestFocus();
        } else {
            val++;
            if (TextField_NombreCliente.getText().equals("")) {
                Label_NombreCliente.setText("Ingrese el nombre");
                Label_NombreCliente.setForeground(Color.red);
                TextField_NombreCliente.requestFocus();
            } else {
                val++;
                if (TextField_ApellidioCliente.getText().equals("")) {
                    Label_ApellidoCliente.setText("Ingrese el apellido");
                    Label_ApellidoCliente.setForeground(Color.red);
                    TextField_ApellidioCliente.requestFocus();
                } else {
                    val++;
                    if (TextField_DireccioCliente.getText().equals("")) {
                        Label_DireccionCliente.setText("Ingrese la dirección");
                        Label_DireccionCliente.setForeground(Color.red);
                        TextField_DireccioCliente.requestFocus();
                    } else {
                        val++;
                        if (TextField_TelefonoCliente.getText().equals("")) {
                            Label_TelefonoCliente.setText("Ingrese el teléfono");
                            Label_TelefonoCliente.setForeground(Color.red);
                            TextField_TelefonoCliente.requestFocus();
                        } else {
                            val++;
                            if (acction.equals("insert")) {
                                ci = TextField_CiCliente.getText();
                                ruc = TextField_rucCliente.getText();
                                nombre = TextField_NombreCliente.getText().toUpperCase();
                                apellido = TextField_ApellidioCliente.getText().toUpperCase();
                                direccion = TextField_DireccioCliente.getText().toUpperCase();
                                telefono = TextField_TelefonoCliente.getText();

                            }

                        }

                    }

                }

            }
        }

        return val;
    }

    private void limpiar() {
        TextField_CiCliente.setText("");
        TextField_rucCliente.setText("");
        TextField_NombreCliente.setText("");
        TextField_ApellidioCliente.setText("");
        TextField_DireccioCliente.setText("");
        TextField_TelefonoCliente.setText("");

        Label_ciCliente.setForeground(new Color(102, 102, 102));
        Label_rucCliente.setForeground(new Color(102, 102, 102));
        Label_NombreCliente.setForeground(new Color(102, 102, 102));
        Label_ApellidoCliente.setForeground(new Color(102, 102, 102));
        Label_DireccionCliente.setForeground(new Color(102, 102, 102));
        Label_TelefonoCliente.setForeground(new Color(102, 102, 102));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cancelar;
    private javax.swing.JButton Button_Editar;
    private javax.swing.JButton Button_Eliminar;
    private javax.swing.JButton Button_Guardar;
    private javax.swing.JButton Button_Limpiar;
    private javax.swing.JButton Button_Seleccionar;
    private javax.swing.JButton Button_imprimir;
    private javax.swing.JLabel Label_ApellidoCliente;
    private javax.swing.JLabel Label_DireccionCliente;
    private javax.swing.JLabel Label_NombreCliente;
    private javax.swing.JLabel Label_TelefonoCliente;
    private javax.swing.JLabel Label_ciCliente;
    private javax.swing.JLabel Label_rucCliente;
    public static javax.swing.JTable Table_Clientes;
    private javax.swing.JTextField TextField_ApellidioCliente;
    private javax.swing.JTextField TextField_BuscarCliente;
    private javax.swing.JTextField TextField_CiCliente;
    private javax.swing.JTextField TextField_DireccioCliente;
    private javax.swing.JTextField TextField_NombreCliente;
    private javax.swing.JTextField TextField_TelefonoCliente;
    private javax.swing.JTextField TextField_rucCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
