/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import ModelClass.TextFieldEven;
import alertas.principal.ErrorAlert;
import alertas.principal.SuccessAlert;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;

import producto.ModalProductoM;
import producto.Sentencias;

import ventas.Opciones;

/**
 *
 * @author RojeruSan
 */
public class PnlCompras extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    private String acction = "insert";

    private int agregar;
    TextFieldEven evento = new TextFieldEven();

    private String cod = "";
    private String nom = "";
    private String des = "";
    private double pc = 0;
    private double pv = 0;
    private double pm = 0;
    private int idprovedor;
    private int cantidad = 0;

//    ProductoJpaController productoController = new ProductoJpaController();
//    ProveedorJpaController provedor = new ProveedorJpaController();
    DefaultTableModel modelo2;
    int ids;
    private TableRowSorter trsfiltro;

    public PnlCompras() {
        initComponents();
        this.TextField_BuscarProveedor.requestFocusInWindow();
        producto.Opciones.listar("");

    }

    public void filtro() {
        trsfiltro.setRowFilter(RowFilter.regexFilter(TextField_BuscarProveedor.getText(), 4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Label_codPRODUCTO = new javax.swing.JLabel();
        TextField_CODPRODUCTO = new javax.swing.JTextField();
        Label_canPRODUCTO = new javax.swing.JLabel();
        TextField_canPRODUCTO = new javax.swing.JTextField();
        materialButtomRectangle2 = new materialdesing.MaterialButtomRectangle();
        materialButtomRectangle3 = new materialdesing.MaterialButtomRectangle();
        materialButtomRectangle4 = new materialdesing.MaterialButtomRectangle();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TextField_BuscarProveedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Proveedores = new javax.swing.JTable();
        materialButtomRectangle1 = new materialdesing.MaterialButtomRectangle();
        materialButtomRectangle5 = new materialdesing.MaterialButtomRectangle();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(80, 80, 97));
        jLabel2.setText("Datos de la compra");
        jLabel2.setToolTipText("");

        Label_codPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_codPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        Label_codPRODUCTO.setText("Código");
        Label_codPRODUCTO.setToolTipText("");

        TextField_CODPRODUCTO.setEditable(false);
        TextField_CODPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_CODPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_CODPRODUCTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_CODPRODUCTOKeyTyped(evt);
            }
        });

        Label_canPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_canPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        Label_canPRODUCTO.setText("Cantidad");

        TextField_canPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_canPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_canPRODUCTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_canPRODUCTOKeyTyped(evt);
            }
        });

        materialButtomRectangle2.setBackground(new java.awt.Color(204, 0, 0));
        materialButtomRectangle2.setForeground(new java.awt.Color(255, 255, 255));
        materialButtomRectangle2.setText("Cancelar");
        materialButtomRectangle2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        materialButtomRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButtomRectangle2ActionPerformed(evt);
            }
        });

        materialButtomRectangle3.setBackground(new java.awt.Color(255, 153, 0));
        materialButtomRectangle3.setForeground(new java.awt.Color(255, 255, 255));
        materialButtomRectangle3.setText("Limpiar");
        materialButtomRectangle3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        materialButtomRectangle3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButtomRectangle3ActionPerformed(evt);
            }
        });

        materialButtomRectangle4.setBackground(new java.awt.Color(0, 204, 51));
        materialButtomRectangle4.setForeground(new java.awt.Color(255, 255, 255));
        materialButtomRectangle4.setText("Comprar");
        materialButtomRectangle4.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        materialButtomRectangle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButtomRectangle4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TextField_canPRODUCTO)
                    .addComponent(TextField_CODPRODUCTO)
                    .addComponent(jLabel2)
                    .addComponent(Label_codPRODUCTO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_canPRODUCTO, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(materialButtomRectangle4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(materialButtomRectangle3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(materialButtomRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_codPRODUCTO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_CODPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_canPRODUCTO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_canPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(materialButtomRectangle4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(materialButtomRectangle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(materialButtomRectangle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(80, 80, 97));
        jLabel5.setText("Buscar");

        TextField_BuscarProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_BuscarProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_BuscarProveedorKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 97));
        jLabel1.setText("Compra ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(TextField_BuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(TextField_BuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Table_Proveedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Table_Proveedores.setForeground(new java.awt.Color(51, 51, 51));
        Table_Proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "NOMBRE", "COD BARRAS", "TIPO PRODUCTO", "$PRECIO", "STOCK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Proveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Table_Proveedores.setDoubleBuffered(true);
        Table_Proveedores.setRowHeight(20);
        Table_Proveedores.setSelectionBackground(new java.awt.Color(0, 153, 255));
        Table_Proveedores.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Table_Proveedores);
        if (Table_Proveedores.getColumnModel().getColumnCount() > 0) {
            Table_Proveedores.getColumnModel().getColumn(0).setResizable(false);
            Table_Proveedores.getColumnModel().getColumn(0).setPreferredWidth(6);
            Table_Proveedores.getColumnModel().getColumn(2).setResizable(false);
            Table_Proveedores.getColumnModel().getColumn(4).setPreferredWidth(10);
            Table_Proveedores.getColumnModel().getColumn(5).setResizable(false);
            Table_Proveedores.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        materialButtomRectangle1.setBackground(new java.awt.Color(80, 172, 224));
        materialButtomRectangle1.setForeground(new java.awt.Color(255, 255, 255));
        materialButtomRectangle1.setText("Nuevo ");
        materialButtomRectangle1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        materialButtomRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButtomRectangle1ActionPerformed(evt);
            }
        });

        materialButtomRectangle5.setBackground(new java.awt.Color(80, 172, 224));
        materialButtomRectangle5.setForeground(new java.awt.Color(255, 255, 255));
        materialButtomRectangle5.setText("Seleccionar");
        materialButtomRectangle5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        materialButtomRectangle5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButtomRectangle5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(materialButtomRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(materialButtomRectangle5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(materialButtomRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(materialButtomRectangle5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_CODPRODUCTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CODPRODUCTOKeyReleased
        if (TextField_CODPRODUCTO.getText().equals("")) {
            Label_codPRODUCTO.setForeground(new Color(102, 102, 102));
        } else {
            Label_codPRODUCTO.setText("Código");
            Label_codPRODUCTO.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_CODPRODUCTOKeyReleased

    private void TextField_CODPRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CODPRODUCTOKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_CODPRODUCTOKeyTyped

    private void TextField_canPRODUCTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_canPRODUCTOKeyReleased
        if (TextField_canPRODUCTO.getText().equals("")) {
            Label_canPRODUCTO.setForeground(new Color(102, 102, 102));
        } else {
            Label_canPRODUCTO.setText("Cantidad");
            Label_canPRODUCTO.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_canPRODUCTOKeyReleased

    private void TextField_canPRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_canPRODUCTOKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_canPRODUCTOKeyTyped

    private void TextField_BuscarProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_BuscarProveedorKeyTyped

        producto.Opciones.listar(this.TextField_BuscarProveedor.getText());

//        TextField_BuscarProveedor.addKeyListener(new KeyAdapter() {
//            public void keyReleased(final KeyEvent e) {
//                String cadena = (TextField_BuscarProveedor.getText().toUpperCase());
//                TextField_BuscarProveedor.setText(cadena);
//                repaint();
//                filtro();
//            }
//        });
//        trsfiltro = new TableRowSorter(Table_Proveedores.getModel());
//        Table_Proveedores.setRowSorter(trsfiltro);
    }//GEN-LAST:event_TextField_BuscarProveedorKeyTyped

    private void materialButtomRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButtomRectangle1ActionPerformed
        ModalProductoM mp = new ModalProductoM(new JFrame(), true);
        mp.titulo.setText("REGISTRAR");

        mp.setVisible(true);
    }//GEN-LAST:event_materialButtomRectangle1ActionPerformed

    private void materialButtomRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButtomRectangle2ActionPerformed
        limpiar();
    }//GEN-LAST:event_materialButtomRectangle2ActionPerformed

    private void materialButtomRectangle3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButtomRectangle3ActionPerformed
        limpiar();
    }//GEN-LAST:event_materialButtomRectangle3ActionPerformed
    public void guardar() {
        System.out.println("valor guardar : " + this.cantidad);
        if (validar() < 2) {

            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("FALTAN CAMPOS DE LLENAR");
            er.msj1.setText("");
            er.setVisible(true);

        } else {

            this.cantidad = this.cantidad + this.agregar;
            System.out.println("valor 2 variables : " + this.cantidad);
            producto.Sentencias s = new Sentencias(cantidad, ids);

            int opcion = producto.Opciones.actualizarStock(s);
            if (opcion != 0) {

                limpiar();
                SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                sa.titulo.setText("¡HECHO!");
                sa.msj.setText("PRODUCTO ACTUALIZADO");
                sa.msj1.setText("CORRECTAMENTE");
                sa.setVisible(true);
                producto.Opciones.listar("");
            }

            //}
        }
    }

    private void materialButtomRectangle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButtomRectangle4ActionPerformed
        if (validar() == 2) {
            guardar();
            limpiar();
            this.cod = "";
            this.nom = "";
            this.des = "";
            this.pc = 0;
            this.pv = 0;
            this.pm = 0;
            this.cantidad = 0;
            this.idprovedor = 0;
            this.agregar = 0;

        } else {
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("FALTAN CAMPOS DE LLENAR");
            er.msj1.setText("");
            er.setVisible(true);
        }
    }//GEN-LAST:event_materialButtomRectangle4ActionPerformed

    private void materialButtomRectangle5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButtomRectangle5ActionPerformed
        try {
            this.ids = Integer.parseInt((String) Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 0));

            TextField_CODPRODUCTO.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 0).toString());
            this.cantidad = Integer.parseInt((String) Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 5));
            System.out.println("valor : " + this.cantidad);
        } catch (Exception e) {
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("SELECIONE UN PRODUCTO");
            er.msj1.setText("");
            er.setVisible(true);
            System.out.println(e);
        }


    }//GEN-LAST:event_materialButtomRectangle5ActionPerformed

//    private void LoadDates() {
//        try {
//            Table_Proveedores.removeAll();
//            String[] titulos = {"id", "Codigo", "Nombre", "Descripcion", "Cantidad", "Precio compra", "Precio venta", "Precio x mayor"};
//            String[] registro = new String[9];
//            //Object o[] = null;
//            List<Producto> listproveedor = productoController.findProductoEntities();
//            modelo2 = new DefaultTableModel(null, titulos);
//
//            for (int i = 0; i < listproveedor.size(); i++) {
////                modelo2.addRow(o);
//                registro[0] = String.valueOf(listproveedor.get(i).getId());
//                registro[1] = listproveedor.get(i).getCodigo();
//                registro[2] = listproveedor.get(i).getNombre();
//                registro[3] = listproveedor.get(i).getDescripcion();
//                registro[4] = String.valueOf(listproveedor.get(i).getCantidad());
//                registro[5] = String.valueOf(listproveedor.get(i).getPcom());
//                registro[6] = String.valueOf(listproveedor.get(i).getPvp());
//                registro[7] = String.valueOf(listproveedor.get(i).getPmayor());
//                //registro[8] = listproveedor.get(i).getEmpresaProveedor();
//
//                //System.out.println(listLocal.get(i).getAdmin().toString());
//                modelo2.addRow(registro);
//            }
//            Table_Proveedores.setModel(modelo2);
//
//        } catch (Exception e) {
//            System.out.println(e.toString());
//        }
//
//    }
    private int validar() {
        int val = 0;

        if (TextField_canPRODUCTO.getText().equals("")) {
            Label_canPRODUCTO.setText("Ingrese cantidad");
            Label_canPRODUCTO.setForeground(Color.red);
            TextField_canPRODUCTO.requestFocus();
        } else {
            val++;

            if (TextField_CODPRODUCTO.getText().equals("")) {
                Label_codPRODUCTO.setText("Ingrese código");
                Label_codPRODUCTO.setForeground(Color.red);
                TextField_CODPRODUCTO.requestFocus();
            } else {

                val++;
                if (acction.equals("insert")) {

                    cod = TextField_CODPRODUCTO.getText();
                    System.out.println("valor validar : " + val);
                    this.agregar = Integer.parseInt(TextField_canPRODUCTO.getText());

//                                    empresa = TextField_empresaProveedor.getText().toUpperCase();
                }
            }

        }

        return val;
    }

    private void limpiar() {

        TextField_CODPRODUCTO.setText("");

        TextField_canPRODUCTO.setText("");

//        TextField_empresaProveedor.setText("");
        Label_codPRODUCTO.setForeground(new Color(102, 102, 102));

        Label_canPRODUCTO.setForeground(new Color(102, 102, 102));
        this.TextField_BuscarProveedor.requestFocusInWindow();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_canPRODUCTO;
    private javax.swing.JLabel Label_codPRODUCTO;
    public static javax.swing.JTable Table_Proveedores;
    public static javax.swing.JTextField TextField_BuscarProveedor;
    private javax.swing.JTextField TextField_CODPRODUCTO;
    private javax.swing.JTextField TextField_canPRODUCTO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private materialdesing.MaterialButtomRectangle materialButtomRectangle1;
    private materialdesing.MaterialButtomRectangle materialButtomRectangle2;
    private materialdesing.MaterialButtomRectangle materialButtomRectangle3;
    private materialdesing.MaterialButtomRectangle materialButtomRectangle4;
    private materialdesing.MaterialButtomRectangle materialButtomRectangle5;
    // End of variables declaration//GEN-END:variables
}
