/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import ModelClass.TextFieldEven;
import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JDateChooser;
import controllers.ClienteJpaController;
import controllers.Controlador;
import controllers.EmpleadoJpaController;
import controllers.ProveedorJpaController;
import controllers.ControllerCliente;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import models.Cliente;
import models.Empleado;
import models.Local;
import models.Proveedor;

/**
 *
 * @author RojeruSan
 */
public class PnlEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    private String acction = "insert", Id = "", dia, mes, anio, funcionCatDpt, idCat, dpt;
    private int pageSize, tab, maxReg, pageCount, currentPage, numReg;
    private int startRec, endRec;
    TextFieldEven evento = new TextFieldEven();

    private String ci = "";
    private String nombre = "";
    private String apellido = "";
    private int edad = 0;
    private String fechain;
    private String fechacob;
    private float sueldo = 0;
    private float adelando = 0;
    private float descuento = 0;

    Controlador control = new Controlador();
    EmpleadoJpaController empleadoController = new EmpleadoJpaController();
    DefaultTableModel modelo2;
    int ids;
    private TableRowSorter trsfiltro;

    public PnlEmpleados() {
        initComponents();
        LoadDates();
        this.Button_Guardar.setEnabled(true);
        this.Button_Editar.setEnabled(false);
    }

    public void filtro() {
        trsfiltro.setRowFilter(RowFilter.regexFilter(TextField_BuscarProveedor.getText(), 4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Button_Limpiar = new javax.swing.JButton();
        Button_Guardar = new javax.swing.JButton();
        Label_ciEmpleado = new javax.swing.JLabel();
        TextField_CiEmpleado = new javax.swing.JTextField();
        Label_NombreEmpleado = new javax.swing.JLabel();
        TextField_NombreEmpleado = new javax.swing.JTextField();
        Label_ApellidoEmpleado = new javax.swing.JLabel();
        TextField_ApellidioEmpleado = new javax.swing.JTextField();
        Label_edadEmpleado = new javax.swing.JLabel();
        Label_fechaingresoEmpleado = new javax.swing.JLabel();
        Label_fechaCobroEmpleado = new javax.swing.JLabel();
        Label_sueldoEmpleado = new javax.swing.JLabel();
        TextField_sueldoEmpleado = new javax.swing.JTextField();
        Button_Editar = new javax.swing.JButton();
        TextField_edadEmpleado = new javax.swing.JSpinner();
        TextField_fechaingresoEmpleado = new com.toedter.calendar.JDateChooser();
        TextField_fechacobroEmpleado = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TextField_BuscarProveedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Proveedores =   Table_Proveedores = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        Button_Seleccionar = new javax.swing.JButton();
        Button_Eliminar = new javax.swing.JButton();
        Button_Cancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(80, 80, 97));
        jLabel2.setText("Datos del empleado");
        jLabel2.setToolTipText("");

        Button_Limpiar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png"))); // NOI18N
        Button_Limpiar.setText("Limpiar");
        Button_Limpiar.setBorder(null);
        Button_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LimpiarActionPerformed(evt);
            }
        });

        Button_Guardar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Agregar.png"))); // NOI18N
        Button_Guardar.setText("Guardar");
        Button_Guardar.setBorder(null);
        Button_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GuardarActionPerformed(evt);
            }
        });

        Label_ciEmpleado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_ciEmpleado.setForeground(new java.awt.Color(102, 102, 102));
        Label_ciEmpleado.setText("CI");
        Label_ciEmpleado.setToolTipText("");

        TextField_CiEmpleado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_CiEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_CiEmpleadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_CiEmpleadoKeyTyped(evt);
            }
        });

        Label_NombreEmpleado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_NombreEmpleado.setForeground(new java.awt.Color(102, 102, 102));
        Label_NombreEmpleado.setText("Nombre completo");
        Label_NombreEmpleado.setToolTipText("");

        TextField_NombreEmpleado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_NombreEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_NombreEmpleadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_NombreEmpleadoKeyTyped(evt);
            }
        });

        Label_ApellidoEmpleado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_ApellidoEmpleado.setForeground(new java.awt.Color(102, 102, 102));
        Label_ApellidoEmpleado.setText("Apellido");

        TextField_ApellidioEmpleado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_ApellidioEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_ApellidioEmpleadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_ApellidioEmpleadoKeyTyped(evt);
            }
        });

        Label_edadEmpleado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_edadEmpleado.setForeground(new java.awt.Color(102, 102, 102));
        Label_edadEmpleado.setText("edad");
        Label_edadEmpleado.setToolTipText("");

        Label_fechaingresoEmpleado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_fechaingresoEmpleado.setForeground(new java.awt.Color(102, 102, 102));
        Label_fechaingresoEmpleado.setText("Fecha de ingreso");

        Label_fechaCobroEmpleado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_fechaCobroEmpleado.setForeground(new java.awt.Color(102, 102, 102));
        Label_fechaCobroEmpleado.setText("Fecha cobro");

        Label_sueldoEmpleado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_sueldoEmpleado.setForeground(new java.awt.Color(102, 102, 102));
        Label_sueldoEmpleado.setText("Salario");

        TextField_sueldoEmpleado.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_sueldoEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_sueldoEmpleadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_sueldoEmpleadoKeyTyped(evt);
            }
        });

        Button_Editar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar.png"))); // NOI18N
        Button_Editar.setText("Editar");
        Button_Editar.setBorder(null);
        Button_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EditarActionPerformed(evt);
            }
        });

        TextField_fechaingresoEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_fechaingresoEmpleadoKeyReleased(evt);
            }
        });

        TextField_fechacobroEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_fechacobroEmpleadoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Button_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextField_NombreEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(TextField_ApellidioEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(TextField_CiEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(TextField_sueldoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(Label_ciEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_NombreEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_ApellidoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_edadEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_fechaingresoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_fechaCobroEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_sueldoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextField_edadEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextField_fechaingresoEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextField_fechacobroEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_ciEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_CiEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_NombreEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_NombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_ApellidoEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_ApellidioEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Label_edadEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_edadEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(Label_fechaingresoEmpleado)
                .addGap(8, 8, 8)
                .addComponent(TextField_fechaingresoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_fechaCobroEmpleado)
                .addGap(8, 8, 8)
                .addComponent(TextField_fechacobroEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_sueldoEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_sueldoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(80, 80, 97));
        jLabel5.setText("Buscar");

        TextField_BuscarProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_BuscarProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_BuscarProveedorKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 97));
        jLabel1.setText("Empleados");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(86, 86, 86)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(TextField_BuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextField_BuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Table_Proveedores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Table_Proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table_Proveedores.setRowHeight(20);
        Table_Proveedores.setSelectionBackground(new java.awt.Color(102, 204, 255));
        jScrollPane2.setViewportView(Table_Proveedores);

        Button_Seleccionar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Seleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Left.png"))); // NOI18N
        Button_Seleccionar.setText("Seleccionar");
        Button_Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SeleccionarActionPerformed(evt);
            }
        });

        Button_Eliminar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png"))); // NOI18N
        Button_Eliminar.setText("Eliminar");
        Button_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EliminarActionPerformed(evt);
            }
        });

        Button_Cancelar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar.png"))); // NOI18N
        Button_Cancelar.setText("Cancelar");
        Button_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Seleccionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button_Seleccionar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GuardarActionPerformed

        if (validar() == 6) {
            saveCliente();

            JOptionPane.showMessageDialog(null, "Guardado exitosamente");
            limpiar();
            this.ci = "";
            this.nombre = "";
            this.apellido = "";
            this.edad = 0;
            this.fechain = null;
            this.fechacob = null;
            this.sueldo = 0;

        } else {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        }
    }//GEN-LAST:event_Button_GuardarActionPerformed

    private void Button_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_Button_LimpiarActionPerformed

    private void TextField_CiEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CiEmpleadoKeyReleased
        if (TextField_CiEmpleado.getText().equals("")) {
            Label_ciEmpleado.setForeground(new Color(102, 102, 102));
        } else {
            Label_ciEmpleado.setText("CI");
            Label_ciEmpleado.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_CiEmpleadoKeyReleased

    private void TextField_CiEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CiEmpleadoKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_CiEmpleadoKeyTyped

    private void TextField_NombreEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_NombreEmpleadoKeyReleased
        if (TextField_NombreEmpleado.getText().equals("")) {
            Label_NombreEmpleado.setForeground(new Color(102, 102, 102));
        } else {
            Label_NombreEmpleado.setText("Nombres completos");
            Label_NombreEmpleado.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_NombreEmpleadoKeyReleased

    private void TextField_NombreEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_NombreEmpleadoKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_NombreEmpleadoKeyTyped

    private void TextField_ApellidioEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ApellidioEmpleadoKeyReleased
        if (TextField_ApellidioEmpleado.getText().equals("")) {
            Label_ApellidoEmpleado.setForeground(new Color(102, 102, 102));
        } else {
            Label_ApellidoEmpleado.setText("Apellidos");
            Label_ApellidoEmpleado.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_ApellidioEmpleadoKeyReleased

    private void TextField_ApellidioEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ApellidioEmpleadoKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_ApellidioEmpleadoKeyTyped

    private void TextField_sueldoEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_sueldoEmpleadoKeyReleased
        if (TextField_sueldoEmpleado.getText().equals("")) {
            Label_sueldoEmpleado.setForeground(new Color(102, 102, 102));
        } else {
            Label_sueldoEmpleado.setText("Salario");
            Label_sueldoEmpleado.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_sueldoEmpleadoKeyReleased

    private void TextField_sueldoEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_sueldoEmpleadoKeyTyped
        evento.numberDecimalkeyPress(evt, TextField_sueldoEmpleado);
    }//GEN-LAST:event_TextField_sueldoEmpleadoKeyTyped

    private void Button_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EditarActionPerformed
        try {
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Button_EditarActionPerformed

    private void Button_SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SeleccionarActionPerformed
        this.Button_Guardar.setEnabled(false);
        this.Button_Editar.setEnabled(true);
        this.ids = Integer.parseInt((String) Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 0));
        TextField_CiEmpleado.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 1).toString());
        TextField_NombreEmpleado.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 2).toString());
        TextField_ApellidioEmpleado.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 3).toString());
        TextField_edadEmpleado.setValue(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 4).toString());
        TextField_fechaingresoEmpleado.setDateFormatString(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 5).toString());
        TextField_fechacobroEmpleado.setDateFormatString(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 6).toString());
        TextField_sueldoEmpleado.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 7).toString());

    }//GEN-LAST:event_Button_SeleccionarActionPerformed

    private void TextField_BuscarProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_BuscarProveedorKeyTyped
        TextField_BuscarProveedor.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (TextField_BuscarProveedor.getText().toUpperCase());
                TextField_BuscarProveedor.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsfiltro = new TableRowSorter(Table_Proveedores.getModel());
        Table_Proveedores.setRowSorter(trsfiltro);
    }//GEN-LAST:event_TextField_BuscarProveedorKeyTyped

    private void Button_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EliminarActionPerformed
        try {
            int id_ad = Integer.parseInt((String) Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 0));

            empleadoController.destroy(id_ad);

            LoadDates();
            JOptionPane.showMessageDialog(null, "Eliminado exitosamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Button_EliminarActionPerformed

    private void Button_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelarActionPerformed
        limpiar();
        this.Button_Guardar.setEnabled(true);
        this.Button_Editar.setEnabled(false);
    }//GEN-LAST:event_Button_CancelarActionPerformed

    private void TextField_fechacobroEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_fechacobroEmpleadoKeyReleased
       if (TextField_fechacobroEmpleado.getDateFormatString().equals("")) {
            Label_fechaCobroEmpleado.setForeground(new Color(102, 102, 102));
        } else {
            Label_fechaCobroEmpleado.setText("Fecha cobro");
            Label_fechaCobroEmpleado.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_fechacobroEmpleadoKeyReleased

    private void TextField_fechaingresoEmpleadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_fechaingresoEmpleadoKeyReleased
        if (TextField_fechaingresoEmpleado.getDateFormatString().equals("")) {
            Label_fechaingresoEmpleado.setForeground(new Color(102, 102, 102));
        } else {
            Label_fechaingresoEmpleado.setText("Fecha ingreso");
            Label_fechaingresoEmpleado.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_fechaingresoEmpleadoKeyReleased

    private void LoadDates() {
        try {
            Table_Proveedores.removeAll();
            String[] titulos = {"id", "Ci", "Nombres", "Apellidos", "Edad", "Ingreso", "Cobro", "Sueldo"};
            String[] registro = new String[8];
            //Object o[] = null;
            List<Empleado> listempleado = empleadoController.findEmpleadoEntities();
            modelo2 = new DefaultTableModel(null, titulos);

            for (int i = 0; i < listempleado.size(); i++) {
//                modelo2.addRow(o);
                registro[0] = String.valueOf(listempleado.get(i).getId());
                registro[1] = listempleado.get(i).getCi();
                registro[2] = listempleado.get(i).getNombres();
                registro[3] = listempleado.get(i).getApellidos();
                registro[4] = String.valueOf(listempleado.get(i).getEdad());
                registro[5] = listempleado.get(i).getFecha_ingreso().toString();
                registro[6] = listempleado.get(i).getFecha_cobro().toString();
                registro[7] = String.valueOf(listempleado.get(i).getSueldo());

                //System.out.println(listLocal.get(i).getAdmin().toString());
                modelo2.addRow(registro);
            }
            Table_Proveedores.setModel(modelo2);

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

    private void saveCliente() {
        try {
            System.out.println("administrador recuperado    :  ");
            Empleado empleado = new Empleado();

            empleado.setCi(this.ci);
            empleado.setNombres(this.nombre);
            empleado.setApellidos(this.apellido);
            empleado.setEdad(this.edad);
            empleado.setFecha_ingreso(this.fechain);
            empleado.setFecha_cobro(this.fechacob);
            empleado.setSueldo(this.sueldo);
            empleado.setDescuento(0);
            empleado.setAdelanto(0);
            empleadoController.create(empleado);
            LoadDates();

        } catch (Exception e) {
            System.out.println(e);
//            JOptionPane.showMessageDialog(null, e);
        }
    }

    private int validar() {
        int val = 0;
        if (TextField_CiEmpleado.getText().equals("")) {
            Label_ciEmpleado.setText("Ingrese CI");
            Label_ciEmpleado.setForeground(Color.red);
            TextField_CiEmpleado.requestFocus();
        } else {
            val++;
            if (TextField_NombreEmpleado.getText().equals("")) {
                Label_NombreEmpleado.setText("Ingrese el nombre");
                Label_NombreEmpleado.setForeground(Color.red);
                TextField_NombreEmpleado.requestFocus();
            } else {
                val++;
                if (TextField_ApellidioEmpleado.getText().equals("")) {
                    Label_ApellidoEmpleado.setText("Ingrese el apellido");
                    Label_ApellidoEmpleado.setForeground(Color.red);
                    TextField_ApellidioEmpleado.requestFocus();
                } else {
                    val++;
                    if ((int) TextField_edadEmpleado.getValue() < 18) {
                        Label_edadEmpleado.setText("Ingrese edad mayor a 18");
                        Label_edadEmpleado.setForeground(Color.red);
                        TextField_edadEmpleado.requestFocus();
                    } else {
                        val++;
                        if (TextField_fechaingresoEmpleado.getDateFormatString().equals("")) {
                            Label_fechaingresoEmpleado.setText("Elija una fecha");
                            Label_fechaingresoEmpleado.setForeground(Color.red);
                            TextField_fechaingresoEmpleado.requestFocus();
                        } else {
                            val++;
                            if (TextField_sueldoEmpleado.getText().equals("")) {
                                Label_sueldoEmpleado.setText("Ingrese el salario");
                                Label_sueldoEmpleado.setForeground(Color.red);
                                TextField_sueldoEmpleado.requestFocus();
                            } else {
                                val++;
                                if (acction.equals("insert")) {
                                    ci = TextField_CiEmpleado.getText();
                                    nombre = TextField_NombreEmpleado.getText().toUpperCase();
                                    apellido = TextField_ApellidioEmpleado.getText().toUpperCase();
                                    edad = (int) TextField_edadEmpleado.getValue();
                                    fechain= getFechaInicio(TextField_fechaingresoEmpleado);
                                    fechacob= getFechaInicio(TextField_fechacobroEmpleado);
                                   
                                    

                                }

                            }

                        }

                    }

                }

            }
        }

        return val;
    }

    public Date darFormato(String fecha) {
        Date date = null;
        try {
            String str_date = fecha;
            DateFormat formatter;

            formatter = new SimpleDateFormat("yyy-MMM-dd");
            date = (Date) formatter.parse(str_date);
            Calendar cal = Calendar.getInstance();
            cal.setTime(date);
            System.out.println("Today is " + date);
            return date;
        } catch (Exception e) {
            System.out.println("Exception :" + e);
            return date;
        }

    }

    public String getFechaInicio(JDateChooser calendar) {
        String fecha = "";
        try {
            int dia = calendar.getDate().getDate();
            int mes = calendar.getDate().getMonth() + 1;
            int anio = calendar.getDate().getYear() + 1900;
            fecha = anio + "-" + mes + "-" + dia;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "debe elegir una fecha");
        }
        return fecha;

    }

    private void limpiar() {
        TextField_CiEmpleado.setText("");
        TextField_NombreEmpleado.setText("");
        TextField_ApellidioEmpleado.setText("");
        TextField_edadEmpleado.setValue(0);
        TextField_fechaingresoEmpleado.removeAll();
        TextField_fechacobroEmpleado.removeAll();
        TextField_sueldoEmpleado.setText("");

        Label_ciEmpleado.setForeground(new Color(102, 102, 102));
        Label_NombreEmpleado.setForeground(new Color(102, 102, 102));
        Label_ApellidoEmpleado.setForeground(new Color(102, 102, 102));
        Label_edadEmpleado.setForeground(new Color(102, 102, 102));
        Label_fechaingresoEmpleado.setForeground(new Color(102, 102, 102));
        Label_fechaCobroEmpleado.setForeground(new Color(102, 102, 102));
        Label_sueldoEmpleado.setForeground(new Color(102, 102, 102));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cancelar;
    private javax.swing.JButton Button_Editar;
    private javax.swing.JButton Button_Eliminar;
    private javax.swing.JButton Button_Guardar;
    private javax.swing.JButton Button_Limpiar;
    private javax.swing.JButton Button_Seleccionar;
    private javax.swing.JLabel Label_ApellidoEmpleado;
    private javax.swing.JLabel Label_NombreEmpleado;
    private javax.swing.JLabel Label_ciEmpleado;
    private javax.swing.JLabel Label_edadEmpleado;
    private javax.swing.JLabel Label_fechaCobroEmpleado;
    private javax.swing.JLabel Label_fechaingresoEmpleado;
    private javax.swing.JLabel Label_sueldoEmpleado;
    private javax.swing.JTable Table_Proveedores;
    private javax.swing.JTextField TextField_ApellidioEmpleado;
    private javax.swing.JTextField TextField_BuscarProveedor;
    private javax.swing.JTextField TextField_CiEmpleado;
    private javax.swing.JTextField TextField_NombreEmpleado;
    private javax.swing.JSpinner TextField_edadEmpleado;
    private com.toedter.calendar.JDateChooser TextField_fechacobroEmpleado;
    private com.toedter.calendar.JDateChooser TextField_fechaingresoEmpleado;
    private javax.swing.JTextField TextField_sueldoEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
