/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import ModelClass.TextFieldEven;
import alertas.principal.ErrorAlert;
import alertas.principal.SuccessAlert;
import alertas.principal.WarningAlertP;
import alertas.principal.WarningAlertP1;
import conexion.ConexionBD;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

import producto.ModalProductoM;
import producto.ModalProductoMInventario;
import producto.Sentencias;

import ventas.Opciones;
import ventas.ProductoReport;
import ventas.VentaReport;

/**
 *
 * @author RojeruSan
 */
public class PnlGestionVentas extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    private String acction = "insert";

    private int agregar;
    TextFieldEven evento = new TextFieldEven();

    private String cod = "";
    private String nom = "";
    private String des = "";
    private double pc = 0;
    private double pv = 0;
    private double pm = 0;
    private int idprovedor;
    private int cantidad = 0;
    private int rowtable;

//    ProductoJpaController productoController = new ProductoJpaController();
//    ProveedorJpaController provedor = new ProveedorJpaController();
    DefaultTableModel modelo2;
    int ids;
    private TableRowSorter trsfiltro;

    public PnlGestionVentas() {
        initComponents();
        ventas.Opciones.listartodoProductosVendidos(fechaactual(), fechaactual());
        this.rowtable = 1;
        this.radiofechas.setSelected(true);
        sumar();

    }

    public static String fechaactual() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("YYYY/MM/dd");
        return formatofecha.format(fecha);
    }

    public String getFechaInicio() {
        String fecha = "";
        try {
            int dia = datestart.getDate().getDate();
            int mes = datestart.getDate().getMonth() + 1;
            int anio = datestart.getDate().getYear() + 1900;
            fecha = anio + "/" + mes + "/" + dia;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "debe elegir una fecha");
        }
        return fecha;

    }

    public String getFechaFin() {
        String fecha = "";
        try {
            int dia = dateend.getDate().getDate();
            int mes = dateend.getDate().getMonth() + 1;
            int anio = dateend.getDate().getYear() + 1900;
            fecha = anio + "/" + mes + "/" + dia;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "debe elegir una fecha");
        }
        return fecha;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        radiofechas = new javax.swing.JRadioButton();
        radiofacturas = new javax.swing.JRadioButton();
        dateend = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        datestart = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        materialButtomRectangle10 = new materialdesing.MaterialButtomRectangle();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Proveedores = new javax.swing.JTable();
        materialButtomRectangle9 = new materialdesing.MaterialButtomRectangle();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 97));
        jLabel1.setText("Reporte ventas");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(80, 80, 97));
        jLabel5.setText("filtrar por");

        radiofechas.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        radiofechas.setForeground(new java.awt.Color(102, 102, 102));
        radiofechas.setText("productos");
        radiofechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiofechasActionPerformed(evt);
            }
        });

        radiofacturas.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        radiofacturas.setForeground(new java.awt.Color(102, 102, 102));
        radiofacturas.setText("facturas");
        radiofacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiofacturasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Hasta");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Desde");

        materialButtomRectangle10.setBackground(new java.awt.Color(0, 204, 153));
        materialButtomRectangle10.setForeground(new java.awt.Color(255, 255, 255));
        materialButtomRectangle10.setText("Buscar");
        materialButtomRectangle10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        materialButtomRectangle10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButtomRectangle10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datestart, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateend, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radiofechas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radiofacturas)
                .addGap(28, 28, 28)
                .addComponent(materialButtomRectangle10, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(materialButtomRectangle10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(datestart, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dateend, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(radiofacturas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                .addComponent(radiofechas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table_Proveedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Table_Proveedores.setForeground(new java.awt.Color(51, 51, 51));
        Table_Proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Table_Proveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Table_Proveedores.setDoubleBuffered(true);
        Table_Proveedores.setRowHeight(20);
        Table_Proveedores.setSelectionBackground(new java.awt.Color(0, 153, 255));
        Table_Proveedores.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Table_Proveedores);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 18, 1004, 350));

        materialButtomRectangle9.setBackground(new java.awt.Color(80, 172, 224));
        materialButtomRectangle9.setForeground(new java.awt.Color(255, 255, 255));
        materialButtomRectangle9.setText("imprimir");
        materialButtomRectangle9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        materialButtomRectangle9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButtomRectangle9ActionPerformed(evt);
            }
        });
        jPanel8.add(materialButtomRectangle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, 131, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("0");
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 120, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Total ingresos");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void materialButtomRectangle9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButtomRectangle9ActionPerformed
        try {
            // TODO add your handling code here:
            List<VentaReport> listaProductos = new ArrayList<VentaReport>();
            int filas = Table_Proveedores.getRowCount();
            for (int i = 0; i < filas; i++) {
                VentaReport p = new VentaReport(Table_Proveedores.getValueAt(i, 0).toString(), Table_Proveedores.getValueAt(i, 1).toString(), Table_Proveedores.getValueAt(i, 2).toString(), Table_Proveedores.getValueAt(i, 3).toString(), Table_Proveedores.getValueAt(i, 4).toString(), Table_Proveedores.getValueAt(i, 5).toString(), Table_Proveedores.getValueAt(i, 6).toString());
                listaProductos.add(p);
            }

            JasperReport reporte = (JasperReport) JRLoader.loadObject("ReporteVentas.jasper");

            Map<String, String> parametros = new HashMap<String, String>();
            parametros.put("fila5", Table_Proveedores.getColumnName(4).toString());
            parametros.put("fila6", Table_Proveedores.getColumnName(5).toString());
            parametros.put("fila7", Table_Proveedores.getColumnName(6).toString());
            System.out.println(Table_Proveedores.getColumnName(4).toString());
            System.out.println(Table_Proveedores.getColumnName(5).toString());
            System.out.println(Table_Proveedores.getColumnName(6).toString());
            parametros.put("totalventa",this.jLabel4.getText());

            JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, parametros, new JRBeanCollectionDataSource(listaProductos));
            JasperViewer.viewReport(jasperPrint, false);
            JRExporter exporter = new JRPdfExporter();
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, jasperPrint);
            exporter.setParameter(JRExporterParameter.OUTPUT_FILE, new java.io.File("reportesVentas.pdf"));
            exporter.exportReport();
        } catch (JRException ex) {
            Logger.getLogger(PnlVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_materialButtomRectangle9ActionPerformed


    public void sumar() {
        double sumtotal = 0;
        double cont;
        String filas;
        

        for (int i = 0; i < Table_Proveedores.getRowCount(); i++) {
            filas = Table_Proveedores.getValueAt(i, 6).toString();
            cont = Double.parseDouble(filas);

            sumtotal = sumtotal + cont;

        }
        this.jLabel4.setText(""+Math.rint(sumtotal * 100) / 100);
    }

    private void radiofechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiofechasActionPerformed

        this.radiofacturas.setSelected(false);
        this.rowtable = 1;
    }//GEN-LAST:event_radiofechasActionPerformed

    private void radiofacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiofacturasActionPerformed

        this.radiofechas.setSelected(false);
        this.rowtable = 2;
    }//GEN-LAST:event_radiofacturasActionPerformed

    private void materialButtomRectangle10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButtomRectangle10ActionPerformed
        if (this.rowtable == 1) {

            ventas.Opciones.listartodoProductosVendidos(getFechaInicio(), getFechaFin());
            sumar();
        }
        if (this.rowtable == 2) {
            ventas.Opciones.listartodoFacturasVendidas(getFechaInicio(), getFechaFin());
            sumar();
        }
    }//GEN-LAST:event_materialButtomRectangle10ActionPerformed

//    private void LoadDates() {
//        try {
//            Table_Proveedores.removeAll();
//            String[] titulos = {"id", "Codigo", "Nombre", "Descripcion", "Cantidad", "Precio compra", "Precio venta", "Precio x mayor"};
//            String[] registro = new String[9];
//            //Object o[] = null;
//            List<Producto> listproveedor = productoController.findProductoEntities();
//            modelo2 = new DefaultTableModel(null, titulos);
//
//            for (int i = 0; i < listproveedor.size(); i++) {
////                modelo2.addRow(o);
//                registro[0] = String.valueOf(listproveedor.get(i).getId());
//                registro[1] = listproveedor.get(i).getCodigo();
//                registro[2] = listproveedor.get(i).getNombre();
//                registro[3] = listproveedor.get(i).getDescripcion();
//                registro[4] = String.valueOf(listproveedor.get(i).getCantidad());
//                registro[5] = String.valueOf(listproveedor.get(i).getPcom());
//                registro[6] = String.valueOf(listproveedor.get(i).getPvp());
//                registro[7] = String.valueOf(listproveedor.get(i).getPmayor());
//                //registro[8] = listproveedor.get(i).getEmpresaProveedor();
//
//                //System.out.println(listLocal.get(i).getAdmin().toString());
//                modelo2.addRow(registro);
//            }
//            Table_Proveedores.setModel(modelo2);
//
//        } catch (Exception e) {
//            System.out.println(e.toString());
//        }
//
//    }
//    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Table_Proveedores;
    private com.toedter.calendar.JDateChooser dateend;
    private com.toedter.calendar.JDateChooser datestart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private materialdesing.MaterialButtomRectangle materialButtomRectangle10;
    private materialdesing.MaterialButtomRectangle materialButtomRectangle9;
    private javax.swing.JRadioButton radiofacturas;
    private javax.swing.JRadioButton radiofechas;
    // End of variables declaration//GEN-END:variables
}
