/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import ModelClass.TextFieldEven;
import alertas.principal.ErrorAlert;
import alertas.principal.SuccessAlert;
import alertas.principal.WarningAlertP;
import alertas.principal.WarningAlertP1;
import conexion.ConexionBD;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

import producto.ModalProductoM;
import producto.ModalProductoMInventario;
import producto.Sentencias;

import ventas.Opciones;
import ventas.ProductoReport;
import ventas.VentaReport;

/**
 *
 * @author RojeruSan
 */
public class PnlGestionFacturas extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    private String acction = "insert";

    private int agregar;
    TextFieldEven evento = new TextFieldEven();

    private String cod = "";
    private String nom = "";
    private String des = "";
    private double pc = 0;
    private double pv = 0;
    private double pm = 0;
    private int idprovedor;
    private int cantidad = 0;
    private int rowtable;

//    ProductoJpaController productoController = new ProductoJpaController();
//    ProveedorJpaController provedor = new ProveedorJpaController();
    DefaultTableModel modelo2;
    int ids;
    private TableRowSorter trsfiltro;

    public PnlGestionFacturas() {
        initComponents();
        ventas.Opciones.listarFacturasClientes("");
        this.rowtable = 1;

    }

    public static String fechaactual() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("YYYY/MM/dd");
        return formatofecha.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        btnAnular1 = new javax.swing.JButton();
        rbCanceladas = new javax.swing.JRadioButton();
        rbAnuladas = new javax.swing.JRadioButton();
        rbTodas = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Proveedores = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        lbsubtotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbtotal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbiva = new javax.swing.JLabel();
        lbnombre1 = new javax.swing.JLabel();
        lbcodigo = new javax.swing.JLabel();
        lbdni = new javax.swing.JLabel();
        lbdireccion = new javax.swing.JLabel();
        lbruc = new javax.swing.JLabel();
        btnAnular = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 97));
        jLabel1.setText("Facturas");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(80, 80, 97));
        jLabel5.setText("filtrar por");

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        btnAnular1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsaletr/icons8-find-and-replace-28.png"))); // NOI18N
        btnAnular1.setText("Cargar");
        btnAnular1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAnular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnular1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCanceladas);
        rbCanceladas.setText("Canceladas");
        rbCanceladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCanceladasActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbAnuladas);
        rbAnuladas.setText("Anuladas");
        rbAnuladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAnuladasActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbTodas);
        rbTodas.setText("Todas");
        rbTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCanceladas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbAnuladas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbTodas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnular1)
                .addGap(17, 17, 17))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAnular1)
                        .addComponent(rbCanceladas)
                        .addComponent(rbAnuladas)
                        .addComponent(rbTodas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table_Proveedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Table_Proveedores.setForeground(new java.awt.Color(51, 51, 51));
        Table_Proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° FACTURA", "CI CLIENTE", "SUBTOTAL", "IGV", "TOTAL", "FECHA", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Proveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Table_Proveedores.setDoubleBuffered(true);
        Table_Proveedores.setRowHeight(20);
        Table_Proveedores.setSelectionBackground(new java.awt.Color(0, 153, 255));
        Table_Proveedores.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Table_Proveedores);
        if (Table_Proveedores.getColumnModel().getColumnCount() > 0) {
            Table_Proveedores.getColumnModel().getColumn(2).setPreferredWidth(12);
            Table_Proveedores.getColumnModel().getColumn(3).setPreferredWidth(12);
            Table_Proveedores.getColumnModel().getColumn(4).setPreferredWidth(12);
            Table_Proveedores.getColumnModel().getColumn(5).setPreferredWidth(15);
            Table_Proveedores.getColumnModel().getColumn(6).setPreferredWidth(12);
        }

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 18, 970, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("total");
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, -1, 30));

        lbsubtotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbsubtotal.setText("0");
        jPanel8.add(lbsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 120, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Subtotal");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, -1, 30));

        lbtotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbtotal.setText("0");
        jPanel8.add(lbtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 510, 120, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("iva");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, -1, 30));

        lbiva.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbiva.setText("0");
        jPanel8.add(lbiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 120, 30));

        lbnombre1.setForeground(new java.awt.Color(255, 255, 255));
        lbnombre1.setText("jLabel3");
        jPanel8.add(lbnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        lbcodigo.setForeground(new java.awt.Color(255, 255, 255));
        lbcodigo.setText("jLabel3");
        jPanel8.add(lbcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        lbdni.setForeground(new java.awt.Color(255, 255, 255));
        lbdni.setText("jLabel3");
        jPanel8.add(lbdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        lbdireccion.setForeground(new java.awt.Color(255, 255, 255));
        lbdireccion.setText("jLabel3");
        jPanel8.add(lbdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        lbruc.setForeground(new java.awt.Color(255, 255, 255));
        lbruc.setText("jLabel3");
        jPanel8.add(lbruc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        btnAnular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsaletr/icons8-delete-document-28.png"))); // NOI18N
        btnAnular.setText("Anular");
        btnAnular.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularActionPerformed(evt);
            }
        });
        jPanel8.add(btnAnular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 110, 40));

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsaletr/icons8-print-28.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        jPanel8.add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 110, 40));

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsaletr/icons8-show-property-28.png"))); // NOI18N
        btnVer.setText("Revisar");
        btnVer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        jPanel8.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void sumar() {
        double sumtotal = 0;
        double cont;
        String filas;
        double iva = 0.14;
        double igv = 0;
        double subtotal = 0;

        for (int i = 0; i < Table_Proveedores.getRowCount(); i++) {
            filas = Table_Proveedores.getValueAt(i, 4).toString();
            cont = Double.parseDouble(filas);

            sumtotal = sumtotal + cont;

        }
        igv = sumtotal * iva;
        subtotal = sumtotal - igv;

        this.lbsubtotal.setText("" + Math.rint(subtotal * 100) / 100);
        this.lbiva.setText("" + Math.rint(igv * 100) / 100);
        this.lbtotal.setText("" + Math.rint(sumtotal * 100) / 100);

    }

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased

        if (rbTodas.isSelected()) {
            ventas.Opciones.listarFacturasClientes(this.txtbuscar.getText());
        }
        if (rbAnuladas.isSelected()) {
            ventas.Opciones.listarFacturasClientesAnuladas(this.txtbuscar.getText());
        }
        if (rbCanceladas.isSelected()) {
            ventas.Opciones.listarFacturasClientesCanceladas(this.txtbuscar.getText());
        }


    }//GEN-LAST:event_txtbuscarKeyReleased

    private void btnAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularActionPerformed
        String capcod = "", capcan = "", numfactura = "";
        int contador = 0;

        for (int i = 0; i < Table_Proveedores.getRowCount(); i++) {
            System.out.println(" codigo : " + Table_Proveedores.getValueAt(i, 1).toString() + "   cantidad: " + Table_Proveedores.getValueAt(i, 3).toString());
            capcod = Table_Proveedores.getValueAt(i, 1).toString();
            capcan = Table_Proveedores.getValueAt(i, 3).toString();
            numfactura = Table_Proveedores.getValueAt(i, 0).toString();
            Opciones.restablcerstock(capcod, capcan);
            contador++;

        }

        ventas.Opciones.anularFactura(numfactura);

        if (contador == this.Table_Proveedores.getRowCount()) {

            //producto.Opciones.finalizarTransaccion();
            SuccessAlert sa = new SuccessAlert(new JFrame(), true);
            sa.titulo.setText("¡HECHO!");
            sa.msj.setText("VENTA REALIZADA CON");
            sa.msj1.setText("ÉXITO");
            sa.setVisible(true);
            paneles.PnlGestionFacturas.Table_Proveedores.removeAll();
            String[] titulos = {"N° FACTURA", "CI CLIENTE", "SUBTOTAL", "IGV", "TOTAL", "FECHA", "ESTADO"};

            DefaultTableModel modelo;
            modelo = new DefaultTableModel(null, titulos);
            Table_Proveedores.setModel(modelo);

            ventas.Opciones.listarFacturasClientes("");
        }
    }//GEN-LAST:event_btnAnularActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        try {
            // TODO add your handling code here:
            List<ProductoReport> listaProductos = new ArrayList<ProductoReport>();
            int filas = Table_Proveedores.getRowCount();
            for (int i = 0; i < filas; i++) {
                ProductoReport p = new ProductoReport(Table_Proveedores.getValueAt(i, 1).toString(), Table_Proveedores.getValueAt(i, 2).toString(), Table_Proveedores.getValueAt(i, 3).toString(), Table_Proveedores.getValueAt(i, 4).toString(), Table_Proveedores.getValueAt(i, 5).toString());
                listaProductos.add(p);
            }

            JasperReport reporte = (JasperReport) JRLoader.loadObject("ImprFac.jasper");

            Map<String, String> parametros = new HashMap<String, String>();
            parametros.put("nunfac", Table_Proveedores.getValueAt(0, 0).toString());
            parametros.put("nomape", lbnombre1.getText());
            parametros.put("codigo", lbcodigo.getText());
            parametros.put("dni", lbdni.getText());
            parametros.put("direccion", lbdireccion.getText());
            parametros.put("ruc", lbruc.getText());
            parametros.put("fecha", fechaactual());
            parametros.put("subtotal", lbsubtotal.getText());
            parametros.put("iva", lbiva.getText());
            parametros.put("total", lbtotal.getText());

            JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, parametros, new JRBeanCollectionDataSource(listaProductos));
            JasperViewer.viewReport(jasperPrint, false);
            JRExporter exporter = new JRPdfExporter();
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, jasperPrint);
            exporter.setParameter(JRExporterParameter.OUTPUT_FILE, new java.io.File("reportesproductos.pdf"));
            exporter.exportReport();
        } catch (JRException ex) {
            Logger.getLogger(PnlVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed

        int fila = Table_Proveedores.getSelectedRow();
        if (fila >= 0) {
            String ruccli = Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 1).toString();
            System.out.println("ruc encontrado " + ruccli);
            String datos[] = new String[8];
            datos = clientes.Opciones.listarClienteVenta(ruccli);

            lbcodigo.setText(datos[0]);
            lbdni.setText(datos[1]);
            lbnombre1.setText(datos[2] + " " + datos[3]);
            lbdireccion.setText(datos[4]);
            lbruc.setText(datos[6]);

            ventas.Opciones.listartodoFacturasRegistro(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 0).toString());

            sumar();
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un fila");
        }

    }//GEN-LAST:event_btnVerActionPerformed

    public void encabezado() {
        paneles.PnlGestionFacturas.Table_Proveedores.removeAll();
        String[] titulos = {"N° FACTURA", "CI CLIENTE", "SUBTOTAL", "IGV", "TOTAL", "FECHA", "ESTADO"};

        DefaultTableModel modelo;
        modelo = new DefaultTableModel(null, titulos);
        Table_Proveedores.setModel(modelo);
    }

    private void btnAnular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnular1ActionPerformed
        encabezado();

        ventas.Opciones.listarFacturasClientes("");
    }//GEN-LAST:event_btnAnular1ActionPerformed

    private void rbCanceladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCanceladasActionPerformed
        encabezado();
        ventas.Opciones.listarFacturasClientesCanceladas("");
    }//GEN-LAST:event_rbCanceladasActionPerformed

    private void rbAnuladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAnuladasActionPerformed
        encabezado();
        ventas.Opciones.listarFacturasClientesAnuladas("");
    }//GEN-LAST:event_rbAnuladasActionPerformed

    private void rbTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodasActionPerformed
        encabezado();
        ventas.Opciones.listarFacturasClientes("");
    }//GEN-LAST:event_rbTodasActionPerformed

//    private void LoadDates() {
//        try {
//            Table_Proveedores.removeAll();
//            String[] titulos = {"id", "Codigo", "Nombre", "Descripcion", "Cantidad", "Precio compra", "Precio venta", "Precio x mayor"};
//            String[] registro = new String[9];
//            //Object o[] = null;
//            List<Producto> listproveedor = productoController.findProductoEntities();
//            modelo2 = new DefaultTableModel(null, titulos);
//
//            for (int i = 0; i < listproveedor.size(); i++) {
////                modelo2.addRow(o);
//                registro[0] = String.valueOf(listproveedor.get(i).getId());
//                registro[1] = listproveedor.get(i).getCodigo();
//                registro[2] = listproveedor.get(i).getNombre();
//                registro[3] = listproveedor.get(i).getDescripcion();
//                registro[4] = String.valueOf(listproveedor.get(i).getCantidad());
//                registro[5] = String.valueOf(listproveedor.get(i).getPcom());
//                registro[6] = String.valueOf(listproveedor.get(i).getPvp());
//                registro[7] = String.valueOf(listproveedor.get(i).getPmayor());
//                //registro[8] = listproveedor.get(i).getEmpresaProveedor();
//
//                //System.out.println(listLocal.get(i).getAdmin().toString());
//                modelo2.addRow(registro);
//            }
//            Table_Proveedores.setModel(modelo2);
//
//        } catch (Exception e) {
//            System.out.println(e.toString());
//        }
//
//    }
//    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Table_Proveedores;
    private javax.swing.JButton btnAnular;
    private javax.swing.JButton btnAnular1;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnVer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbcodigo;
    private javax.swing.JLabel lbdireccion;
    private javax.swing.JLabel lbdni;
    private javax.swing.JLabel lbiva;
    private javax.swing.JLabel lbnombre1;
    private javax.swing.JLabel lbruc;
    private javax.swing.JLabel lbsubtotal;
    private javax.swing.JLabel lbtotal;
    private javax.swing.JRadioButton rbAnuladas;
    private javax.swing.JRadioButton rbCanceladas;
    private javax.swing.JRadioButton rbTodas;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
