/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import ModelClass.TextFieldEven;
import alertas.principal.ErrorAlert;
import alertas.principal.SuccessAlert;
import alertas.principal.WarningAlertP;
import alertas.principal.WarningAlertP1;
import conexion.ConexionBD;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

import producto.ModalProductoM;
import producto.ModalProductoMInventario;
import producto.Sentencias;

import ventas.Opciones;

/**
 *
 * @author RojeruSan
 */
public class PnlInventario extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    private String acction = "insert";

    private int agregar;
    TextFieldEven evento = new TextFieldEven();

    private String cod = "";
    private String nom = "";
    private String des = "";
    private double pc = 0;
    private double pv = 0;
    private double pm = 0;
    private int idprovedor;
    private int cantidad = 0;
    private int rowtable;

//    ProductoJpaController productoController = new ProductoJpaController();
//    ProveedorJpaController provedor = new ProveedorJpaController();
    DefaultTableModel modelo2;
    int ids;
    private TableRowSorter trsfiltro;

    public PnlInventario() {
        initComponents();
        producto.Opciones.listartodo();
        this.rowtable = 1;
        this.radiobarras.setSelected(true);

    }

    public void filtro(int rowtable) {
        trsfiltro.setRowFilter(RowFilter.regexFilter(TextField_BuscarProveedor.getText(), rowtable));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        TextField_BuscarProveedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        radiobarras = new javax.swing.JRadioButton();
        radionombre = new javax.swing.JRadioButton();
        radiocategoria = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Proveedores = new javax.swing.JTable();
        materialButtomRectangle1 = new materialdesing.MaterialButtomRectangle();
        materialButtomRectangle6 = new materialdesing.MaterialButtomRectangle();
        materialButtomRectangle7 = new materialdesing.MaterialButtomRectangle();
        materialButtomRectangle8 = new materialdesing.MaterialButtomRectangle();
        materialButtomRectangle9 = new materialdesing.MaterialButtomRectangle();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TextField_BuscarProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_BuscarProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_BuscarProveedorKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 97));
        jLabel1.setText("Inventario de productos");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(80, 80, 97));
        jLabel5.setText("filtrar por");

        radiobarras.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        radiobarras.setForeground(new java.awt.Color(102, 102, 102));
        radiobarras.setText("c. barras");
        radiobarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobarrasActionPerformed(evt);
            }
        });

        radionombre.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        radionombre.setForeground(new java.awt.Color(102, 102, 102));
        radionombre.setText("nombre");
        radionombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radionombreActionPerformed(evt);
            }
        });

        radiocategoria.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        radiocategoria.setForeground(new java.awt.Color(102, 102, 102));
        radiocategoria.setText("categoría");
        radiocategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiocategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radiobarras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radionombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radiocategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextField_BuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(radionombre)
                        .addComponent(radiobarras)
                        .addComponent(radiocategoria))
                    .addComponent(TextField_BuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table_Proveedores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Table_Proveedores.setForeground(new java.awt.Color(51, 51, 51));
        Table_Proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Table_Proveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Table_Proveedores.setDoubleBuffered(true);
        Table_Proveedores.setRowHeight(20);
        Table_Proveedores.setSelectionBackground(new java.awt.Color(0, 153, 255));
        Table_Proveedores.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Table_Proveedores);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 81, 1004, 367));

        materialButtomRectangle1.setBackground(new java.awt.Color(0, 204, 102));
        materialButtomRectangle1.setForeground(new java.awt.Color(255, 255, 255));
        materialButtomRectangle1.setText("Nuevo ");
        materialButtomRectangle1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        materialButtomRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButtomRectangle1ActionPerformed(evt);
            }
        });
        jPanel8.add(materialButtomRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 93, 47));

        materialButtomRectangle6.setBackground(new java.awt.Color(80, 172, 224));
        materialButtomRectangle6.setForeground(new java.awt.Color(255, 255, 255));
        materialButtomRectangle6.setText("Editar");
        materialButtomRectangle6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        materialButtomRectangle6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButtomRectangle6ActionPerformed(evt);
            }
        });
        jPanel8.add(materialButtomRectangle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 13, 92, 50));

        materialButtomRectangle7.setBackground(new java.awt.Color(255, 153, 51));
        materialButtomRectangle7.setForeground(new java.awt.Color(255, 255, 255));
        materialButtomRectangle7.setText("Eliminar");
        materialButtomRectangle7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        materialButtomRectangle7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButtomRectangle7ActionPerformed(evt);
            }
        });
        jPanel8.add(materialButtomRectangle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 13, 91, 50));

        materialButtomRectangle8.setBackground(new java.awt.Color(255, 102, 102));
        materialButtomRectangle8.setForeground(new java.awt.Color(255, 255, 255));
        materialButtomRectangle8.setText("Eliminar todo");
        materialButtomRectangle8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        materialButtomRectangle8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButtomRectangle8ActionPerformed(evt);
            }
        });
        jPanel8.add(materialButtomRectangle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 13, 131, 50));

        materialButtomRectangle9.setBackground(new java.awt.Color(80, 172, 224));
        materialButtomRectangle9.setForeground(new java.awt.Color(255, 255, 255));
        materialButtomRectangle9.setText("imprimir");
        materialButtomRectangle9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        materialButtomRectangle9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialButtomRectangle9ActionPerformed(evt);
            }
        });
        jPanel8.add(materialButtomRectangle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 13, 131, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_BuscarProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_BuscarProveedorKeyTyped
        TextField_BuscarProveedor.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (TextField_BuscarProveedor.getText().toUpperCase());
                TextField_BuscarProveedor.setText(cadena);
                repaint();
                filtro(rowtable);
            }
        });
        trsfiltro = new TableRowSorter(Table_Proveedores.getModel());
        Table_Proveedores.setRowSorter(trsfiltro);
    }//GEN-LAST:event_TextField_BuscarProveedorKeyTyped

    private void materialButtomRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButtomRectangle1ActionPerformed
        ModalProductoMInventario mp = new ModalProductoMInventario(new JFrame(), true);
        mp.titulo.setText("REGISTRAR");

        mp.setVisible(true);
    }//GEN-LAST:event_materialButtomRectangle1ActionPerformed

    private void materialButtomRectangle6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButtomRectangle6ActionPerformed
        if (this.Table_Proveedores.getRowCount() < 1) {
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("LA TABLA ESTA VACÍA");
            er.msj1.setText("");
            er.setVisible(true);
        } else {
            if (this.Table_Proveedores.getSelectedRowCount() < 1) {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("OOPS...");
                er.msj.setText("SELECCIONA UN");
                er.msj1.setText("REGISTRO");
                er.setVisible(true);
            } else {

                int fila = this.Table_Proveedores.getSelectedRow();

                ModalProductoMInventario mp = new ModalProductoMInventario(new JFrame(), true);
                mp.TextField_CODPRODUCTO.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 1).toString());
                mp.TextField_nomPRODUCTO.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 2).toString());
                mp.TextField_desPRODUCTO.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 3).toString());
                mp.TextField_canPRODUCTO.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 5).toString());
                mp.TextField_pcPRODUCTO.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 6).toString());
                mp.TextField_pvPRODUCTO.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 7).toString());
                mp.TextField_pmPRODUCTO.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 7).toString());
                mp.idmodal.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 0).toString());

                mp.titulo.setText("MODIFICAR");

                mp.setVisible(true);
            }
        }
    }//GEN-LAST:event_materialButtomRectangle6ActionPerformed

    private void materialButtomRectangle7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButtomRectangle7ActionPerformed
        if (this.Table_Proveedores.getRowCount() < 1) {
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("LA TABLA ESTA VACÍA");
            er.msj1.setText("");
            er.setVisible(true);
        } else {
            if (this.Table_Proveedores.getSelectedRowCount() < 1) {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("OOPS...");
                er.msj.setText("SELECCIONA UN");
                er.msj1.setText("REGISTRO");
                er.setVisible(true);
            } else {
                int fila = this.Table_Proveedores.getSelectedRow();
                WarningAlertP wa = new WarningAlertP(new JFrame(), true);
                wa.id.setText(this.Table_Proveedores.getValueAt(fila, 0).toString());
                wa.titulo.setText("¿ESTAS SEGURO?");
                wa.msj.setText("SE BORRARA PERMANENTEMENTE");
                wa.msj1.setText("");
                wa.setVisible(true);
            }
        }
    }//GEN-LAST:event_materialButtomRectangle7ActionPerformed

    private void materialButtomRectangle8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButtomRectangle8ActionPerformed
        if (this.Table_Proveedores.getRowCount() < 1) {
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("LA TABLA ESTA VACÍA");
            er.msj1.setText("");
            er.setVisible(true);
        } else {
            WarningAlertP1 wa = new WarningAlertP1(new JFrame(), true);
            wa.titulo.setText("¿ESTAS SEGURO?");
            wa.msj.setText("SE BORRARAN TODOS LOS");
            wa.msj1.setText("REGISTROS PERMANENTEMENTE");
            wa.setVisible(true);
        }
    }//GEN-LAST:event_materialButtomRectangle8ActionPerformed

    private void materialButtomRectangle9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialButtomRectangle9ActionPerformed
        try {
            ConexionBD cc = new ConexionBD();
            JasperReport reporte = (JasperReport) JRLoader.loadObject("reportesProductos.jasper");

            JasperPrint j = JasperFillManager.fillReport(reporte, null, cc.conexion());
            JasperViewer jv = new JasperViewer(j, false);
            jv.setTitle("Reporte Clientes Registrados");
            jv.setVisible(true);

        } catch (Exception e) {
            System.out.printf(e.getMessage());
        }
    }//GEN-LAST:event_materialButtomRectangle9ActionPerformed

    private void radiobarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobarrasActionPerformed
        this.radiocategoria.setSelected(false);
        this.radionombre.setSelected(false);
        this.rowtable = 1;
    }//GEN-LAST:event_radiobarrasActionPerformed

    private void radionombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radionombreActionPerformed
        this.radiocategoria.setSelected(false);
        this.radiobarras.setSelected(false);
        this.rowtable = 2;
    }//GEN-LAST:event_radionombreActionPerformed

    private void radiocategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiocategoriaActionPerformed
        this.radionombre.setSelected(false);
        this.radiobarras.setSelected(false);
        this.rowtable = 4;
    }//GEN-LAST:event_radiocategoriaActionPerformed

//    private void LoadDates() {
//        try {
//            Table_Proveedores.removeAll();
//            String[] titulos = {"id", "Codigo", "Nombre", "Descripcion", "Cantidad", "Precio compra", "Precio venta", "Precio x mayor"};
//            String[] registro = new String[9];
//            //Object o[] = null;
//            List<Producto> listproveedor = productoController.findProductoEntities();
//            modelo2 = new DefaultTableModel(null, titulos);
//
//            for (int i = 0; i < listproveedor.size(); i++) {
////                modelo2.addRow(o);
//                registro[0] = String.valueOf(listproveedor.get(i).getId());
//                registro[1] = listproveedor.get(i).getCodigo();
//                registro[2] = listproveedor.get(i).getNombre();
//                registro[3] = listproveedor.get(i).getDescripcion();
//                registro[4] = String.valueOf(listproveedor.get(i).getCantidad());
//                registro[5] = String.valueOf(listproveedor.get(i).getPcom());
//                registro[6] = String.valueOf(listproveedor.get(i).getPvp());
//                registro[7] = String.valueOf(listproveedor.get(i).getPmayor());
//                //registro[8] = listproveedor.get(i).getEmpresaProveedor();
//
//                //System.out.println(listLocal.get(i).getAdmin().toString());
//                modelo2.addRow(registro);
//            }
//            Table_Proveedores.setModel(modelo2);
//
//        } catch (Exception e) {
//            System.out.println(e.toString());
//        }
//
//    }
//    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Table_Proveedores;
    private javax.swing.JTextField TextField_BuscarProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private materialdesing.MaterialButtomRectangle materialButtomRectangle1;
    private materialdesing.MaterialButtomRectangle materialButtomRectangle6;
    private materialdesing.MaterialButtomRectangle materialButtomRectangle7;
    private materialdesing.MaterialButtomRectangle materialButtomRectangle8;
    private materialdesing.MaterialButtomRectangle materialButtomRectangle9;
    private javax.swing.JRadioButton radiobarras;
    private javax.swing.JRadioButton radiocategoria;
    private javax.swing.JRadioButton radionombre;
    // End of variables declaration//GEN-END:variables
}
