/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import ModelClass.TextFieldEven;
import controllers.AdministradorJpaController;
import controllers.Controlador;
import controllers.LocalJpaController;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Array;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import models.Administrador;
import models.Local;

/**
 *
 * @author RojeruSan
 */
public class PnlLocal extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    private String acction = "insert", Id = "", dia, mes, anio, funcionCatDpt, idCat, dpt;
    private int pageSize, tab, maxReg, pageCount, currentPage, numReg;
    private int startRec, endRec;
    private String ruc = "";
    private String nombre = "";
    private String provincia = "";
    private String canton = "";
    private String parroquia = "";
    private String calle = "";
    private String telefono = "";
    private int idAdmin;
    TextFieldEven evento = new TextFieldEven();
    
    DefaultTableModel modelo2;
    LocalJpaController localController = new LocalJpaController();
    AdministradorJpaController adminController = new AdministradorJpaController();
    Controlador control = new Controlador();
    int ids;
    private TableRowSorter trsfiltro;
    List<Administrador> add;
    private Administrador objeto;
    
    public PnlLocal() {
        initComponents();
        LoadDates();
        rSComboAdmin.removeAllItems();
        cargarAdmin();
        this.Button_Guardar.setEnabled(true);
        this.Button_Editar.setEnabled(false);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Button_Limpiar = new javax.swing.JButton();
        Button_Guardar = new javax.swing.JButton();
        Label_rucEmpresa = new javax.swing.JLabel();
        TextField_rucEmpresa = new javax.swing.JTextField();
        Label_parroquiaEmpresa = new javax.swing.JLabel();
        Label_NombreEmpresa = new javax.swing.JLabel();
        TextField_NombreEmpresa = new javax.swing.JTextField();
        Label_ProvinciaEmpresa = new javax.swing.JLabel();
        TextField_Provincia = new javax.swing.JTextField();
        Label_CantonEmpresa = new javax.swing.JLabel();
        TextField_CantonEmpresa = new javax.swing.JTextField();
        Label_TelefonoEmpresa = new javax.swing.JLabel();
        TextField_TelefonoEmpresa = new javax.swing.JTextField();
        Label_calleEmpresa = new javax.swing.JLabel();
        TextField_CalleEmpresa = new javax.swing.JTextField();
        Button_Editar = new javax.swing.JButton();
        TextField_ParroquiaEmpresa = new javax.swing.JTextField();
        rSComboAdmin = new rojerusan.RSComboMetro();
        Label_idAdminEmpresa = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextField_BuscarCliente = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Locales =   Table_Locales = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        Button_Seleccionar = new javax.swing.JButton();
        Button_Eliminar = new javax.swing.JButton();
        Button_Cancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(80, 80, 97));
        jLabel2.setText("Datos del Local");
        jLabel2.setToolTipText("");

        Button_Limpiar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png"))); // NOI18N
        Button_Limpiar.setText("Limpiar");
        Button_Limpiar.setBorder(null);
        Button_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LimpiarActionPerformed(evt);
            }
        });

        Button_Guardar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Agregar.png"))); // NOI18N
        Button_Guardar.setText("Guardar");
        Button_Guardar.setBorder(null);
        Button_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GuardarActionPerformed(evt);
            }
        });

        Label_rucEmpresa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_rucEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        Label_rucEmpresa.setText("Ruc");
        Label_rucEmpresa.setToolTipText("");

        TextField_rucEmpresa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_rucEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_rucEmpresaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_rucEmpresaKeyTyped(evt);
            }
        });

        Label_parroquiaEmpresa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_parroquiaEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        Label_parroquiaEmpresa.setText("Parroquia");
        Label_parroquiaEmpresa.setToolTipText("");

        Label_NombreEmpresa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_NombreEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        Label_NombreEmpresa.setText("Nombre ");
        Label_NombreEmpresa.setToolTipText("");

        TextField_NombreEmpresa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_NombreEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_NombreEmpresaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_NombreEmpresaKeyTyped(evt);
            }
        });

        Label_ProvinciaEmpresa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_ProvinciaEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        Label_ProvinciaEmpresa.setText("Provincia");

        TextField_Provincia.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_Provincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_ProvinciaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_ProvinciaKeyTyped(evt);
            }
        });

        Label_CantonEmpresa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_CantonEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        Label_CantonEmpresa.setText("Cantón");
        Label_CantonEmpresa.setToolTipText("");

        TextField_CantonEmpresa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_CantonEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_CantonEmpresaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_CantonEmpresaKeyTyped(evt);
            }
        });

        Label_TelefonoEmpresa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_TelefonoEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        Label_TelefonoEmpresa.setText("Teléfono");

        TextField_TelefonoEmpresa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_TelefonoEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_TelefonoEmpresaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_TelefonoEmpresaKeyTyped(evt);
            }
        });

        Label_calleEmpresa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_calleEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        Label_calleEmpresa.setText("Calle");

        TextField_CalleEmpresa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_CalleEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_CalleEmpresaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_CalleEmpresaKeyTyped(evt);
            }
        });

        Button_Editar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar.png"))); // NOI18N
        Button_Editar.setText("Editar");
        Button_Editar.setBorder(null);
        Button_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EditarActionPerformed(evt);
            }
        });

        TextField_ParroquiaEmpresa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_ParroquiaEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_ParroquiaEmpresaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_ParroquiaEmpresaKeyTyped(evt);
            }
        });

        rSComboAdmin.setBackground(new java.awt.Color(106, 111, 124));
        rSComboAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        rSComboAdmin.setForeground(new java.awt.Color(51, 51, 51));
        rSComboAdmin.setColorArrow(new java.awt.Color(102, 102, 102));
        rSComboAdmin.setColorBorde(new java.awt.Color(153, 153, 153));
        rSComboAdmin.setColorFondo(new java.awt.Color(204, 204, 204));

        Label_idAdminEmpresa.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_idAdminEmpresa.setForeground(new java.awt.Color(102, 102, 102));
        Label_idAdminEmpresa.setText("Administrador");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Button_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextField_NombreEmpresa)
                            .addComponent(TextField_Provincia)
                            .addComponent(TextField_CantonEmpresa)
                            .addComponent(TextField_TelefonoEmpresa)
                            .addComponent(TextField_CalleEmpresa)
                            .addComponent(TextField_rucEmpresa)
                            .addComponent(jLabel2)
                            .addComponent(TextField_ParroquiaEmpresa)
                            .addComponent(Label_rucEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_NombreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_ProvinciaEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_CantonEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_parroquiaEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_calleEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_TelefonoEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSComboAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label_idAdminEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_idAdminEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSComboAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_rucEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_rucEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_NombreEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_NombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_ProvinciaEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_Provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Label_CantonEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_CantonEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_parroquiaEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_ParroquiaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_calleEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_CalleEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_TelefonoEmpresa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_TelefonoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 97));
        jLabel1.setText("Locales");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(80, 80, 97));
        jLabel5.setText("Buscar");

        TextField_BuscarCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_BuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_BuscarClienteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(156, 156, 156)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(TextField_BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(TextField_BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Table_Locales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Table_Locales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table_Locales.setRowHeight(20);
        Table_Locales.setSelectionBackground(new java.awt.Color(102, 204, 255));
        jScrollPane2.setViewportView(Table_Locales);

        Button_Seleccionar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Seleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Left.png"))); // NOI18N
        Button_Seleccionar.setText("Seleccionar");
        Button_Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SeleccionarActionPerformed(evt);
            }
        });

        Button_Eliminar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Right.png"))); // NOI18N
        Button_Eliminar.setText("Eliminar");
        Button_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EliminarActionPerformed(evt);
            }
        });

        Button_Cancelar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Left-12.png"))); // NOI18N
        Button_Cancelar.setText("Cancelar");
        Button_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Seleccionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Eliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Button_Seleccionar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Button_Cancelar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void cargarAdmin() {
        List<Administrador> listAdmin = adminController.findAdministradorEntities();
        this.add = listAdmin;
        rSComboAdmin.removeAllItems();
        for (Administrador admin : listAdmin) {
            rSComboAdmin.addItem(admin.getNombres());
        }
    }
    
    public void buscar(String nombre) {
        System.out.println(nombre);
        for (Administrador admin : this.add) {
            if (admin.getNombres().equalsIgnoreCase(nombre)) {
                idAdmin = admin.getId();
                objeto = admin;
//                System.out.println(objeto.toString());
            }
            //rSComboAdmin.addItem(admin.getNombres());
        }
    }
    
    public void filtro() {
        trsfiltro.setRowFilter(RowFilter.regexFilter(TextField_BuscarCliente.getText(), 2));
    }
    
    private void LoadDates() {
        try {
            Table_Locales.removeAll();
            String[] titulos = {"id", "Ruc", "Nombre", "Provincia", "Cantón", "Parroquia", "Calle", "Teléfono", "idAdmin"};
            String[] registro = new String[9];
            //Object o[] = null;
            List<Local> listLocal = localController.findLocalEntities();
            modelo2 = new DefaultTableModel(null, titulos);
            
            for (int i = 0; i < listLocal.size(); i++) {
//                modelo2.addRow(o);
                registro[0] = String.valueOf(listLocal.get(i).getId());
                registro[1] = listLocal.get(i).getRuc();
                registro[2] = listLocal.get(i).getNombre();
                registro[3] = listLocal.get(i).getProvincia();
                registro[4] = listLocal.get(i).getCanton();
                registro[5] = listLocal.get(i).getParroquia();
                registro[6] = listLocal.get(i).getCalle();
                registro[7] = listLocal.get(i).getTelefono();
                registro[8] = String.valueOf(listLocal.get(i).getAdmin().getId());
                //System.out.println(listLocal.get(i).getAdmin().toString());
                modelo2.addRow(registro);
            }
            Table_Locales.setModel(modelo2);
            
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        
    }
    private void Button_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GuardarActionPerformed
        if (validar() == 7) {
            save();
            
            JOptionPane.showMessageDialog(null, "Guardado exitosamente");
            limpiar();
            this.ruc = "";
            this.nombre = "";
            this.provincia = "";
            this.canton = "";
            this.parroquia = "";
            this.calle = "";
            this.telefono = "";
            this.idAdmin = 0;
            
        } else {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        }

    }//GEN-LAST:event_Button_GuardarActionPerformed

    private void Button_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LimpiarActionPerformed
        this.Button_Guardar.setEnabled(true);
        this.Button_Editar.setEnabled(false);
        limpiar();
    }//GEN-LAST:event_Button_LimpiarActionPerformed

    private void TextField_rucEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_rucEmpresaKeyReleased
        if (TextField_rucEmpresa.getText().equals("")) {
            Label_rucEmpresa.setForeground(new Color(102, 102, 102));
        } else {
            Label_rucEmpresa.setText("Ruc");
            Label_rucEmpresa.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_rucEmpresaKeyReleased

    private void TextField_rucEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_rucEmpresaKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_rucEmpresaKeyTyped

    private void TextField_NombreEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_NombreEmpresaKeyReleased
        if (TextField_NombreEmpresa.getText().equals("")) {
            Label_NombreEmpresa.setForeground(new Color(102, 102, 102));
        } else {
            Label_NombreEmpresa.setText("Nombre");
            Label_NombreEmpresa.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_NombreEmpresaKeyReleased

    private void TextField_NombreEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_NombreEmpresaKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_NombreEmpresaKeyTyped

    private void TextField_ProvinciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ProvinciaKeyReleased
        if (TextField_Provincia.getText().equals("")) {
            Label_ProvinciaEmpresa.setForeground(new Color(102, 102, 102));
        } else {
            Label_ProvinciaEmpresa.setText("Provincia");
            Label_ProvinciaEmpresa.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_ProvinciaKeyReleased

    private void TextField_ProvinciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ProvinciaKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_ProvinciaKeyTyped

    private void TextField_CantonEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CantonEmpresaKeyReleased
        if (TextField_CantonEmpresa.getText().equals("")) {
            Label_CantonEmpresa.setForeground(new Color(102, 102, 102));
        } else {
            Label_CantonEmpresa.setText("Cantón");
            Label_CantonEmpresa.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_CantonEmpresaKeyReleased

    private void TextField_CantonEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CantonEmpresaKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_CantonEmpresaKeyTyped

    private void TextField_TelefonoEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_TelefonoEmpresaKeyReleased
        if (TextField_TelefonoEmpresa.getText().equals("")) {
            Label_TelefonoEmpresa.setForeground(new Color(102, 102, 102));
        } else {
            Label_TelefonoEmpresa.setText("Teléfono");
            Label_TelefonoEmpresa.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_TelefonoEmpresaKeyReleased

    private void TextField_TelefonoEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_TelefonoEmpresaKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_TelefonoEmpresaKeyTyped

    private void TextField_CalleEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CalleEmpresaKeyReleased
        if (TextField_CalleEmpresa.getText().equals("")) {
            Label_calleEmpresa.setForeground(new Color(102, 102, 102));
        } else {
            Label_calleEmpresa.setText("Calle");
            Label_calleEmpresa.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_CalleEmpresaKeyReleased

    private void TextField_CalleEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CalleEmpresaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_CalleEmpresaKeyTyped

    private void TextField_ParroquiaEmpresaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ParroquiaEmpresaKeyReleased
        if (TextField_ParroquiaEmpresa.getText().equals("")) {
            Label_parroquiaEmpresa.setForeground(new Color(102, 102, 102));
        } else {
            Label_parroquiaEmpresa.setText("Parroquia");
            Label_parroquiaEmpresa.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_ParroquiaEmpresaKeyReleased

    private void TextField_ParroquiaEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ParroquiaEmpresaKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_ParroquiaEmpresaKeyTyped

    private void Button_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EditarActionPerformed
       
        try {
            if (validar() == 7) {
                System.out.println("id recuperado    :  " + ids);
                Local local = control.buscarLocal(ids);
//                System.out.println("Local recuperado    :  " + local.toString());
                
                local.setRuc(this.ruc);
                
                local.setNombre(this.nombre);
                
                local.setProvincia(this.provincia);
                
                local.setCanton(this.canton);
                
                local.setParroquia(this.parroquia);
                
                local.setCalle(this.calle);
                
                local.setTelefono(this.telefono);
                System.out.println("llego aqui   :  ");
//                System.out.println("onjeto admin  :  " + objeto.toString());
                local.setAdmin(objeto);
                control.update(local);
                //localController.edit(local);
                limpiar();
                this.ruc = "";
                this.nombre = "";
                this.provincia = "";
                this.canton = "";
                this.parroquia = "";
                this.calle = "";
                this.telefono = "";
                LoadDates();
                JOptionPane.showMessageDialog(null, "Actualizado exitosamente");
                
            } else {
                JOptionPane.showMessageDialog(null, "Complete todos los campos");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Button_EditarActionPerformed

    private void Button_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelarActionPerformed
        limpiar();
        this.Button_Guardar.setEnabled(true);
        this.Button_Editar.setEnabled(false);
    }//GEN-LAST:event_Button_CancelarActionPerformed

    private void Button_SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SeleccionarActionPerformed
        this.Button_Guardar.setEnabled(false);
        this.Button_Editar.setEnabled(true);
        this.ids = Integer.parseInt((String) Table_Locales.getValueAt(Table_Locales.getSelectedRow(), 0));
        
        TextField_rucEmpresa.setText(Table_Locales.getValueAt(Table_Locales.getSelectedRow(), 1).toString());
        TextField_NombreEmpresa.setText(Table_Locales.getValueAt(Table_Locales.getSelectedRow(), 2).toString());
        TextField_Provincia.setText(Table_Locales.getValueAt(Table_Locales.getSelectedRow(), 3).toString());
        TextField_CantonEmpresa.setText(Table_Locales.getValueAt(Table_Locales.getSelectedRow(), 4).toString());
        TextField_ParroquiaEmpresa.setText(Table_Locales.getValueAt(Table_Locales.getSelectedRow(), 5).toString());
        TextField_CalleEmpresa.setText(Table_Locales.getValueAt(Table_Locales.getSelectedRow(), 6).toString());
        TextField_TelefonoEmpresa.setText(Table_Locales.getValueAt(Table_Locales.getSelectedRow(), 7).toString());
    }//GEN-LAST:event_Button_SeleccionarActionPerformed

    private void Button_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EliminarActionPerformed
        try {
            int id_ad = Integer.parseInt((String) Table_Locales.getValueAt(Table_Locales.getSelectedRow(), 0));
            
            //localController.destroy(id_ad);
            Local  local = control.buscarLocal(id_ad);
            control.delete(local);
            
            LoadDates();
            JOptionPane.showMessageDialog(null, "Eliminado exitosamente");
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_Button_EliminarActionPerformed

    private void TextField_BuscarClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_BuscarClienteKeyTyped
        TextField_BuscarCliente.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (TextField_BuscarCliente.getText().toUpperCase());
                TextField_BuscarCliente.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsfiltro = new TableRowSorter(Table_Locales.getModel());
        Table_Locales.setRowSorter(trsfiltro);
    }//GEN-LAST:event_TextField_BuscarClienteKeyTyped
    
    private void limpiar() {
        TextField_rucEmpresa.setText("");
        TextField_NombreEmpresa.setText("");
        TextField_Provincia.setText("");
        TextField_CantonEmpresa.setText("");
        TextField_ParroquiaEmpresa.setText("");
        TextField_CalleEmpresa.setText("");
        TextField_TelefonoEmpresa.setText("");
        
        Label_rucEmpresa.setForeground(new Color(102, 102, 102));
        Label_NombreEmpresa.setForeground(new Color(102, 102, 102));
        Label_ProvinciaEmpresa.setForeground(new Color(102, 102, 102));
        Label_CantonEmpresa.setForeground(new Color(102, 102, 102));
        Label_parroquiaEmpresa.setForeground(new Color(102, 102, 102));
        Label_calleEmpresa.setForeground(new Color(102, 102, 102));
        Label_TelefonoEmpresa.setForeground(new Color(102, 102, 102));
        
    }
    
    private void save() {
        try {
            System.out.println("administrador recuperado    :  ");
//            Local local = new Local( nombre, provincia, canton, parroquia, calle, telefono, ruc, objeto);
            Local local = new Local();
            
            
            local.setRuc(this.ruc);
            
            local.setNombre(this.nombre);
            
            local.setProvincia(this.provincia);
            
            local.setCanton(this.canton);
            
            local.setParroquia(this.parroquia);
            
            local.setCalle(this.calle);
            
            local.setTelefono(this.telefono);
            
            local.setAdmin(this.objeto);
            this.objeto.addLocal(local);
            //localController.create(local);

            control.insert(local);
//            List<Local> locales = control.getAllLocales();
//            this.objeto.setLocal(locales);
            
           // Administrador admins = adminController.findAdministrador(this.objeto.getId());
            //admins.setLocal(Arrays.asList(local));
            //adminController.edit(admins);
            //this.objeto.setLocal((List<Local>) local);

            //local.setAdmin(this.objeto);
            LoadDates();
        } catch (Exception e) {
            System.out.println(e);
//            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private int validar() {
        int val = 0;
        
        if (TextField_rucEmpresa.getText().equals("")) {
            Label_rucEmpresa.setText("Ingrese el Ruc");
            Label_rucEmpresa.setForeground(Color.red);
            TextField_rucEmpresa.requestFocus();
        } else {
            val++;
            if (TextField_NombreEmpresa.getText().equals("")) {
                Label_NombreEmpresa.setText("Ingrese el Nombre");
                Label_NombreEmpresa.setForeground(Color.red);
                TextField_NombreEmpresa.requestFocus();
            } else {
                val++;
                if (TextField_Provincia.getText().equals("")) {
                    Label_ProvinciaEmpresa.setText("Ingrese la Provincia");
                    Label_ProvinciaEmpresa.setForeground(Color.red);
                    TextField_Provincia.requestFocus();
                } else {
                    val++;
                    if (TextField_CantonEmpresa.getText().equals("")) {
                        Label_CantonEmpresa.setText("Ingrese el Cantón");
                        Label_CantonEmpresa.setForeground(Color.red);
                        TextField_CantonEmpresa.requestFocus();
                    } else {
                        val++;
                        if (TextField_ParroquiaEmpresa.getText().equals("")) {
                            Label_parroquiaEmpresa.setText("Ingrese la Parroquia");
                            Label_parroquiaEmpresa.setForeground(Color.red);
                            TextField_ParroquiaEmpresa.requestFocus();
                        } else {
                            val++;
                            if (TextField_CalleEmpresa.getText().equals("")) {
                                Label_calleEmpresa.setText("Ingrese la Calle");
                                Label_calleEmpresa.setForeground(Color.red);
                                TextField_CalleEmpresa.requestFocus();
                            } else {
                                val++;
                                if (TextField_TelefonoEmpresa.getText().equals("")) {
                                    Label_TelefonoEmpresa.setText("Ingrese el teléfono");
                                    Label_TelefonoEmpresa.setForeground(Color.red);
                                    TextField_TelefonoEmpresa.requestFocus();
                                } else {
                                    val++;
                                    if (acction.equals("insert")) {
                                        this.ruc = TextField_rucEmpresa.getText();
                                        this.nombre = TextField_NombreEmpresa.getText().toUpperCase();
                                        this.provincia = TextField_Provincia.getText().toUpperCase();
                                        this.canton = TextField_CantonEmpresa.getText().toUpperCase();
                                        this.parroquia = TextField_ParroquiaEmpresa.getText().toUpperCase();
                                        this.calle = TextField_CalleEmpresa.getText().toUpperCase();
                                        this.telefono = TextField_TelefonoEmpresa.getText();
                                        buscar(rSComboAdmin.getSelectedItem().toString());
                                        
                                    }
                                    
                                }
                                
                            }
                            
                        }
                        
                    }
                    
                }
                
            }
        }
        
        return val;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cancelar;
    private javax.swing.JButton Button_Editar;
    private javax.swing.JButton Button_Eliminar;
    private javax.swing.JButton Button_Guardar;
    private javax.swing.JButton Button_Limpiar;
    private javax.swing.JButton Button_Seleccionar;
    private javax.swing.JLabel Label_CantonEmpresa;
    private javax.swing.JLabel Label_NombreEmpresa;
    private javax.swing.JLabel Label_ProvinciaEmpresa;
    private javax.swing.JLabel Label_TelefonoEmpresa;
    private javax.swing.JLabel Label_calleEmpresa;
    private javax.swing.JLabel Label_idAdminEmpresa;
    private javax.swing.JLabel Label_parroquiaEmpresa;
    private javax.swing.JLabel Label_rucEmpresa;
    private javax.swing.JTable Table_Locales;
    private javax.swing.JTextField TextField_BuscarCliente;
    private javax.swing.JTextField TextField_CalleEmpresa;
    private javax.swing.JTextField TextField_CantonEmpresa;
    private javax.swing.JTextField TextField_NombreEmpresa;
    private javax.swing.JTextField TextField_ParroquiaEmpresa;
    private javax.swing.JTextField TextField_Provincia;
    private javax.swing.JTextField TextField_TelefonoEmpresa;
    private javax.swing.JTextField TextField_rucEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSComboMetro rSComboAdmin;
    // End of variables declaration//GEN-END:variables
}
