/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import ModelClass.TextFieldEven;
import alertas.principal.ErrorAlert;
import alertas.principal.SuccessAlert;

import controllers.ClienteJpaController;
import controllers.Controlador;
import controllers.ProveedorJpaController;
import controllers.ControllerCliente;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import models.Cliente;
import models.Local;
import models.Proveedor;
import proveedores.Sentencias;

/**
 *
 * @author RojeruSan
 */
public class PnlProveedor extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    private String acction = "insert", Id = "", dia, mes, anio, funcionCatDpt, idCat, dpt;
    private int pageSize, tab, maxReg, pageCount, currentPage, numReg;
    private int startRec, endRec;
    TextFieldEven evento = new TextFieldEven();

    private String ci = "";
    private String ruc = "";
    private String nombre = "";
    private String apellido = "";
    private String direccion = "";
    private String telefono = "";
    private String email = "";
    private String empresa = "";

    Controlador control = new Controlador();
    ProveedorJpaController proveedorController = new ProveedorJpaController();
    DefaultTableModel modelo2;
    int ids;
    private TableRowSorter trsfiltro;

    public PnlProveedor() {
        initComponents();
        proveedores.Opciones.listarProveedor("");
        this.Button_Guardar.setEnabled(true);
        this.Button_Editar.setEnabled(false);
    }

    public void filtro() {
        trsfiltro.setRowFilter(RowFilter.regexFilter(TextField_BuscarProveedor.getText(), 4));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Button_Limpiar = new javax.swing.JButton();
        Button_Guardar = new javax.swing.JButton();
        Label_rucProveedor = new javax.swing.JLabel();
        TextField_rucProveedor = new javax.swing.JTextField();
        Label_ciProveedor = new javax.swing.JLabel();
        TextField_CiProveedor = new javax.swing.JTextField();
        Label_NombreProveedor = new javax.swing.JLabel();
        TextField_NombreProveedor = new javax.swing.JTextField();
        Label_ApellidoProveedor = new javax.swing.JLabel();
        TextField_ApellidioProveedor = new javax.swing.JTextField();
        Label_DireccionProveedor = new javax.swing.JLabel();
        TextField_DireccionProveedor = new javax.swing.JTextField();
        Label_TelefonoProveedor = new javax.swing.JLabel();
        TextField_TelefonoProveedor = new javax.swing.JTextField();
        Label_emailProveedor = new javax.swing.JLabel();
        TextField_EmailProveedor = new javax.swing.JTextField();
        Label_empresaProveedor = new javax.swing.JLabel();
        TextField_empresaProveedor = new javax.swing.JTextField();
        Button_Editar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TextField_BuscarProveedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Button_Seleccionar = new javax.swing.JButton();
        Button_Eliminar = new javax.swing.JButton();
        Button_Cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Proveedores = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(80, 80, 97));
        jLabel2.setText("Datos del proveedor");
        jLabel2.setToolTipText("");

        Button_Limpiar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png"))); // NOI18N
        Button_Limpiar.setText("Limpiar");
        Button_Limpiar.setBorder(null);
        Button_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LimpiarActionPerformed(evt);
            }
        });

        Button_Guardar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Agregar.png"))); // NOI18N
        Button_Guardar.setText("Guardar");
        Button_Guardar.setBorder(null);
        Button_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GuardarActionPerformed(evt);
            }
        });

        Label_rucProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_rucProveedor.setForeground(new java.awt.Color(102, 102, 102));
        Label_rucProveedor.setText("Ruc");
        Label_rucProveedor.setToolTipText("");

        TextField_rucProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_rucProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_rucProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_rucProveedorKeyTyped(evt);
            }
        });

        Label_ciProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_ciProveedor.setForeground(new java.awt.Color(102, 102, 102));
        Label_ciProveedor.setText("CI");
        Label_ciProveedor.setToolTipText("");

        TextField_CiProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_CiProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_CiProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_CiProveedorKeyTyped(evt);
            }
        });

        Label_NombreProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_NombreProveedor.setForeground(new java.awt.Color(102, 102, 102));
        Label_NombreProveedor.setText("Nombre completo");
        Label_NombreProveedor.setToolTipText("");

        TextField_NombreProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_NombreProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_NombreProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_NombreProveedorKeyTyped(evt);
            }
        });

        Label_ApellidoProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_ApellidoProveedor.setForeground(new java.awt.Color(102, 102, 102));
        Label_ApellidoProveedor.setText("Apellido");

        TextField_ApellidioProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_ApellidioProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_ApellidioProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_ApellidioProveedorKeyTyped(evt);
            }
        });

        Label_DireccionProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_DireccionProveedor.setForeground(new java.awt.Color(102, 102, 102));
        Label_DireccionProveedor.setText("Dirección");
        Label_DireccionProveedor.setToolTipText("");

        TextField_DireccionProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_DireccionProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_DireccionProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_DireccionProveedorKeyTyped(evt);
            }
        });

        Label_TelefonoProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_TelefonoProveedor.setForeground(new java.awt.Color(102, 102, 102));
        Label_TelefonoProveedor.setText("Teléfono");

        TextField_TelefonoProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_TelefonoProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_TelefonoProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_TelefonoProveedorKeyTyped(evt);
            }
        });

        Label_emailProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_emailProveedor.setForeground(new java.awt.Color(102, 102, 102));
        Label_emailProveedor.setText("email");

        TextField_EmailProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_EmailProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_EmailProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_EmailProveedorKeyTyped(evt);
            }
        });

        Label_empresaProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_empresaProveedor.setForeground(new java.awt.Color(102, 102, 102));
        Label_empresaProveedor.setText("Nombre empresa");

        TextField_empresaProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_empresaProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_empresaProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_empresaProveedorKeyTyped(evt);
            }
        });

        Button_Editar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar.png"))); // NOI18N
        Button_Editar.setText("Editar");
        Button_Editar.setBorder(null);
        Button_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Button_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextField_NombreProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(TextField_ApellidioProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(TextField_DireccionProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(TextField_TelefonoProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(TextField_CiProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(TextField_EmailProveedor)
                            .addComponent(TextField_empresaProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(TextField_rucProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(Label_rucProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_ciProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_NombreProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_ApellidoProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_DireccionProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_TelefonoProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_emailProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Label_empresaProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_rucProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_rucProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Label_ciProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_CiProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_NombreProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_NombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_ApellidoProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_ApellidioProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Label_DireccionProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_DireccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_TelefonoProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_TelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_emailProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_EmailProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_empresaProveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_empresaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(80, 80, 97));
        jLabel5.setText("Buscar");

        TextField_BuscarProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_BuscarProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_BuscarProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_BuscarProveedorKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 97));
        jLabel1.setText("Proveedores");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(86, 86, 86)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(TextField_BuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextField_BuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Button_Seleccionar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Seleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Left.png"))); // NOI18N
        Button_Seleccionar.setText("Seleccionar");
        Button_Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SeleccionarActionPerformed(evt);
            }
        });

        Button_Eliminar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png"))); // NOI18N
        Button_Eliminar.setText("Eliminar");
        Button_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EliminarActionPerformed(evt);
            }
        });

        Button_Cancelar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar.png"))); // NOI18N
        Button_Cancelar.setText("Cancelar");
        Button_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelarActionPerformed(evt);
            }
        });

        Table_Proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CI", "RUC", "NOMBRE", "APELLIDO", "DIRECCIÓN", "EMAIL", "TÉLEFONO", "EMPRESA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table_Proveedores);
        if (Table_Proveedores.getColumnModel().getColumnCount() > 0) {
            Table_Proveedores.getColumnModel().getColumn(0).setPreferredWidth(14);
            Table_Proveedores.getColumnModel().getColumn(1).setResizable(false);
            Table_Proveedores.getColumnModel().getColumn(2).setResizable(false);
            Table_Proveedores.getColumnModel().getColumn(4).setResizable(false);
            Table_Proveedores.getColumnModel().getColumn(5).setResizable(false);
            Table_Proveedores.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Seleccionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button_Cancelar)
                        .addComponent(Button_Seleccionar))
                    .addComponent(Button_Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GuardarActionPerformed

        if (validar() == 6) {
            saveCliente();

            JOptionPane.showMessageDialog(null, "Guardado exitosamente");
            limpiar();
            this.ci = "";
            this.ruc = "";
            this.nombre = "";
            this.apellido = "";
            this.direccion = "";
            this.telefono = "";
            this.email = "";
            this.empresa = "";

        } else {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        }
    }//GEN-LAST:event_Button_GuardarActionPerformed

    private void Button_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_Button_LimpiarActionPerformed

    private void TextField_rucProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_rucProveedorKeyReleased
        if (TextField_rucProveedor.getText().equals("")) {
            Label_rucProveedor.setForeground(new Color(102, 102, 102));
        } else {
            Label_rucProveedor.setText("Ruc");
            Label_rucProveedor.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_rucProveedorKeyReleased

    private void TextField_rucProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_rucProveedorKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_rucProveedorKeyTyped

    private void TextField_CiProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CiProveedorKeyReleased
        if (TextField_CiProveedor.getText().equals("")) {
            Label_ciProveedor.setForeground(new Color(102, 102, 102));
        } else {
            Label_ciProveedor.setText("CI");
            Label_ciProveedor.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_CiProveedorKeyReleased

    private void TextField_CiProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CiProveedorKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_CiProveedorKeyTyped

    private void TextField_NombreProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_NombreProveedorKeyReleased
        if (TextField_NombreProveedor.getText().equals("")) {
            Label_NombreProveedor.setForeground(new Color(102, 102, 102));
        } else {
            Label_NombreProveedor.setText("Nombres completos");
            Label_NombreProveedor.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_NombreProveedorKeyReleased

    private void TextField_NombreProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_NombreProveedorKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_NombreProveedorKeyTyped

    private void TextField_ApellidioProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ApellidioProveedorKeyReleased
        if (TextField_ApellidioProveedor.getText().equals("")) {
            Label_ApellidoProveedor.setForeground(new Color(102, 102, 102));
        } else {
            Label_ApellidoProveedor.setText("Apellidos");
            Label_ApellidoProveedor.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_ApellidioProveedorKeyReleased

    private void TextField_ApellidioProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ApellidioProveedorKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_ApellidioProveedorKeyTyped

    private void TextField_DireccionProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_DireccionProveedorKeyReleased
        if (TextField_DireccionProveedor.getText().equals("")) {
            Label_DireccionProveedor.setForeground(new Color(102, 102, 102));
        } else {
            Label_DireccionProveedor.setText("Dirección");
            Label_DireccionProveedor.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_DireccionProveedorKeyReleased

    private void TextField_DireccionProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_DireccionProveedorKeyTyped

    }//GEN-LAST:event_TextField_DireccionProveedorKeyTyped

    private void TextField_TelefonoProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_TelefonoProveedorKeyReleased
        if (TextField_TelefonoProveedor.getText().equals("")) {
            Label_TelefonoProveedor.setForeground(new Color(102, 102, 102));
        } else {
            Label_TelefonoProveedor.setText("Teléfono");
            Label_TelefonoProveedor.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_TelefonoProveedorKeyReleased

    private void TextField_TelefonoProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_TelefonoProveedorKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_TelefonoProveedorKeyTyped

    private void TextField_EmailProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_EmailProveedorKeyReleased
        if (TextField_EmailProveedor.getText().equals("")) {
            Label_emailProveedor.setForeground(new Color(102, 102, 102));
        } else {
            Label_emailProveedor.setText("email");
            Label_emailProveedor.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_EmailProveedorKeyReleased

    private void TextField_EmailProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_EmailProveedorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_EmailProveedorKeyTyped

    private void TextField_empresaProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_empresaProveedorKeyReleased
        if (TextField_empresaProveedor.getText().equals("")) {
            Label_empresaProveedor.setForeground(new Color(102, 102, 102));
        } else {
            Label_empresaProveedor.setText("Nombre empresa");
            Label_empresaProveedor.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_empresaProveedorKeyReleased

    private void TextField_empresaProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_empresaProveedorKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_empresaProveedorKeyTyped

    
    public void actualizar() {
        System.out.println("valor de validar ; "+validar());
        if (validar() < 6) {

            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("FALTAN CAMPOS DE LLENAR");
            er.msj1.setText("");
            er.setVisible(true);

        } else {
            //String ci, String nom, String ruc, String dir, String ape, String telf
            Sentencias s = new Sentencias(apellido, ci, direccion, email, empresa,nombre,ruc,telefono);
            s.setId(this.ids);

            int opcion = proveedores.Opciones.actualizar(s);
            if (opcion != 0) {

                proveedores.Opciones.listarProveedor("");

                SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                sa.titulo.setText("¡HECHO!");
                sa.msj.setText("SE HAN GUARDADO LOS CAMBIOS");
                sa.msj1.setText("");
                sa.setVisible(true);
            } else {
                System.out.println(s.toString());
            }
        }

    }
    
    private void Button_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EditarActionPerformed
       actualizar();
        limpiar();
        this.ids=0;
    }//GEN-LAST:event_Button_EditarActionPerformed

    private void Button_SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SeleccionarActionPerformed
        this.Button_Guardar.setEnabled(false);
        this.Button_Editar.setEnabled(true);
        this.ids = Integer.parseInt((String) Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 0));

        TextField_rucProveedor.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 1).toString());
        TextField_CiProveedor.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 2).toString());
        TextField_NombreProveedor.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 3).toString());
        TextField_ApellidioProveedor.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 4).toString());
        TextField_DireccionProveedor.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 5).toString());
        TextField_TelefonoProveedor.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 6).toString());
        TextField_EmailProveedor.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 7).toString());
        TextField_empresaProveedor.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 8).toString());
    }//GEN-LAST:event_Button_SeleccionarActionPerformed

    private void TextField_BuscarProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_BuscarProveedorKeyTyped
        TextField_BuscarProveedor.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (TextField_BuscarProveedor.getText().toUpperCase());
                TextField_BuscarProveedor.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsfiltro = new TableRowSorter(Table_Proveedores.getModel());
        Table_Proveedores.setRowSorter(trsfiltro);
    }//GEN-LAST:event_TextField_BuscarProveedorKeyTyped

    private void Button_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EliminarActionPerformed
        try {
            int id_ad = Integer.parseInt((String) Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 0));
            int elimina = proveedores.Opciones.eliminar(id_ad);
            if (elimina != 0) {

                proveedores.Opciones.listar("");
                SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                sa.titulo.setText("¡HECHO!");
                sa.msj.setText("SE HA ELIMINADO UN");
                sa.msj1.setText("REGISTRO");
                sa.setVisible(true);
            }
            //productoController.destroy(id_ad);

            //LoadDates();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Button_EliminarActionPerformed

    private void Button_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelarActionPerformed
        limpiar();
        this.Button_Guardar.setEnabled(true);
        this.Button_Editar.setEnabled(false);
    }//GEN-LAST:event_Button_CancelarActionPerformed

    private void TextField_BuscarProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_BuscarProveedorKeyReleased
        proveedores.Opciones.listarProveedor(TextField_BuscarProveedor.getText());
    }//GEN-LAST:event_TextField_BuscarProveedorKeyReleased

    private void LoadDates() {
        try {
            Table_Proveedores.removeAll();
            String[] titulos = {"id", "Ruc", "Ci", "Nombres", "Apellidos", "Dirección", "Teléfono", "Email", "Empresa"};
            String[] registro = new String[9];
            //Object o[] = null;
            List<Proveedor> listproveedor = proveedorController.findProveedorEntities();
            modelo2 = new DefaultTableModel(null, titulos);

            for (int i = 0; i < listproveedor.size(); i++) {
//                modelo2.addRow(o);
                registro[0] = String.valueOf(listproveedor.get(i).getId());
                registro[1] = listproveedor.get(i).getRucProveedor();
                registro[2] = listproveedor.get(i).getCiProveedor();
                registro[3] = listproveedor.get(i).getNomProveedor();
                registro[4] = listproveedor.get(i).getApeProveedor();
                registro[5] = listproveedor.get(i).getDirProveedor();
                registro[6] = listproveedor.get(i).getTelefono();
                registro[7] = listproveedor.get(i).getEmail();
                registro[8] = listproveedor.get(i).getEmpresaProveedor();

                //System.out.println(listLocal.get(i).getAdmin().toString());
                modelo2.addRow(registro);
            }
            Table_Proveedores.setModel(modelo2);

        } catch (Exception e) {
            System.out.println(e.toString());
        }

    }

    private void saveCliente() {
        try {
            if (validar() == 6) {
                
                //ape_proveedor, ci_proveedor, dir_proveedor, email_proveedor, empresa_proveedor,nom_proveedor,ruc_proveedor,telf_proveedor
                proveedores.Sentencias sentecia = new proveedores.Sentencias(apellido, ci, direccion, email, empresa,nombre,ruc,telefono);
                proveedores.Opciones.registrar(sentecia);
                proveedores.Opciones.listarProveedor("");
            }

        } catch (Exception e) {
            System.out.println(e);
//            JOptionPane.showMessageDialog(null, e);
        }
    }

    private int validar() {
        int val = 0;
        if (TextField_CiProveedor.getText().equals("")) {
            Label_ciProveedor.setText("Ingrese CI");
            Label_ciProveedor.setForeground(Color.red);
            TextField_CiProveedor.requestFocus();
        } else {
            val++;
            if (TextField_NombreProveedor.getText().equals("")) {
                Label_NombreProveedor.setText("Ingrese el nombre");
                Label_NombreProveedor.setForeground(Color.red);
                TextField_NombreProveedor.requestFocus();
            } else {
                val++;
                if (TextField_ApellidioProveedor.getText().equals("")) {
                    Label_ApellidoProveedor.setText("Ingrese el apellido");
                    Label_ApellidoProveedor.setForeground(Color.red);
                    TextField_ApellidioProveedor.requestFocus();
                } else {
                    val++;
                    if (TextField_DireccionProveedor.getText().equals("")) {
                        Label_DireccionProveedor.setText("Ingrese la dirección");
                        Label_DireccionProveedor.setForeground(Color.red);
                        TextField_DireccionProveedor.requestFocus();
                    } else {
                        val++;
                        if (TextField_TelefonoProveedor.getText().equals("")) {
                            Label_TelefonoProveedor.setText("Ingrese el teléfono");
                            Label_TelefonoProveedor.setForeground(Color.red);
                            TextField_TelefonoProveedor.requestFocus();
                        } else {
                            val++;
                            if (TextField_empresaProveedor.getText().equals("")) {
                                Label_empresaProveedor.setText("Ingrese nombre de la empresa");
                                Label_empresaProveedor.setForeground(Color.red);
                                TextField_empresaProveedor.requestFocus();
                            } else {
                                val++;
                                if (acction.equals("insert")) {
                                    ci = TextField_CiProveedor.getText();
                                    ruc = TextField_rucProveedor.getText();
                                    nombre = TextField_NombreProveedor.getText().toUpperCase();
                                    apellido = TextField_ApellidioProveedor.getText().toUpperCase();
                                    direccion = TextField_DireccionProveedor.getText().toUpperCase();
                                    telefono = TextField_TelefonoProveedor.getText();
                                    email = TextField_EmailProveedor.getText();
                                    empresa = TextField_empresaProveedor.getText().toUpperCase();

                                }

                            }

                        }

                    }

                }

            }
        }

        return val;
    }

    private void limpiar() {
        TextField_CiProveedor.setText("");
        TextField_rucProveedor.setText("");
        TextField_NombreProveedor.setText("");
        TextField_ApellidioProveedor.setText("");
        TextField_DireccionProveedor.setText("");
        TextField_TelefonoProveedor.setText("");
        TextField_EmailProveedor.setText("");
        TextField_empresaProveedor.setText("");

        Label_ciProveedor.setForeground(new Color(102, 102, 102));
        Label_rucProveedor.setForeground(new Color(102, 102, 102));
        Label_NombreProveedor.setForeground(new Color(102, 102, 102));
        Label_ApellidoProveedor.setForeground(new Color(102, 102, 102));
        Label_DireccionProveedor.setForeground(new Color(102, 102, 102));
        Label_TelefonoProveedor.setForeground(new Color(102, 102, 102));
        Label_emailProveedor.setForeground(new Color(102, 102, 102));
        Label_empresaProveedor.setForeground(new Color(102, 102, 102));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cancelar;
    private javax.swing.JButton Button_Editar;
    private javax.swing.JButton Button_Eliminar;
    private javax.swing.JButton Button_Guardar;
    private javax.swing.JButton Button_Limpiar;
    private javax.swing.JButton Button_Seleccionar;
    private javax.swing.JLabel Label_ApellidoProveedor;
    private javax.swing.JLabel Label_DireccionProveedor;
    private javax.swing.JLabel Label_NombreProveedor;
    private javax.swing.JLabel Label_TelefonoProveedor;
    private javax.swing.JLabel Label_ciProveedor;
    private javax.swing.JLabel Label_emailProveedor;
    private javax.swing.JLabel Label_empresaProveedor;
    private javax.swing.JLabel Label_rucProveedor;
    public static javax.swing.JTable Table_Proveedores;
    private javax.swing.JTextField TextField_ApellidioProveedor;
    private javax.swing.JTextField TextField_BuscarProveedor;
    private javax.swing.JTextField TextField_CiProveedor;
    private javax.swing.JTextField TextField_DireccionProveedor;
    private javax.swing.JTextField TextField_EmailProveedor;
    private javax.swing.JTextField TextField_NombreProveedor;
    private javax.swing.JTextField TextField_TelefonoProveedor;
    private javax.swing.JTextField TextField_empresaProveedor;
    private javax.swing.JTextField TextField_rucProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
