/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import ModelClass.TextFieldEven;
import alertas.principal.ErrorAlert;
import alertas.principal.SuccessAlert;
import conexion.ConexionBD;

import controllers.Controlador;
import controllers.ProductoJpaController;
import controllers.ProveedorJpaController;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import models.Administrador;
import models.Producto;
import models.Proveedor;
import producto.Opciones;
import producto.Sentencias;

/**
 *
 * @author RojeruSan
 */
public class PnlProductos extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    private String acction = "insert", Id = "", dia, mes, anio, funcionCatDpt, idCat, dpt;
    private int pageSize, tab, maxReg, pageCount, currentPage, numReg;
    private int startRec, endRec;
    TextFieldEven evento = new TextFieldEven();
    static ConexionBD cc = new ConexionBD();
    static Connection cn = cc.conexion();

    private String cod = "";
    private String nom = "";
    private String des = "";
    private double pc = 0;
    private double pv = 0;
    private double pm = 0;
    private int idprovedor;
    private int cantidad = 0;
    private String tipo = "";

    private int rowtable;

    Controlador control = new Controlador();
    ProductoJpaController productoController = new ProductoJpaController();
    ProveedorJpaController provedor = new ProveedorJpaController();
    DefaultTableModel modelo2;
    int ids;
    private TableRowSorter trsfiltro;
    List<Proveedor> add;
    Proveedor objeto;

    public PnlProductos() {
        initComponents();

        ConexionBD.conectar();
        comboProveedor.removeAllItems();
        ArrayList<String> lista = new ArrayList<String>();
        lista = conexion.ConexionBD.llenar_combo("proveedores", "empresa_proveedor");
        for (int i = 0; i < lista.size(); i++) {
            comboProveedor.addItem(lista.get(i));
        }
        this.Button_Guardar.setEnabled(true);
        this.Button_Editar.setEnabled(false);

        producto.Opciones.listartodoProductos();
        this.rowtable = 1;
        this.radiobarras.setSelected(true);
    }

    public void cargarAdmin() {
        List<Proveedor> listprovedor = provedor.findProveedorEntities();
        this.add = listprovedor;
        comboProveedor.removeAllItems();
        for (Proveedor pro : listprovedor) {
            comboProveedor.addItem(pro.getEmpresaProveedor());
        }
    }

    public void filtro(int rowtable) {
        trsfiltro.setRowFilter(RowFilter.regexFilter(TextField_BuscarProveedor.getText(), rowtable));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        Button_Limpiar = new javax.swing.JButton();
        Button_Guardar = new javax.swing.JButton();
        Label_codPRODUCTO = new javax.swing.JLabel();
        TextField_CODPRODUCTO = new javax.swing.JTextField();
        Label_nomPRODUCTO = new javax.swing.JLabel();
        TextField_nomPRODUCTO = new javax.swing.JTextField();
        Label_desPRODUCTO = new javax.swing.JLabel();
        TextField_desPRODUCTO = new javax.swing.JTextField();
        Label_canPRODUCTO = new javax.swing.JLabel();
        TextField_canPRODUCTO = new javax.swing.JTextField();
        Label_pcPRODUCTO = new javax.swing.JLabel();
        TextField_pcPRODUCTO = new javax.swing.JTextField();
        Label_pvPRODUCTO = new javax.swing.JLabel();
        TextField_pvPRODUCTO = new javax.swing.JTextField();
        Label_pmPRODUCTO = new javax.swing.JLabel();
        TextField_pmPRODUCTO = new javax.swing.JTextField();
        Button_Editar = new javax.swing.JButton();
        Label_empresaProveedor = new javax.swing.JLabel();
        comboProveedor = new javax.swing.JComboBox<>();
        combotipo = new javax.swing.JComboBox<>();
        Label_productoTipo = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TextField_BuscarProveedor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        radionombre = new javax.swing.JRadioButton();
        radiobarras = new javax.swing.JRadioButton();
        radiocategoria = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_Proveedores =   Table_Proveedores = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        Button_Seleccionar = new javax.swing.JButton();
        Button_Eliminar = new javax.swing.JButton();
        Button_Cancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        Button_Limpiar.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        Button_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png"))); // NOI18N
        Button_Limpiar.setText("Limpiar");
        Button_Limpiar.setBorder(null);
        Button_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LimpiarActionPerformed(evt);
            }
        });

        Button_Guardar.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        Button_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Agregar.png"))); // NOI18N
        Button_Guardar.setText("Guardar");
        Button_Guardar.setBorder(null);
        Button_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GuardarActionPerformed(evt);
            }
        });

        Label_codPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_codPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        Label_codPRODUCTO.setText("Código");
        Label_codPRODUCTO.setToolTipText("");

        TextField_CODPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_CODPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_CODPRODUCTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_CODPRODUCTOKeyTyped(evt);
            }
        });

        Label_nomPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_nomPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        Label_nomPRODUCTO.setText("Nombre");
        Label_nomPRODUCTO.setToolTipText("");

        TextField_nomPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_nomPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_nomPRODUCTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_nomPRODUCTOKeyTyped(evt);
            }
        });

        Label_desPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_desPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        Label_desPRODUCTO.setText("Descripción");
        Label_desPRODUCTO.setToolTipText("");

        TextField_desPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_desPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_desPRODUCTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_desPRODUCTOKeyTyped(evt);
            }
        });

        Label_canPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_canPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        Label_canPRODUCTO.setText("Cantidad");

        TextField_canPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_canPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_canPRODUCTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_canPRODUCTOKeyTyped(evt);
            }
        });

        Label_pcPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_pcPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        Label_pcPRODUCTO.setText("Precio compra");
        Label_pcPRODUCTO.setToolTipText("");

        TextField_pcPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_pcPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_pcPRODUCTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_pcPRODUCTOKeyTyped(evt);
            }
        });

        Label_pvPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_pvPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        Label_pvPRODUCTO.setText("Precio venta");

        TextField_pvPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_pvPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_pvPRODUCTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_pvPRODUCTOKeyTyped(evt);
            }
        });

        Label_pmPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_pmPRODUCTO.setForeground(new java.awt.Color(102, 102, 102));
        Label_pmPRODUCTO.setText("Precio mayorista");

        TextField_pmPRODUCTO.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_pmPRODUCTO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_pmPRODUCTOKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_pmPRODUCTOKeyTyped(evt);
            }
        });

        Button_Editar.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        Button_Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar.png"))); // NOI18N
        Button_Editar.setText("Editar");
        Button_Editar.setBorder(null);
        Button_Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EditarActionPerformed(evt);
            }
        });

        Label_empresaProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_empresaProveedor.setForeground(new java.awt.Color(102, 102, 102));
        Label_empresaProveedor.setText("Proveedor");

        combotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASEO", "HOJAS", "LIBROS", "JUGUETES", "BISUTERIA" }));
        combotipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotipoActionPerformed(evt);
            }
        });

        Label_productoTipo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Label_productoTipo.setForeground(new java.awt.Color(102, 102, 102));
        Label_productoTipo.setText("Categoría");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Button_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(Button_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TextField_CODPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Label_nomPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextField_nomPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Label_desPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextField_desPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Label_canPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextField_canPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Label_pcPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextField_pcPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Label_pvPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextField_pvPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Label_pmPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextField_pmPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Label_codPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Label_empresaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Label_productoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_empresaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_productoTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_codPRODUCTO)
                .addGap(6, 6, 6)
                .addComponent(TextField_CODPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Label_nomPRODUCTO)
                .addGap(6, 6, 6)
                .addComponent(TextField_nomPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Label_desPRODUCTO)
                .addGap(6, 6, 6)
                .addComponent(TextField_desPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Label_canPRODUCTO)
                .addGap(6, 6, 6)
                .addComponent(TextField_canPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Label_pcPRODUCTO)
                .addGap(6, 6, 6)
                .addComponent(TextField_pcPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Label_pvPRODUCTO)
                .addGap(6, 6, 6)
                .addComponent(TextField_pvPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(Label_pmPRODUCTO)
                .addGap(6, 6, 6)
                .addComponent(TextField_pmPRODUCTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Button_Guardar, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(Button_Editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(80, 80, 97));
        jLabel5.setText("filtrar por");

        TextField_BuscarProveedor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TextField_BuscarProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_BuscarProveedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_BuscarProveedorKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(80, 80, 97));
        jLabel1.setText("Productos");

        radionombre.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        radionombre.setForeground(new java.awt.Color(102, 102, 102));
        radionombre.setText("nombre");
        radionombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radionombreActionPerformed(evt);
            }
        });

        radiobarras.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        radiobarras.setForeground(new java.awt.Color(102, 102, 102));
        radiobarras.setText("c. barras");
        radiobarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiobarrasActionPerformed(evt);
            }
        });

        radiocategoria.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        radiocategoria.setForeground(new java.awt.Color(102, 102, 102));
        radiocategoria.setText("categoría");
        radiocategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiocategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radiobarras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radionombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radiocategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextField_BuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(TextField_BuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(radionombre)
                        .addComponent(radiobarras)
                        .addComponent(radiocategoria))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Table_Proveedores.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Table_Proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table_Proveedores.setRowHeight(20);
        Table_Proveedores.setSelectionBackground(new java.awt.Color(102, 204, 255));
        jScrollPane2.setViewportView(Table_Proveedores);

        Button_Seleccionar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Seleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Left.png"))); // NOI18N
        Button_Seleccionar.setText("Seleccionar");
        Button_Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SeleccionarActionPerformed(evt);
            }
        });

        Button_Eliminar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eliminar.png"))); // NOI18N
        Button_Eliminar.setText("Eliminar");
        Button_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EliminarActionPerformed(evt);
            }
        });

        Button_Cancelar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Button_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar.png"))); // NOI18N
        Button_Cancelar.setText("Cancelar");
        Button_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Seleccionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Button_Seleccionar)
                        .addComponent(Button_Cancelar))
                    .addComponent(Button_Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GuardarActionPerformed

        guardar();
        limpiar();
        this.cod = "";
        this.nom = "";
        this.des = "";
        this.pc = 0;
        this.pv = 0;
        this.pm = 0;
        this.cantidad = 0;
        this.idprovedor = 0;
    }//GEN-LAST:event_Button_GuardarActionPerformed

    private void Button_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_Button_LimpiarActionPerformed

    private void TextField_CODPRODUCTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CODPRODUCTOKeyReleased
        if (TextField_CODPRODUCTO.getText().equals("")) {
            Label_codPRODUCTO.setForeground(new Color(102, 102, 102));
        } else {
            Label_codPRODUCTO.setText("Código");
            Label_codPRODUCTO.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_CODPRODUCTOKeyReleased

    private void TextField_CODPRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CODPRODUCTOKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_CODPRODUCTOKeyTyped

    private void TextField_nomPRODUCTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_nomPRODUCTOKeyReleased
        if (TextField_nomPRODUCTO.getText().equals("")) {
            Label_nomPRODUCTO.setForeground(new Color(102, 102, 102));
        } else {
            Label_nomPRODUCTO.setText("Nombre");
            Label_nomPRODUCTO.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_nomPRODUCTOKeyReleased

    private void TextField_nomPRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_nomPRODUCTOKeyTyped
       // evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_nomPRODUCTOKeyTyped

    private void TextField_desPRODUCTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_desPRODUCTOKeyReleased
        if (TextField_desPRODUCTO.getText().equals("")) {
            Label_desPRODUCTO.setForeground(new Color(102, 102, 102));
        } else {
            Label_desPRODUCTO.setText("Descripción");
            Label_desPRODUCTO.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_desPRODUCTOKeyReleased

    private void TextField_desPRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_desPRODUCTOKeyTyped
        //evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_desPRODUCTOKeyTyped

    private void TextField_canPRODUCTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_canPRODUCTOKeyReleased
        if (TextField_canPRODUCTO.getText().equals("")) {
            Label_canPRODUCTO.setForeground(new Color(102, 102, 102));
        } else {
            Label_canPRODUCTO.setText("Cantidad");
            Label_canPRODUCTO.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_canPRODUCTOKeyReleased

    private void TextField_canPRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_canPRODUCTOKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_canPRODUCTOKeyTyped

    private void TextField_pcPRODUCTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_pcPRODUCTOKeyReleased
        if (TextField_pcPRODUCTO.getText().equals("")) {
            Label_pcPRODUCTO.setForeground(new Color(102, 102, 102));
        } else {
            Label_pcPRODUCTO.setText("Precio compra");
            Label_pcPRODUCTO.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_pcPRODUCTOKeyReleased

    private void TextField_pcPRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_pcPRODUCTOKeyTyped
        evento.numberDecimalkeyPress(evt, TextField_pcPRODUCTO);
    }//GEN-LAST:event_TextField_pcPRODUCTOKeyTyped

    private void TextField_pvPRODUCTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_pvPRODUCTOKeyReleased
        if (TextField_pvPRODUCTO.getText().equals("")) {
            Label_pvPRODUCTO.setForeground(new Color(102, 102, 102));
        } else {
            Label_pvPRODUCTO.setText("Precio venta");
            Label_pvPRODUCTO.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_pvPRODUCTOKeyReleased

    private void TextField_pvPRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_pvPRODUCTOKeyTyped
        evento.numberDecimalkeyPress(evt, TextField_pvPRODUCTO);
    }//GEN-LAST:event_TextField_pvPRODUCTOKeyTyped

    private void TextField_pmPRODUCTOKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_pmPRODUCTOKeyReleased
        if (TextField_pmPRODUCTO.getText().equals("")) {
            Label_pmPRODUCTO.setForeground(new Color(102, 102, 102));
        } else {
            Label_pmPRODUCTO.setText("Precio mayorista");
            Label_pmPRODUCTO.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_pmPRODUCTOKeyReleased

    private void TextField_pmPRODUCTOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_pmPRODUCTOKeyTyped
        evento.numberDecimalkeyPress(evt, TextField_pmPRODUCTO);
    }//GEN-LAST:event_TextField_pmPRODUCTOKeyTyped

    public void actualizar() {
        if (validar() < 7) {

            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("FALTAN CAMPOS DE LLENAR");
            er.msj1.setText("");
            er.setVisible(true);

        } else {
            producto.Sentencias s = new Sentencias(cod, nom, des, pc, pv, pm, idprovedor, cantidad, tipo);
            s.setId(this.ids);

            int opcion = producto.Opciones.actualizar(s);
            if (opcion != 0) {

                producto.Opciones.listartodoProductos();

                SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                sa.titulo.setText("¡HECHO!");
                sa.msj.setText("SE HAN GUARDADO LOS CAMBIOS");
                sa.msj1.setText("");
                sa.setVisible(true);
            } else {
                System.out.println(s.toString());
            }
        }

    }
    private void Button_EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EditarActionPerformed
      
            actualizar();
            limpiar();
            this.cod = "";
            this.nom = "";
            this.des = "";
            this.pc = 0;
            this.pv = 0;
            this.pm = 0;
            this.cantidad = 0;
            this.idprovedor = 0;
            this.ids = 0;
//            Producto proveedor = productoController.findProducto(ids);
//            if (validar() == 7) {
//
//                System.out.println("valores : " + cod + nom + cantidad + des + pv + pc + pm);
//                proveedor.setCodigo(cod);
//
//                proveedor.setCantidad(cantidad);
//
//                proveedor.setDescripcion(des);
//
//                proveedor.setNombre(nom);
//
//                proveedor.setPvp(pv);
//                proveedor.setPcom(pc);
//
//                proveedor.setPmayor(pm);
//
//                proveedor.setProveedor(this.objeto);
//
//                productoController.edit(proveedor);
//                JOptionPane.showMessageDialog(null, "Actualizado exitosamente");
//                limpiar();
//                //LoadDates();
//                producto.Opciones.listartodoProductos();
//                this.Button_Guardar.setEnabled(true);
//                this.Button_Editar.setEnabled(false);
//
//                this.cod = "";
//                this.nom = "";
//                this.des = "";
//                this.pc = 0;
//                this.pv = 0;
//                this.pm = 0;
//                this.cantidad = 0;
//                this.idprovedor = 0;
//            }

        
        
    }//GEN-LAST:event_Button_EditarActionPerformed

    private void Button_SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SeleccionarActionPerformed
        this.Button_Guardar.setEnabled(false);
        this.Button_Editar.setEnabled(true);

        this.ids = Integer.parseInt((String) Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 0));

        String datos[] = new String[10];
        datos = producto.Opciones.buscarEdit(this.ids);

        //cant_pro, cod_pro, des_pro, nom_pro, pcom_pro,pmayor_pro,pvp_pro,id_proveedor,tipo
        TextField_canPRODUCTO.setText(datos[1]);
        TextField_CODPRODUCTO.setText(datos[2]);
        TextField_desPRODUCTO.setText(datos[3]);
        TextField_nomPRODUCTO.setText(datos[4]);
        TextField_pcPRODUCTO.setText(datos[5]);
        TextField_pmPRODUCTO.setText(datos[6]);
        TextField_pvPRODUCTO.setText(datos[7]);

        //TextField_empresaProveedor.setText(Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 8).toString());
    }//GEN-LAST:event_Button_SeleccionarActionPerformed

    private void TextField_BuscarProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_BuscarProveedorKeyTyped
        TextField_BuscarProveedor.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (TextField_BuscarProveedor.getText().toUpperCase());
                TextField_BuscarProveedor.setText(cadena);
                repaint();
                filtro(rowtable);
            }
        });
        trsfiltro = new TableRowSorter(Table_Proveedores.getModel());
        Table_Proveedores.setRowSorter(trsfiltro);
    }//GEN-LAST:event_TextField_BuscarProveedorKeyTyped

    private void Button_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EliminarActionPerformed
        try {
            int id_ad = Integer.parseInt((String) Table_Proveedores.getValueAt(Table_Proveedores.getSelectedRow(), 0));
            int elimina = Opciones.eliminar(id_ad);
            if (elimina != 0) {

                producto.Opciones.listartodoProductos();
                SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                sa.titulo.setText("¡HECHO!");
                sa.msj.setText("SE HA ELIMINADO UN");
                sa.msj1.setText("REGISTRO");
                sa.setVisible(true);
            }
            //productoController.destroy(id_ad);

            //LoadDates();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_Button_EliminarActionPerformed

    private void Button_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CancelarActionPerformed
        limpiar();
        this.Button_Guardar.setEnabled(true);
        this.Button_Editar.setEnabled(false);
    }//GEN-LAST:event_Button_CancelarActionPerformed

    private void combotipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotipoActionPerformed

    }//GEN-LAST:event_combotipoActionPerformed

    private void radiobarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiobarrasActionPerformed
        this.radiocategoria.setSelected(false);
        this.radionombre.setSelected(false);
        this.rowtable = 1;
    }//GEN-LAST:event_radiobarrasActionPerformed

    private void radionombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radionombreActionPerformed
        this.radiocategoria.setSelected(false);
        this.radiobarras.setSelected(false);
        this.rowtable = 2;
    }//GEN-LAST:event_radionombreActionPerformed

    private void radiocategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiocategoriaActionPerformed
        this.radionombre.setSelected(false);
        this.radiobarras.setSelected(false);
        this.rowtable = 4;
    }//GEN-LAST:event_radiocategoriaActionPerformed

    private void TextField_BuscarProveedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_BuscarProveedorKeyReleased

    }//GEN-LAST:event_TextField_BuscarProveedorKeyReleased

//    private void LoadDates() {
//        try {
//            Table_Proveedores.removeAll();
//            String[] titulos = {"id", "Codigo", "Nombre", "Descripcion", "Cantidad", "Precio compra", "Precio venta", "Precio x mayor"};
//            String[] registro = new String[9];
//            //Object o[] = null;
//            List<Producto> listproveedor = productoController.findProductoEntities();
//            modelo2 = new DefaultTableModel(null, titulos);
//
//            for (int i = 0; i < listproveedor.size(); i++) {
////                modelo2.addRow(o);
//                registro[0] = String.valueOf(listproveedor.get(i).getId());
//                registro[1] = listproveedor.get(i).getCodigo();
//                registro[2] = listproveedor.get(i).getNombre();
//                registro[3] = listproveedor.get(i).getDescripcion();
//                registro[4] = String.valueOf(listproveedor.get(i).getCantidad());
//                registro[5] = String.valueOf(listproveedor.get(i).getPcom());
//                registro[6] = String.valueOf(listproveedor.get(i).getPvp());
//                registro[7] = String.valueOf(listproveedor.get(i).getPmayor());
//                //registro[8] = listproveedor.get(i).getEmpresaProveedor();
//
//                //System.out.println(listLocal.get(i).getAdmin().toString());
//                modelo2.addRow(registro);
//            }
//            Table_Proveedores.setModel(modelo2);
//
//        } catch (Exception e) {
//            System.out.println(e.toString());
//        }
//
//    }
    public void buscar(String nombre) {
        System.out.println(nombre);
        for (Proveedor pro : this.add) {
            if (pro.getNomProveedor().equalsIgnoreCase(nombre)) {
                idprovedor = pro.getId();
                objeto = pro;
//                System.out.println(objeto.toString());
            }
            //comboProveedor.addItem(admin.getNombres());
        }
    }

    public void guardar() {

        if (validar() < 7) {

            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("FALTAN CAMPOS DE LLENAR");
            er.msj1.setText("");
            er.setVisible(true);

        } else {
            producto.Sentencias s = new Sentencias(cod, nom, des, pc, pv, pm, idprovedor, cantidad, tipo);

            int opcion = producto.Opciones.registrar(s);
            if (opcion != 0) {

                limpiar();
                SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                sa.titulo.setText("¡HECHO!");
                sa.msj.setText("SE HA REGISTRADO UN");
                sa.msj1.setText("NUEVO PRODUCTO");
                sa.setVisible(true);
                producto.Opciones.listartodoProductos();
            }

            //}
        }
    }

    private void saveCliente() {
        try {
            System.out.println("administrador recuperado    :  ");
//            Local local = new Local( nombre, provincia, canton, parroquia, calle, telefono, ruc, objeto);

            if (validar() == 7) {
                Producto producto = new Producto();

                producto.setCodigo(cod);
                producto.setNombre(nom);

                producto.setCantidad(cantidad);

                producto.setDescripcion(des);

                producto.setNombre(nom);

                producto.setPvp(pv);

                producto.setPmayor(pm);
                producto.setProveedor(this.objeto);
                productoController.create(producto);
                //LoadDates();
                JOptionPane.showMessageDialog(null, "Actualizado exitosamente");
            } else {
                JOptionPane.showMessageDialog(null, "Complete todos los campos");
            }

        } catch (Exception e) {
            System.out.println(e);
//            JOptionPane.showMessageDialog(null, e);
        }
    }

    private int validar() {
        int val = 0;
        if (TextField_nomPRODUCTO.getText().equals("")) {
            Label_nomPRODUCTO.setText("Ingrese nombre");
            Label_nomPRODUCTO.setForeground(Color.red);
            TextField_nomPRODUCTO.requestFocus();
        } else {
            val++;
            if (TextField_desPRODUCTO.getText().equals("")) {
                Label_desPRODUCTO.setText("Ingrese descripción");
                Label_desPRODUCTO.setForeground(Color.red);
                TextField_desPRODUCTO.requestFocus();
            } else {
                val++;
                if (TextField_canPRODUCTO.getText().equals("")) {
                    Label_canPRODUCTO.setText("Ingrese cantidad");
                    Label_canPRODUCTO.setForeground(Color.red);
                    TextField_canPRODUCTO.requestFocus();
                } else {
                    val++;
                    if (TextField_pcPRODUCTO.getText().equals("")) {
                        Label_pcPRODUCTO.setText("Ingrese precio compra");
                        Label_pcPRODUCTO.setForeground(Color.red);
                        TextField_pcPRODUCTO.requestFocus();
                    } else {
                        val++;
                        if (TextField_pvPRODUCTO.getText().equals("")) {
                            Label_pvPRODUCTO.setText("Ingrese precio venta");
                            Label_pvPRODUCTO.setForeground(Color.red);
                            TextField_pvPRODUCTO.requestFocus();
                        } else {
                            val++;
                            if (TextField_CODPRODUCTO.getText().equals("")) {
                                Label_codPRODUCTO.setText("Ingrese código");
                                Label_empresaProveedor.setForeground(Color.red);
                                TextField_CODPRODUCTO.requestFocus();
                            } else {
                                val++;
                                if (TextField_pmPRODUCTO.getText().equals("")) {
                                    Label_pmPRODUCTO.setText("Ingrese precio mayorista");
                                    Label_pmPRODUCTO.setForeground(Color.red);
                                    TextField_pmPRODUCTO.requestFocus();
                                } else {
                                    val++;
                                    if (acction.equals("insert")) {

                                        nom = TextField_nomPRODUCTO.getText().toUpperCase();
                                        cod = TextField_CODPRODUCTO.getText();
                                        des = TextField_desPRODUCTO.getText().toUpperCase();
                                        cantidad = Integer.parseInt(TextField_canPRODUCTO.getText());
                                        pc = Double.parseDouble(TextField_pcPRODUCTO.getText());
                                        pv = Double.parseDouble(TextField_pvPRODUCTO.getText());
                                        pm = Double.parseDouble(TextField_pmPRODUCTO.getText());
                                        idprovedor = extraerID(comboProveedor.getSelectedItem().toString());
                                        tipo = combotipo.getSelectedItem().toString().toUpperCase();
//                                    
                                    }
                                }

                            }

                        }

                    }

                }

            }
        }

        return val;
    }

    static PreparedStatement ps;

    public static int extraerID(String empresa) {

        int c = 0;
        String SQL = "SELECT id_proveedor FROM proveedores WHERE empresa_proveedor = '" + empresa + "'";

        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(SQL);
            while (rs.next()) {
                c = rs.getInt(1);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Opciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        return c;
    }

    private void limpiar() {
        TextField_nomPRODUCTO.setText("");
        TextField_CODPRODUCTO.setText("");
        TextField_desPRODUCTO.setText("");
        TextField_canPRODUCTO.setText("");
        TextField_pcPRODUCTO.setText("");
        TextField_pvPRODUCTO.setText("");
        TextField_pmPRODUCTO.setText("");
//        TextField_empresaProveedor.setText("");

        Label_nomPRODUCTO.setForeground(new Color(102, 102, 102));
        Label_codPRODUCTO.setForeground(new Color(102, 102, 102));
        Label_desPRODUCTO.setForeground(new Color(102, 102, 102));
        Label_canPRODUCTO.setForeground(new Color(102, 102, 102));
        Label_pcPRODUCTO.setForeground(new Color(102, 102, 102));
        Label_pvPRODUCTO.setForeground(new Color(102, 102, 102));
        Label_pmPRODUCTO.setForeground(new Color(102, 102, 102));
        Label_empresaProveedor.setForeground(new Color(102, 102, 102));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Cancelar;
    private javax.swing.JButton Button_Editar;
    private javax.swing.JButton Button_Eliminar;
    private javax.swing.JButton Button_Guardar;
    private javax.swing.JButton Button_Limpiar;
    private javax.swing.JButton Button_Seleccionar;
    private javax.swing.JLabel Label_canPRODUCTO;
    private javax.swing.JLabel Label_codPRODUCTO;
    private javax.swing.JLabel Label_desPRODUCTO;
    private javax.swing.JLabel Label_empresaProveedor;
    private javax.swing.JLabel Label_nomPRODUCTO;
    private javax.swing.JLabel Label_pcPRODUCTO;
    private javax.swing.JLabel Label_pmPRODUCTO;
    private javax.swing.JLabel Label_productoTipo;
    private javax.swing.JLabel Label_pvPRODUCTO;
    public static javax.swing.JTable Table_Proveedores;
    private javax.swing.JTextField TextField_BuscarProveedor;
    private javax.swing.JTextField TextField_CODPRODUCTO;
    private javax.swing.JTextField TextField_canPRODUCTO;
    private javax.swing.JTextField TextField_desPRODUCTO;
    private javax.swing.JTextField TextField_nomPRODUCTO;
    private javax.swing.JTextField TextField_pcPRODUCTO;
    private javax.swing.JTextField TextField_pmPRODUCTO;
    private javax.swing.JTextField TextField_pvPRODUCTO;
    private javax.swing.JComboBox<String> comboProveedor;
    private javax.swing.JComboBox<String> combotipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton radiobarras;
    private javax.swing.JRadioButton radiocategoria;
    private javax.swing.JRadioButton radionombre;
    // End of variables declaration//GEN-END:variables
}
