/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import java.awt.Color;
import ModelClass.TextFieldEven;
import alertas.principal.ErrorAlert;
import alertas.principal.SuccessAlert;
import controllers.AdministradorJpaController;
import controllers.Controlador;
import controllers.LocalJpaController;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.*;
import java.sql.Array;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentListener;
import javax.swing.event.UndoableEditListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.Element;
import javax.swing.text.Position;
import javax.swing.text.Segment;
import models.Administrador;
import models.Local;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import ventas.ClientesVenta;
import ventas.Opciones;
import ventas.ProductoReport;
import ventas.Productos;
import ventas.Sentencias;

/**
 *
 * @author RojeruSan
 */
public class PnlVentas extends javax.swing.JPanel {

    /**
     * Creates new form pnlHome
     */
    private String acction = "insert";
    private String ci = "";
    private String ruc = "";
    private String nombre = "";
    private String apellido = "";
    private String direccion = "";
    private String telefono = "";
    private String email = "";
    private float descuento = 0;

    private int idAdmin;
    TextFieldEven evento = new TextFieldEven();

    DefaultTableModel modelo2;

    int ids;
    private TableRowSorter trsfiltro;

    public PnlVentas() {
        initComponents();
        limpiaCampos();
        TextField_CiClienteVenta.setEditable(false);
        TextField_rucClienteVenta.setEditable(false);
        TextField_NombreClienteVenta.setEditable(false);
        TextField_ApellidioClienteVenta.setEditable(false);
        TextField_DireccioClienteVenta.setEditable(false);
        TextField_TelefonoClienteVenta.setEditable(false);
        this.cheCliente.setSelected(false);
        Opciones.numeros();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVentas =   tablaVentas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };
        jPanel33 = new javax.swing.JPanel();
        txtImporte = new app.bolivia.swing.JCTextField();
        jLabel33 = new javax.swing.JLabel();
        txtCambio = new app.bolivia.swing.JCTextField();
        jLabel34 = new javax.swing.JLabel();
        lblsubTotal1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblvaTotal2 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        btnVender = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        TextField_rucClienteVenta = new javax.swing.JTextField();
        Label_ciCliente = new javax.swing.JLabel();
        TextField_CiClienteVenta = new javax.swing.JTextField();
        Label_NombreCliente = new javax.swing.JLabel();
        TextField_NombreClienteVenta = new javax.swing.JTextField();
        Label_ApellidoCliente = new javax.swing.JLabel();
        TextField_ApellidioClienteVenta = new javax.swing.JTextField();
        Label_DireccionCliente = new javax.swing.JLabel();
        TextField_DireccioClienteVenta = new javax.swing.JTextField();
        Label_TelefonoCliente = new javax.swing.JLabel();
        TextField_TelefonoClienteVenta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Label_rucCliente1 = new javax.swing.JLabel();
        lbcod_cli = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        numVenta = new javax.swing.JLabel();
        txtFecha = new app.bolivia.swing.JCTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        cheCliente = new javax.swing.JCheckBox();
        cheConsumidor = new javax.swing.JCheckBox();
        btnclientes = new javax.swing.JButton();
        jPanel39 = new javax.swing.JPanel();
        Buscar = new materialdesing.MaterialButtomRectangle();

        jMenuItem1.setText("Quitar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel30.setBackground(new java.awt.Color(255, 255, 255));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel31.setBackground(new java.awt.Color(80, 80, 97));

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("VENTAS");

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addContainerGap(997, Short.MAX_VALUE))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel30.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 50));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaVentas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Código", "descripcion", "cantidad", "valor unitario", "valor total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVentas.setComponentPopupMenu(jPopupMenu1);
        tablaVentas.setRowHeight(20);
        tablaVentas.setSelectionBackground(new java.awt.Color(102, 204, 255));
        jScrollPane2.setViewportView(tablaVentas);
        if (tablaVentas.getColumnModel().getColumnCount() > 0) {
            tablaVentas.getColumnModel().getColumn(0).setPreferredWidth(6);
            tablaVentas.getColumnModel().getColumn(1).setPreferredWidth(50);
            tablaVentas.getColumnModel().getColumn(2).setResizable(false);
            tablaVentas.getColumnModel().getColumn(3).setPreferredWidth(12);
            tablaVentas.getColumnModel().getColumn(4).setPreferredWidth(13);
            tablaVentas.getColumnModel().getColumn(5).setPreferredWidth(13);
        }

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 810, 330));

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtImporte.setBorder(null);
        txtImporte.setForeground(new java.awt.Color(80, 80, 97));
        txtImporte.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        txtImporte.setPlaceholder("IMPORTE");
        txtImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImporteKeyTyped(evt);
            }
        });
        jPanel33.add(txtImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));
        jPanel33.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 180, -1));

        txtCambio.setEditable(false);
        txtCambio.setBorder(null);
        txtCambio.setForeground(new java.awt.Color(80, 80, 97));
        txtCambio.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        txtCambio.setPlaceholder("CAMBIO");
        txtCambio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCambioKeyTyped(evt);
            }
        });
        jPanel33.add(txtCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 110, 30));
        jPanel33.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 180, -1));

        jPanel7.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 310, 48));

        lblsubTotal1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblsubTotal1.setForeground(new java.awt.Color(0, 204, 0));
        lblsubTotal1.setText("0.0");
        jPanel7.add(lblsubTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 145, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sub Total:");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 105, 33));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Iva : ");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 75, 33));

        lblvaTotal2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblvaTotal2.setForeground(new java.awt.Color(0, 204, 0));
        lblvaTotal2.setText("0.0");
        jPanel7.add(lblvaTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 95, -1));

        jPanel30.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 840, 430));

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnVender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsaletr/icons8-paid-28.png"))); // NOI18N
        btnVender.setText("Vender");
        btnVender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsaletr/icons8-print-28.png"))); // NOI18N
        jButton2.setText("Imprimir");
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsaletr/icons8-clear-shopping-cart-28.png"))); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel35Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel30.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 440, 220, 180));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextField_rucClienteVenta.setText("0000000001");
        TextField_rucClienteVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_rucClienteVentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_rucClienteVentaKeyTyped(evt);
            }
        });
        jPanel8.add(TextField_rucClienteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 55, 188, -1));

        Label_ciCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_ciCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_ciCliente.setText("CI");
        Label_ciCliente.setToolTipText("");
        jPanel8.add(Label_ciCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 81, 188, -1));

        TextField_CiClienteVenta.setText("0000000001");
        TextField_CiClienteVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_CiClienteVentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_CiClienteVentaKeyTyped(evt);
            }
        });
        jPanel8.add(TextField_CiClienteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 102, 188, -1));

        Label_NombreCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_NombreCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_NombreCliente.setText("Nombre completo");
        Label_NombreCliente.setToolTipText("");
        jPanel8.add(Label_NombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 128, 188, -1));

        TextField_NombreClienteVenta.setText("Consumidor");
        TextField_NombreClienteVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_NombreClienteVentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_NombreClienteVentaKeyTyped(evt);
            }
        });
        jPanel8.add(TextField_NombreClienteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 149, 188, -1));

        Label_ApellidoCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_ApellidoCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_ApellidoCliente.setText("Apellido");
        jPanel8.add(Label_ApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 175, 188, -1));

        TextField_ApellidioClienteVenta.setText("Final");
        TextField_ApellidioClienteVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_ApellidioClienteVentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_ApellidioClienteVentaKeyTyped(evt);
            }
        });
        jPanel8.add(TextField_ApellidioClienteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 196, 188, -1));

        Label_DireccionCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_DireccionCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_DireccionCliente.setText("Dirección");
        Label_DireccionCliente.setToolTipText("");
        jPanel8.add(Label_DireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 222, 188, -1));

        TextField_DireccioClienteVenta.setText("S/N");
        TextField_DireccioClienteVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_DireccioClienteVentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_DireccioClienteVentaKeyTyped(evt);
            }
        });
        jPanel8.add(TextField_DireccioClienteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 243, 188, -1));

        Label_TelefonoCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_TelefonoCliente.setForeground(new java.awt.Color(102, 102, 102));
        Label_TelefonoCliente.setText("Teléfono");
        jPanel8.add(Label_TelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 269, 188, -1));

        TextField_TelefonoClienteVenta.setText("0000000000");
        TextField_TelefonoClienteVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TextField_TelefonoClienteVentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_TelefonoClienteVentaKeyTyped(evt);
            }
        });
        jPanel8.add(TextField_TelefonoClienteVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 290, 188, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(80, 80, 97));
        jLabel5.setText("Datos del cliente");
        jLabel5.setToolTipText("");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 13, -1, -1));

        Label_rucCliente1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Label_rucCliente1.setForeground(new java.awt.Color(102, 102, 102));
        Label_rucCliente1.setText("Ruc");
        Label_rucCliente1.setToolTipText("");
        jPanel8.add(Label_rucCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 34, 180, -1));

        lbcod_cli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbcod_cli.setForeground(new java.awt.Color(102, 102, 102));
        lbcod_cli.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbcod_cli.setText("0");
        lbcod_cli.setToolTipText("");
        jPanel8.add(lbcod_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 10, 50, 20));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsaletr/icons8-add-user-male-28.png"))); // NOI18N
        jButton3.setText("Guardar");
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 40));

        jPanel30.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 55, 220, 380));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel34.setBackground(new java.awt.Color(0, 0, 0));
        jPanel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel34.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));
        jPanel34.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 60, 10));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 204, 0));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("TOTAL A PAGAR: $");
        jPanel34.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 189, 30));

        lblTotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 204, 0));
        lblTotal.setText("0.0");
        jPanel34.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 140, 50));

        jPanel6.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 100));

        jPanel30.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 55, 350, 120));

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fecha");

        numVenta.setBackground(new java.awt.Color(255, 255, 255));
        numVenta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        numVenta.setForeground(new java.awt.Color(153, 153, 153));
        numVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numVenta.setText("NO. VENTA");

        txtFecha.setEditable(false);
        txtFecha.setBorder(null);
        txtFecha.setForeground(new java.awt.Color(51, 51, 51));
        txtFecha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtFecha.setPlaceholder("FECHA");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("N° venta");

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(numVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel32Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        jPanel30.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 55, 457, 50));

        jPanel38.setBackground(new java.awt.Color(255, 255, 255));
        jPanel38.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cheCliente.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cheCliente.setText("Cliente");
        cheCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheClienteActionPerformed(evt);
            }
        });
        jPanel38.add(cheCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 17, -1, -1));

        cheConsumidor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cheConsumidor.setText("Cosumidor final");
        cheConsumidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheConsumidorActionPerformed(evt);
            }
        });
        jPanel38.add(cheConsumidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 17, -1, -1));

        btnclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsaletr/icons8-find-user-male-24.png"))); // NOI18N
        btnclientes.setText("...");
        btnclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclientesActionPerformed(evt);
            }
        });
        jPanel38.add(btnclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 12, 50, 30));

        jPanel30.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 260, 60));

        jPanel39.setBackground(new java.awt.Color(255, 255, 255));
        jPanel39.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscar.setBackground(new java.awt.Color(0, 153, 204));
        Buscar.setForeground(new java.awt.Color(255, 255, 255));
        Buscar.setText("Buscar producto");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel39.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, 40));

        jPanel30.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 110, 190, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, 1097, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

//    private void LoadDates() {
//        try {
//            tablaVentas.removeAll();
//            String[] titulos = {"id", "Ruc", "Nombre", "Provincia", "Cantón", "Parroquia", "Calle", "Teléfono", "idAdmin"};
//            String[] registro = new String[9];
//            //Object o[] = null;
//            List<Local> listLocal = localController.findLocalEntities();
//            modelo2 = new DefaultTableModel(null, titulos);
//
//            for (int i = 0; i < listLocal.size(); i++) {
////                modelo2.addRow(o);
//                registro[0] = String.valueOf(listLocal.get(i).getId());
//                registro[1] = listLocal.get(i).getRuc();
//                registro[2] = listLocal.get(i).getNombre();
//                registro[3] = listLocal.get(i).getProvincia();
//                registro[4] = listLocal.get(i).getCanton();
//                registro[5] = listLocal.get(i).getParroquia();
//                registro[6] = listLocal.get(i).getCalle();
//                registro[7] = listLocal.get(i).getTelefono();
//                registro[8] = String.valueOf(listLocal.get(i).getAdmin().getId());
//                //System.out.println(listLocal.get(i).getAdmin().toString());
//                modelo2.addRow(registro);
//            }
//            tablaVentas.setModel(modelo2);
//
//        } catch (Exception e) {
//            System.out.println(e.toString());
//        }
//
//    }

    private void txtImporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImporteKeyTyped
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();
        }
        if ((num == KeyEvent.VK_ENTER)) {
            if (this.txtImporte.getText().equals("")) {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("OOPS...");
                er.msj.setText("DEBES INGRESAR UNA");
                er.msj1.setText("CANTIDAD");
                er.setVisible(true);
            } else {
                double recibe = Double.parseDouble(txtImporte.getText());
                double total = Double.parseDouble(lblTotal.getText());

                if (total > 0.0) {
                    if (recibe > total) {
                        this.txtCambio.setText(String.valueOf(recibe - total));
                    } else {
                        ErrorAlert er = new ErrorAlert(new JFrame(), true);
                        er.titulo.setText("OOPS...");
                        er.msj.setText("INGRESA UNA CANTIDAD");
                        er.msj1.setText("VALIDA");
                        er.setVisible(true);
                    }
                } else {
                    ErrorAlert er = new ErrorAlert(new JFrame(), true);
                    er.titulo.setText("OOPS...");
                    er.msj.setText("IMPOSIBLE REALIZAR");
                    er.msj1.setText("LA OPERACIÓN");
                    er.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_txtImporteKeyTyped

    private void txtCambioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCambioKeyTyped
        char num = evt.getKeyChar();
        if ((num < '0' || num > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCambioKeyTyped

    private void TextField_rucClienteVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_rucClienteVentaKeyReleased
        if (TextField_rucClienteVenta.getText().equals("")) {
            Label_rucCliente1.setForeground(new Color(102, 102, 102));
        } else {
            Label_rucCliente1.setText("Ruc");
            Label_rucCliente1.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_rucClienteVentaKeyReleased

    private void TextField_rucClienteVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_rucClienteVentaKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_rucClienteVentaKeyTyped

    private void TextField_CiClienteVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CiClienteVentaKeyReleased
        if (TextField_CiClienteVenta.getText().equals("")) {
            Label_ciCliente.setForeground(new Color(102, 102, 102));
        } else {
            Label_ciCliente.setText("CI");
            Label_ciCliente.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_CiClienteVentaKeyReleased

    private void TextField_CiClienteVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_CiClienteVentaKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_CiClienteVentaKeyTyped

    private void TextField_NombreClienteVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_NombreClienteVentaKeyReleased
        if (TextField_NombreClienteVenta.getText().equals("")) {
            Label_NombreCliente.setForeground(new Color(102, 102, 102));
        } else {
            Label_NombreCliente.setText("Nombres completos");
            Label_NombreCliente.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_NombreClienteVentaKeyReleased

    private void TextField_NombreClienteVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_NombreClienteVentaKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_NombreClienteVentaKeyTyped

    private void TextField_ApellidioClienteVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ApellidioClienteVentaKeyReleased
        if (TextField_ApellidioClienteVenta.getText().equals("")) {
            Label_ApellidoCliente.setForeground(new Color(102, 102, 102));
        } else {
            Label_ApellidoCliente.setText("Apellidos");
            Label_ApellidoCliente.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_ApellidioClienteVentaKeyReleased

    private void TextField_ApellidioClienteVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ApellidioClienteVentaKeyTyped
        evento.textkeyPress(evt);
    }//GEN-LAST:event_TextField_ApellidioClienteVentaKeyTyped

    private void TextField_DireccioClienteVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_DireccioClienteVentaKeyReleased
        if (TextField_DireccioClienteVenta.getText().equals("")) {
            Label_DireccionCliente.setForeground(new Color(102, 102, 102));
        } else {
            Label_DireccionCliente.setText("Dirección");
            Label_DireccionCliente.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_DireccioClienteVentaKeyReleased

    private void TextField_DireccioClienteVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_DireccioClienteVentaKeyTyped

    }//GEN-LAST:event_TextField_DireccioClienteVentaKeyTyped

    private void TextField_TelefonoClienteVentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_TelefonoClienteVentaKeyReleased
        if (TextField_TelefonoClienteVenta.getText().equals("")) {
            Label_TelefonoCliente.setForeground(new Color(102, 102, 102));
        } else {
            Label_TelefonoCliente.setText("Teléfono");
            Label_TelefonoCliente.setForeground(new Color(0, 153, 51));
        }
    }//GEN-LAST:event_TextField_TelefonoClienteVentaKeyReleased

    private void TextField_TelefonoClienteVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_TelefonoClienteVentaKeyTyped
        evento.numberkeyPress(evt);
    }//GEN-LAST:event_TextField_TelefonoClienteVentaKeyTyped

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        new ventas.Productos(new JFrame(), true).setVisible(true);
    }//GEN-LAST:event_BuscarActionPerformed
    void limpiaCampos() {
        DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();

        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        lblvaTotal2.setText("");
        lblsubTotal1.setText("");
        txtImporte.setText("");
        txtCambio.setText("");
        lblTotal.setText("0.0");
        TextField_CiClienteVenta.setText("");
        TextField_rucClienteVenta.setText("");
        TextField_NombreClienteVenta.setText("");
        TextField_ApellidioClienteVenta.setText("");
        TextField_DireccioClienteVenta.setText("");
        TextField_TelefonoClienteVenta.setText("");
        lbcod_cli.setText("");
        txtFecha.setText(fechaactual());
        Opciones.numerosVenta();

    }

    public static String fechaactual() {
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("YYYY/MM/dd");
        return formatofecha.format(fecha);
    }

    public void ventaEvento1() {
        if (this.tablaVentas.getRowCount() < 1) {
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("IMPOSIBLE REALIZAR");
            er.msj1.setText("LA VENTA");
            er.setVisible(true);
        } else {
            Sentencias s = new Sentencias();
            int contador = 0;

            //id_venta	fecha_venta	cantidad	num_venta	total	id_caja	,id_factura	precio_unitario,
            for (int i = 0; i < this.tablaVentas.getRowCount(); i++) {

                s.setId_producto(Integer.parseInt(this.tablaVentas.getValueAt(i, 0).toString()));
                s.setCantidad(Integer.parseInt(this.tablaVentas.getValueAt(i, 3).toString()));

                s.setPrecioUnitario(Double.parseDouble(this.tablaVentas.getValueAt(i, 4).toString()));
                s.setTotal(Double.parseDouble(this.tablaVentas.getValueAt(i, 5).toString()));
                s.setFecha(this.txtFecha.getText());
                s.setNumFactura(Integer.parseInt(this.numVenta.getText()));
                s.setId_caja(1);
                s.setId_factura(1);
                System.out.println(s.toString());
                int opcion = ventas.Opciones.registrar(s);
                if (opcion != 0) {
                    contador++;
                }

            }

            if (contador == this.tablaVentas.getRowCount()) {
                limpiaCampos();
                //producto.Opciones.finalizarTransaccion();
                SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                sa.titulo.setText("¡HECHO!");
                sa.msj.setText("VENTA REALIZADA CON");
                sa.msj1.setText("ÉXITO");
                sa.setVisible(true);
            }
        }
    }
    private void cheConsumidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheConsumidorActionPerformed
        TextField_CiClienteVenta.setEditable(false);
        TextField_rucClienteVenta.setEditable(false);
        TextField_NombreClienteVenta.setEditable(false);
        TextField_ApellidioClienteVenta.setEditable(false);
        TextField_DireccioClienteVenta.setEditable(false);
        TextField_TelefonoClienteVenta.setEditable(false);

        TextField_CiClienteVenta.setText("0000000001");
        TextField_rucClienteVenta.setText("0000000001");
        TextField_NombreClienteVenta.setText("CONSUMIDOR");
        TextField_ApellidioClienteVenta.setText("FINAL");
        TextField_DireccioClienteVenta.setText("S/N");
        TextField_TelefonoClienteVenta.setText("000000000");
        this.cheCliente.setSelected(false);
    }//GEN-LAST:event_cheConsumidorActionPerformed

    private void cheClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheClienteActionPerformed
        TextField_CiClienteVenta.setEditable(true);
        TextField_rucClienteVenta.setEditable(true);
        TextField_NombreClienteVenta.setEditable(true);
        TextField_ApellidioClienteVenta.setEditable(true);
        TextField_DireccioClienteVenta.setEditable(true);
        TextField_TelefonoClienteVenta.setEditable(true);

        TextField_CiClienteVenta.setText("");
        TextField_rucClienteVenta.setText("");
        TextField_NombreClienteVenta.setText("");
        TextField_ApellidioClienteVenta.setText("");
        TextField_DireccioClienteVenta.setText("");
        TextField_TelefonoClienteVenta.setText("");
        this.cheConsumidor.setSelected(false);
    }//GEN-LAST:event_cheClienteActionPerformed

    private void btnclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclientesActionPerformed
        // TODO add your handling code here:
        new ventas.ClientesVenta(new JFrame(), true).setVisible(true);

    }//GEN-LAST:event_btnclientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();
        int fila = tablaVentas.getSelectedRow();
        if (fila >= 0) {
            modelo.removeRow(fila);
            Opciones.calcular();
        } else {
            JOptionPane.showMessageDialog(null, "No Selecciono ninguna fila");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        if ((lblsubTotal1.getText().equals(""))) {
            //JOptionPane.showMessageDialog(this, "No ingreso cliente,productos o realice operacion");
            ErrorAlert er = new ErrorAlert(new JFrame(), true);
            er.titulo.setText("No se encontraron productos");
            er.msj.setText("La venta no");
            er.msj1.setText("se puede realizar");
            er.setVisible(true);

        } else {
            String capcod = "", capcan = "";
            int contador = 0;

            for (int i = 0; i < tablaVentas.getRowCount(); i++) {
                capcod = tablaVentas.getValueAt(i, 0).toString();
                capcan = tablaVentas.getValueAt(i, 3).toString();
                Opciones.descontarstock(capcod, capcan);
                contador++;

            }
            Opciones.factura();
            Opciones.detallefactura();

            if (contador == this.tablaVentas.getRowCount()) {
                limpiaCampos();
                //producto.Opciones.finalizarTransaccion();
                SuccessAlert sa = new SuccessAlert(new JFrame(), true);
                sa.titulo.setText("¡HECHO!");
                sa.msj.setText("VENTA REALIZADA CON");
                sa.msj1.setText("ÉXITO");
                sa.setVisible(true);

                limpiaCampos();

                DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();
                int a = tablaVentas.getRowCount() - 1;
                int i;
                for (i = a; i >= 0; i--) {
                    modelo.removeRow(i);
                }

                Opciones.numeros();
            }

        }
    }//GEN-LAST:event_btnVenderActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            List<ProductoReport> listaProductos = new ArrayList<ProductoReport>();
            int filas = tablaVentas.getRowCount();
            for (int i = 0; i < filas; i++) {
                ProductoReport p = new ProductoReport(tablaVentas.getValueAt(i, 1).toString(), tablaVentas.getValueAt(i, 2).toString(), tablaVentas.getValueAt(i, 3).toString(), tablaVentas.getValueAt(i, 4).toString(), tablaVentas.getValueAt(i, 5).toString());
                listaProductos.add(p);
            }

            JasperReport reporte = (JasperReport) JRLoader.loadObject("ImprFac.jasper");

            Map<String, String> parametros = new HashMap<String, String>();
            parametros.put("nunfac", numVenta.getText());
            parametros.put("nomape", TextField_NombreClienteVenta.getText() + " " + TextField_ApellidioClienteVenta.getText());
            parametros.put("codigo", lbcod_cli.getText());
            parametros.put("dni", TextField_CiClienteVenta.getText());
            parametros.put("direccion", TextField_DireccioClienteVenta.getText());
            parametros.put("ruc", TextField_rucClienteVenta.getText());
            parametros.put("fecha", txtFecha.getText());
            parametros.put("subtotal", lblsubTotal1.getText());
            parametros.put("iva", lblvaTotal2.getText());
            parametros.put("total", lblTotal.getText());

            JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, parametros, new JRBeanCollectionDataSource(listaProductos));
            JasperViewer.viewReport(jasperPrint, false);
            JRExporter exporter = new JRPdfExporter();
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, jasperPrint);
            exporter.setParameter(JRExporterParameter.OUTPUT_FILE, new java.io.File("reportesproductos.pdf"));
            exporter.exportReport();
        } catch (JRException ex) {
            Logger.getLogger(PnlVentas.class.getName()).log(Level.SEVERE, null, ex);
        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String existente[] = new String[2];

        if (validar() == 5) {
            existente = clientes.Opciones.BuscarCliente(TextField_CiClienteVenta.getText());
            if (TextField_CiClienteVenta.getText().equalsIgnoreCase(existente[1])) {
                JOptionPane.showMessageDialog(null, "El cliente actualmente existe");

            } else {
                saveCliente();

                JOptionPane.showMessageDialog(null, "Guardado exitosamente");
                this.ci = "";
                this.ruc = "";
                this.nombre = "";
                this.apellido = "";
                this.direccion = "";
                this.telefono = "";
                this.email = "";
                this.descuento = 0;
            }

        } else {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) this.tablaVentas.getModel();
        int id, cant, can_ante, rol;
        producto.Sentencias s = new producto.Sentencias();
        if (modelo.getRowCount() > 0) {

            int fila = this.tablaVentas.getSelectedRow();
            if (this.tablaVentas.getSelectedRowCount() < 1) {
                ErrorAlert er = new ErrorAlert(new JFrame(), true);
                er.titulo.setText("OOPS...");
                er.msj.setText("SELECCIONA UN");
                er.msj1.setText("REGISTRO");
                er.setVisible(true);
            } else {
                if (this.tablaVentas.getRowCount() == 1) {
                    id = Integer.parseInt(this.tablaVentas.getValueAt(0, 0).toString());
                    cant = Integer.parseInt(this.tablaVentas.getValueAt(0, 3).toString());
                } else {
                    id = Integer.parseInt(this.tablaVentas.getValueAt(this.tablaVentas.getSelectedRowCount(), 0).toString());
                    cant = Integer.parseInt(this.tablaVentas.getValueAt(this.tablaVentas.getSelectedRowCount(), 3).toString());
                }

                can_ante = producto.Opciones.extraerCantidad(id);
                rol = cant + can_ante;
                s.setCantidad(rol);
                s.setId(id);
                int opcion = producto.Opciones.actualizarStock(s);

                modelo.removeRow(fila);
                Opciones.calcular();

            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void limpiar() {
        TextField_CiClienteVenta.setText("");
        TextField_rucClienteVenta.setText("");
        TextField_NombreClienteVenta.setText("");
        TextField_ApellidioClienteVenta.setText("");
        TextField_DireccioClienteVenta.setText("");
        TextField_TelefonoClienteVenta.setText("");

        Label_ciCliente.setForeground(new Color(102, 102, 102));
        lbcod_cli.setForeground(new Color(102, 102, 102));
        Label_NombreCliente.setForeground(new Color(102, 102, 102));
        Label_ApellidoCliente.setForeground(new Color(102, 102, 102));
        Label_DireccionCliente.setForeground(new Color(102, 102, 102));
        Label_TelefonoCliente.setForeground(new Color(102, 102, 102));

    }

    private int validar() {
        int val = 0;
        if (TextField_CiClienteVenta.getText().equals("")) {
            Label_ciCliente.setText("Ingrese CI");
            Label_ciCliente.setForeground(Color.red);
            TextField_CiClienteVenta.requestFocus();
        } else {
            val++;
            if (TextField_NombreClienteVenta.getText().equals("")) {
                Label_NombreCliente.setText("Ingrese el nombre");
                Label_NombreCliente.setForeground(Color.red);
                TextField_NombreClienteVenta.requestFocus();
            } else {
                val++;
                if (TextField_ApellidioClienteVenta.getText().equals("")) {
                    Label_ApellidoCliente.setText("Ingrese el apellido");
                    Label_ApellidoCliente.setForeground(Color.red);
                    TextField_ApellidioClienteVenta.requestFocus();
                } else {
                    val++;
                    if (TextField_DireccioClienteVenta.getText().equals("")) {
                        Label_DireccionCliente.setText("Ingrese la dirección");
                        Label_DireccionCliente.setForeground(Color.red);
                        TextField_DireccioClienteVenta.requestFocus();
                    } else {
                        val++;
                        if (TextField_TelefonoClienteVenta.getText().equals("")) {
                            Label_TelefonoCliente.setText("Ingrese el teléfono");
                            Label_TelefonoCliente.setForeground(Color.red);
                            TextField_TelefonoClienteVenta.requestFocus();
                        } else {
                            val++;
                            if (acction.equals("insert")) {
                                ci = TextField_CiClienteVenta.getText();
                                ruc = TextField_rucClienteVenta.getText();
                                nombre = TextField_NombreClienteVenta.getText().toUpperCase();
                                apellido = TextField_ApellidioClienteVenta.getText().toUpperCase();
                                direccion = TextField_DireccioClienteVenta.getText().toUpperCase();
                                telefono = TextField_TelefonoClienteVenta.getText();

                            }

                        }

                    }

                }

            }
        }

        return val;
    }

    private void saveCliente() {
        String idcliente[] = new String[2];
        
        clientes.Sentencias sentecia = new clientes.Sentencias(ci, nombre, ruc, direccion, apellido, telefono);
        clientes.Opciones.registrar(sentecia);
        idcliente = clientes.Opciones.BuscarCliente(TextField_CiClienteVenta.getText());
        JOptionPane.showMessageDialog(null, idcliente[0]);
        lbcod_cli.setText(idcliente[0]);

    }

    private int validarCliente() {
        int val = 0;
        if (TextField_CiClienteVenta.getText().equals("")) {
            Label_ciCliente.setText("Ingrese CI");
            Label_ciCliente.setForeground(Color.red);
            TextField_CiClienteVenta.requestFocus();
        } else {
            val++;
            if (TextField_NombreClienteVenta.getText().equals("")) {
                Label_NombreCliente.setText("Ingrese el nombre");
                Label_NombreCliente.setForeground(Color.red);
                TextField_NombreClienteVenta.requestFocus();
            } else {
                val++;
                if (TextField_ApellidioClienteVenta.getText().equals("")) {
                    Label_ApellidoCliente.setText("Ingrese el apellido");
                    Label_ApellidoCliente.setForeground(Color.red);
                    TextField_ApellidioClienteVenta.requestFocus();
                } else {
                    val++;
                    if (TextField_DireccioClienteVenta.getText().equals("")) {
                        Label_DireccionCliente.setText("Ingrese la dirección");
                        Label_DireccionCliente.setForeground(Color.red);
                        TextField_DireccioClienteVenta.requestFocus();
                    } else {
                        val++;
                        if (TextField_TelefonoClienteVenta.getText().equals("")) {
                            Label_TelefonoCliente.setText("Ingrese el teléfono");
                            Label_TelefonoCliente.setForeground(Color.red);
                            TextField_TelefonoClienteVenta.requestFocus();
                        } else {
                            val++;
                            if (acction.equals("insert")) {
                                ci = TextField_CiClienteVenta.getText();
                                ruc = TextField_rucClienteVenta.getText();
                                nombre = TextField_NombreClienteVenta.getText().toUpperCase();
                                apellido = TextField_ApellidioClienteVenta.getText().toUpperCase();
                                direccion = TextField_DireccioClienteVenta.getText().toUpperCase();
                                telefono = TextField_TelefonoClienteVenta.getText();

                            }

                        }

                    }

                }

            }
        }

        return val;
    }

    private void limpiarCliente() {
        TextField_CiClienteVenta.setText("");
        TextField_rucClienteVenta.setText("");
        TextField_NombreClienteVenta.setText("");
        TextField_ApellidioClienteVenta.setText("");
        TextField_DireccioClienteVenta.setText("");
        TextField_TelefonoClienteVenta.setText("");

        Label_ciCliente.setForeground(new Color(102, 102, 102));
        Label_rucCliente1.setForeground(new Color(102, 102, 102));
        Label_NombreCliente.setForeground(new Color(102, 102, 102));
        Label_ApellidoCliente.setForeground(new Color(102, 102, 102));
        Label_DireccionCliente.setForeground(new Color(102, 102, 102));
        Label_TelefonoCliente.setForeground(new Color(102, 102, 102));

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private materialdesing.MaterialButtomRectangle Buscar;
    private javax.swing.JLabel Label_ApellidoCliente;
    private javax.swing.JLabel Label_DireccionCliente;
    private javax.swing.JLabel Label_NombreCliente;
    private javax.swing.JLabel Label_TelefonoCliente;
    private javax.swing.JLabel Label_ciCliente;
    private javax.swing.JLabel Label_rucCliente1;
    public static javax.swing.JTextField TextField_ApellidioClienteVenta;
    public static javax.swing.JTextField TextField_CiClienteVenta;
    public static javax.swing.JTextField TextField_DireccioClienteVenta;
    public static javax.swing.JTextField TextField_NombreClienteVenta;
    public static javax.swing.JTextField TextField_TelefonoClienteVenta;
    public static javax.swing.JTextField TextField_rucClienteVenta;
    private javax.swing.JButton btnVender;
    private javax.swing.JButton btnclientes;
    private javax.swing.JCheckBox cheCliente;
    private javax.swing.JCheckBox cheConsumidor;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel lbcod_cli;
    public static javax.swing.JLabel lblTotal;
    public static javax.swing.JLabel lblsubTotal1;
    public static javax.swing.JLabel lblvaTotal2;
    public static javax.swing.JLabel numVenta;
    public static javax.swing.JTable tablaVentas;
    public static app.bolivia.swing.JCTextField txtCambio;
    public static app.bolivia.swing.JCTextField txtFecha;
    public static app.bolivia.swing.JCTextField txtImporte;
    // End of variables declaration//GEN-END:variables
}
